### ISSUE TITLE
Smart cherub baby Machine turns off instantly

### ISSUE THREAD

**Issue by boehser-enkel** [krahabb/meross_lan#102]
## Version of the custom_component
2.3.3

## Configuration

```
Configuration all via UI. Device was found automatically



```

## Describe the bug
Turn on via HA: turns instantly off (brightness is remembered if i turn it on via app afterwards

## Debug log

```2021-10-08 09:22:36 DEBUG (MainThread) [custom_components.meross_lan] MerossHttpClient(192.168.88.34): HTTP POST method:(SET) namespace:(Appliance.Control.ToggleX)
2021-10-08 09:22:36 DEBUG (MainThread) [custom_components.meross_lan] MerossHttpClient(192.168.88.34): HTTP POST method:(SET) namespace:(Appliance.Control.Light)
2021-10-08 09:22:36 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [2782113672] Sending {"id": 52, "type": "result", "success": true, "result": {"context": {"id": "b648b8ebac9747b213f217dbb95047c1", "parent_id": null, "user_id": "84b7674c7b4944b7be01194b0011833e"}}}
2021-10-08 09:22:36 DEBUG (MainThread) [custom_components.meross_lan] MerossHttpClient(192.168.88.34): HTTP Response ({"header":{"messageId":"005aabbb339548b9bc0d0ee664032c99","namespace":"Appliance.Control.ToggleX","method":"SETACK","payloadVersion":1,"from":"/appliance/2103033228816690844148e1e94fa7a6/publish","timestamp":1633677756,"timestampMs":972,"sign":"2c448f3c5eb761acc14cc62803eedf4a"},"payload":{}}
)






2021-10-08 09:22:36 DEBUG (MainThread) [custom_components.meross_lan] MerossHttpClient(192.168.88.34): HTTP Response ({"header":{"messageId":"005aabbb339548b9bc0d0ee664032c99","namespace":"Appliance.Control.Light","method":"SETACK","payloadVersion":1,"from":"/appliance/2103033228816690844148e1e94fa7a6/publish","timestamp":1633677756,"timestampMs":286,"sign":"2c448f3c5eb761acc14cc62803eedf4a"},"payload":{}}
)

```

**Comment by krahabb** [comment]
Hello @boehser-enkel,

the 'smart cherub' is a device I'm really getting to know right now (I've just discovered after your post)

meross_lan is probably trying to use it as a 'light' device (since it exposes that feature through the standard meross protocol) but there are probably some tweaks/additions that must be set in place in order to use it correctly.

If you're up for some contributions in order to help me try implement the correct behaviours I would need a good 'trace' to start with:
could you enable the tracing feature of the component (via the integration configuration UI) while experiencing that behaviour?
After enabling, try to use it and replicate the issue and then post/upload the content of the relevant file saved by tracing under 'meross_lan/traces'
More info [here](https://github.com/krahabb/meross_lan#troubleshooting) on the tracing feature

**Comment by boehser-enkel** [comment]
No its the same faulty behaviour when i change brightness/color only

**Comment by rjmcfadd** [comment]
Is there a way to control the sounds from this device with this addon?

**Comment by krahabb** [comment]
Hello @rjmcfadd ,
Not at the moment. The smart cherub was really a surprise to me so I've never had a chance to figure out the device. I was about to buy one in order to test and implement a complete support but it disappeared from Amazon and I haven't check it again.
I'll soon check again if I can find a 'reasonable' seller around.
I'm also thinking about 'mocking' some code to be able to select and start playing a song but without a proper device to test that will probably fail. I could use some hints from the logs posted here in order to try 'guess' the protocol.
We'll see. At the moment I'm trying to fix and refine some pending issues in the code in order to improve meross_lan overall reliability but there is no big feature update incoming

**Comment by rjmcfadd** [comment]
Hi @krahabb, thanks for the reply. I enabled debug tracing and found this when I play sounds, I'm not sure if this will help. 

`2021/11/05 - 10:53:59	http	GET	Appliance.Control.Mp3	{"mp3": {}}
2021/11/05 - 10:53:59	http	GETACK	Appliance.Control.Mp3	{"mp3": {"channel": 0, "lmTime": 1636108537, "song": 9, "mute": 1, "volume": 16}}`

If you have time to work on this and need someone to help test/debug, I could help with that. Thanks!

**Comment by sebirdman** [comment]
I can confirm that the light turns on/off as expected now. 

@krahabb did you get anywhere with the sounds? If not i may take a look at it. I started to look into implementing this a while back on the Cloud Integration, but i'd much rather do it local.

**Comment by boehser-enkel** [comment]
> I can confirm that the light turns on/off as expected now.

I can't confirm that

**Comment by rjmcfadd** [comment]
> Quick update, I'm actually working more closely on this device. Even if I don't have one I should be able to develop a reasonable interface for the sounds. Btw, what is the actual behaviour on the light feature? Does it work on the latest release (2.5.4) ?

That would be awesome! The light part of it works perfectly for me right now. Thanks!

**Comment by boehser-enkel** [comment]
> Quick update,
> I'm actually working more closely on this device. Even if I don't have one I should be able to develop a reasonable interface for the sounds.
> Btw, what is the actual behaviour on the light feature? Does it work on the latest release (2.5.4) ?

No change for me

**Comment by boehser-enkel** [comment]
After the latest update everything works finde. Media Playback can Start. But how do I choose a specific sound effect?

**Comment by krahabb** [comment]
I'm releasing today the 'final' version which should allow you to use it as a media player and choose songs..as usual I've just tested it on an emulated software device so I'm not sure it'll work but I'm pretty confident it will

**Comment by boehser-enkel** [comment]
Thank you that’s great

**Comment by rjmcfadd** [comment]
It's working! Thank you for getting this to work!

How do you change to different sounds? I can only get it to play 1 of the sounds and don't see any way to pick which sound plays.

**Comment by krahabb** [comment]
In my testing, when the media_player is 'playing', you should see the canonical 'track next/prev' buttons on the player in order to switch song.
It's a bit annoying you have to play before being able to change the track but the media_player entity is under 'heavy lifting' in HA so I guess things are going to change soon

**Comment by rjmcfadd** [comment]
Ok, thank you. I don't know how I missed that!
