### ISSUE TITLE
MSS210 gets detected by Meross LAN but then goes offline

### ISSUE THREAD

**Issue by DanyGijon** [krahabb/meross_lan#107]
I´m testing this integration for the first time. Managed to reconfigure a MSS210 using MEROSS app from bytespider and I can see Mqtt messages arriving to Mosquito broker. Eventually, plug gets detected by Meross LAN integration and automatically configured on home assistant, but after some minutes goes unavailable and never works again. I have tried several times and same behaviour every time. I have seen the following on integration logs: 

2021/11/03 - 23:57:13	auto	LOG	INFO	MerossDevice(19011804581223251h0434298f1a4b07) client connection error in async_http_request: TimeoutError
2021/11/03 - 23:57:13	auto	LOG	INFO	MerossDevice(19011804581223251h0434298f1a4b07) switching protocol to MQTT
2021/11/03 - 23:57:13	mqtt	GET	Appliance.System.All	{"all": {}}
2021/11/03 - 23:57:13	auto	LOG	WARNING	MerossDevice(19011804581223251h0434298f1a4b07) error in async_http_request: local variable 'response' referenced before assignment
2021/11/03 - 23:57:19	mqtt	GET	Appliance.System.All	{"all": {}}
2021/11/03 - 23:57:29	auto	LOG	INFO	MerossDevice(19011804581223251h0434298f1a4b07) switching protocol to HTTP
2021/11/03 - 23:57:29	http	GET	Appliance.System.All	{"all": {}}
2021/11/03 - 23:57:39	auto	LOG	DEBUG	MerossDevice(19011804581223251h0434298f1a4b07) going offline!
2021/11/03 - 23:57:39	http	GET	Appliance.System.All	{"all": {}}
2021/11/03 - 23:57:40	http	GETACK	Appliance.System.All	{"all": {"system": {"hardware": {"type": "mss210", "subType": "us", "version": "2.0.0", "chipType": "mt7682", "uuid": "", "macAddress": ""}, "firmware": {"version": "2.2.2", "compileTime": "2021/09/01 18:47:09 GMT +08:00", "encrypt": 1, "wifiMac": "", "innerIp": "", "server": "", "port": "", "userId": ""}, "time": {"timestamp": 1635980258, "timezone": "Europe/Madrid", "timeRule": [[1635634800, 3600, 0], [1648339200, 7200, 1]]}, "online": {"status": 0}}, "digest": {"togglex": [{"channel": 0, "onoff": 1, "lmTime": 1635882409}], "triggerx": [], "timerx": []}}}
2021/11/03 - 23:57:40	auto	LOG	DEBUG	MerossDevice(19011804581223251h0434298f1a4b07) back online!
2021/11/03 - 23:57:44	auto	LOG	INFO	MerossDevice(19011804581223251h0434298f1a4b07) client connection error in async_http_request: TimeoutError
2021/11/03 - 23:57:44	auto	LOG	DEBUG	MerossDevice(19011804581223251h0434298f1a4b07) going offline!
2021/11/03 - 23:57:44	auto	LOG	WARNING	MerossDevice(19011804581223251h0434298f1a4b07) error in async_http_request: local variable 'response' referenced before assignment

Deployment is as follows: 
Home assistant core-2021.7.1
OSX 11.2.1

Many thanks in advance for your great work and effort.
Regards

**Comment by krahabb** [comment]
Hello @DanyGijon ,
Thank you for your comments!
I see by the log that MQTT messages never get replied so I guess there could be some issues in the MQTT configuration.

In order to check the mqtt configuration is properly working at the 'highest' level you could enter the HA MQTT configuration pane (from the MQTT integration UI) and start listening on the following topic:
`/appliance/#`
When 'listening' is enabled reboot the plug and see if you get a bunch of 'PUSH' messages on the `/appliance/19011804581223251h0434298f1a4b07/publish` topic (you should also get a message when you manually toggle the plug)

If you're able to see these messages then it means MQTT is ok and we can proceed to the next troubleshooting

The next step is to check that the device key is properly configured. There are no logs stating any issue in device key configuration but I'm not actually sure the trace you posted would contain that.
If you set any 'key' when using the bytespider utility to configure the device you should also set the same key in meross_lan configuration entry (integration UI). If you leave the key configuration field empty in meross_lan my code tries to 'hack' the protocol but that is sometimes unreliable so ensuring the key is correct woudl save us from further pain.

If everything is correct up to this point then I might suspect something 'new' is happening with the device protocol: from your logs I've seen an 'extra' field (namely the 'encript' field) which I've never seen so far, at least in my own testing so it might be the firmware of the device is 'too new' for meross_lan to keep up but we'll see if that is the case.

Let's see if these tests prove useful.

Also, as a final note: if the device is completely firewalled from the internet the issue could be due to the inability for the device itself to reach an NTP service while booting: some devices I've tested were working like this: they would not boot correctly (and keep so rebooting) if they were not able to get a proper NTP time configuration. Other devices instead did work correctly even when completely firewalled so I really don't have a general rule but the lacking of NTP connectivity for the device could be another source of issues.

I hope this could help fix the 'troubles'

**Comment by DanyGijon** [comment]
Hi, 

Thanks a lot for the quick answer and detailed troubleshooting steps. Let's see if this helps:

- I didn´t configure any key when using the bytespider tool so I left that blank when addind the device to home assistant. Hope that is the correct way.
- Device is not firewall so it should be able to reach any NTP. I don't have a pcap trace so can't be sure if it's trying or not
- Indeed this device is using the latest version available, actually this new release was a causing trouble even with device connected to the cloud. Meross has sent me a previous release ( 4.1.17 if I remember correctly ) so I might be able to test again and check results. 
- Regarding Mqtt , let me know if this helps: 
{"header":{"messageId":"36465a03889ccafc30837f300d275037","namespace":"Appliance.System.Report","method":"PUSH","payloadVersion":1,"from":"/appliance/19011804581223251h0434298f1a4b07/publish","timestamp":1635979935,"timestampMs":551,"sign":"0c0010e6804d9a5a789af4c7bf7876be"},"payload":{"report":[{"type":"1","value":"0","timestamp":1635979935}]}}
{"header":{"messageId":"3b32948fa40690822c40e582d6f24cbd","namespace":"Appliance.Control.Bind","method":"SET","payloadVersion":1,"from":"/appliance/19011804581223251h0434298f1a4b07/subscribe","timestamp":1635979939,"timestampMs":4,"sign":"6ce161c26f871326efb28e62ed42c24b"},"payload":{"bind":{"bindTime":1635979939,"time":{"timestamp":1635979939,"timezone":"Europe/Madrid","timeRule":[[1635634800,3600,0],[1648339200,7200,1]]},"hardware":{"type":"mss210","subType":"us","version":"2.0.0","chipType":"mt7682","uuid":"19011804581223251h0434298f1a4b07","macAddress":"34:29:8f:1a:4b:07"},"firmware":{"version":"2.2.2","compileTime":"2021/09/01 18:47:09 GMT +08:00","encrypt":1,"wifiMac":"d8:0d:17:f5:7a:ea","innerIp":"192.168.68.115","server":"192.168.68.100","port":8883,"userId":0}}}}
{"header":{"messageId":"9f61200f24954559a43928ab20daf921","namespace":"Appliance.System.All","method":"GETACK","payloadVersion":1,"from":"/appliance/19011804581223251h0434298f1a4b07/publish","timestamp":1635979940,"timestampMs":307,"sign":"676d6683494be40e3d853b73f558d717"},"payload":{"all":{"system":{"hardware":{"type":"mss210","subType":"us","version":"2.0.0","chipType":"mt7682","uuid":"19011804581223251h0434298f1a4b07","macAddress":"34:29:8f:1a:4b:07"},"firmware":{"version":"2.2.2","compileTime":"2021/09/01 18:47:09 GMT +08:00","encrypt":1,"wifiMac":"d8:0d:17:f5:7a:ea","innerIp":"192.168.68.115","server":"192.168.68.100","port":8883,"userId":0},"time":{"timestamp":1635979940,"timezone":"Europe/Madrid","timeRule":[[1635634800,3600,0],[1648339200,7200,1]]},"online":{"status":0}},"digest":{"togglex":[{"channel":0,"onoff":1,"lmTime":1635882409}],"triggerx":[],"timerx":[]}}}}
{"header":{"messageId":"bec402a8652d979a84864df010a9aa07","namespace":"Appliance.Control.Bind","method":"SET","payloadVersion":1,"from":"/appliance/19011804581223251h0434298f1a4b07/subscribe","timestamp":1635979947,"timestampMs":786,"sign":"73a79e018fdd4e1562b958f9c4ed1cd4"},"payload":{"bind":{"bindTime":1635979947,"time":{"timestamp":1635979947,"timezone":"Europe/Madrid","timeRule":[[1635634800,3600,0],[1648339200,7200,1]]},"hardware":{"type":"mss210","subType":"us","version":"2.0.0","chipType":"mt7682","uuid":"19011804581223251h0434298f1a4b07","macAddress":"34:29:8f:1a:4b:07"},"firmware":{"version":"2.2.2","compileTime":"2021/09/01 18:47:09 GMT +08:00","encrypt":1,"wifiMac":"d8:0d:17:f5:7a:ea","innerIp":"192.168.68.115","server":"192.168.68.100","port":8883,"userId":0}}}}
{"header":{"messageId":"7938ec0e128e495ab0bccbf99d8b825a","namespace":"Appliance.Control.TriggerX","method":"GETACK","payloadVersion":1,"from":"/appliance/19011804581223251h0434298f1a4b07/publish","timestamp":1635979947,"timestampMs":876,"sign":"8eae5f6bb38b5578cd6598000625d007"},"payload":{"digest":{},"triggerx":{}}}
{"header":{"messageId":"9a9837e3801d472e906b3ddd3fd0b2d5","namespace":"Appliance.Control.ToggleX","method":"GETACK","payloadVersion":1,"from":"/appliance/19011804581223251h0434298f1a4b07/publish","timestamp":1635979947,"timestampMs":882,"sign":"fdba675c740a03d80c66ec98bdf1c004"},"payload":{"channel":0,"togglex":{"channel":0,"onoff":1,"lmTime":1635882409}}}
{"header":{"messageId":"064c2977105a4053ad64c7c01972634b","namespace":"Appliance.Digest.TriggerX","method":"GETACK","payloadVersion":1,"from":"/appliance/19011804581223251h0434298f1a4b07/publish","timestamp":1635979947,"timestampMs":927,"sign":"ed2a095bca1075db8566da4c8b330430"},"payload":{"digest":[]}}

**Comment by krahabb** [comment]
Well, it looks a bit weird to me:
First thing is you can see the MQTT device flow so it seems everything is really ok on the MQTT configuration.
Also, if you left the key empty in configuration the same way as in meross_lan that is ok so everything should be fine also on this.
I don't get the `Appliance.Control.Bind` messages coming through anyway: meross_lan don't use these messages since I don't know what's their meaning (I guess they're related to the MQTT binding procedure but I think they're only used from the official Meross App and/or when the device is 'binded' to the Meross cloud services).
Are you maybe using other software that could in some way talk to the device? Maybe something 'homekit' related or the Meross app itself is trying to discover/using the device locally on your LAN?

Or maybe that message is just 'pushed' automatically by the device (even though I've never seen that in my devices) and maybe my implementation lacks a correct response in order to tell the device everything is ok and keep it working.

Also, the `Appliance.Control.TriggerX` with method `GETACK` looks like a response to a similar `GET` message sent to the device over MQTT but still, meross_lan never issues that kind of inquiry (unless tracing is enabled)
