### ISSUE TITLE
How to set value for open window detection?

### ISSUE THREAD

**Issue by a-waider** [krahabb/meross_lan#110]
Hello @krahabb,

I really love your HA integration. Setting up devices worked with ease on first try. But there is one thing that I'm unsure if this is supported. My setup includes the MTS100 thermostat valves. The official Meross app allows you to set a temperature threshold when to assume that the window is open. Is it possible with this implementation to configure this threshold?

**Comment by krahabb** [comment]
Hello @a-waider ,
Thank you for pointing at this. It should be possible though, even if I didn't spend any time in the beginning investing the commands available to configure the MTS100.
I'll do some tests with mine and I think I can provide an implementation. Not sure about the timing though..I'm a bit random lately with spare time so I don't really have much time to reliably implement code updates...but I'mm definitely willing to!

I'll surely release something before dec since there's a breaking HA core change incoming and I need to update for that in order to keep the MQTT part of the integration working. I'll try to fill in this feature too

Thank you

**Comment by krahabb** [comment]
Hello @a-waider !
I was jumping into this feature but I'm a bit lost with testing since my devices are not paired anymore to the official app and, by looking at the traffic and api they are exposing now, I can't really get where the 'openwindow temperature threshold' could be set.
I've found the commands/payloads to set the heat/cool/night temperature setpoints and the actual room temperature correction but nothing points me to the openwindow threshold.
If you're up with some spare time could you please try to configure one of yours with the meross app by setting a threshold different than default and then 'trace' the device in meross_lan?

In order to 'trace' I'll point you to [this](https://github.com/krahabb/meross_lan#troubleshooting) so you can enable this feature in meross_lan in order to collect the data your devices are communicating with meroos_lan.
I hope this way to find something 'different' from mines so to maybe guess where this setting could be achieved.

**Comment by a-waider** [comment]
Hey @krahabb,

thanks for your effort so far. Currently I've all my meross devices moved to this integration to be less dependent on the cloud. Just got approved for this decision by my ISP that had an outage today for about 7 hours. 

I'll do the testing you mentioned and come back to you. Is there any documentation for the API calls? If that's the case I'd like to push my results. While I'm doing this, is there anything else I can test or trace some more API calls?

**Comment by a-waider** [comment]
It's me again @krahabb,

sooo, there was some confusion about this open window threshold feature. I setup the valves again with the meross app and couldn't find the open window setting I was searching for. I must have messed up with different systems I tested with lately. Homematic IP for example has this feature.

In a nutshell: There is no feature to be added.

**Comment by krahabb** [comment]
Ah well..tbh I've also read on the plain manual that the valve had a threshold setting for open window detection and it looked like this setting could also be customizable..well maybe in the future we'll get to a point.
I can't 'physically' manage mines at the moment since they're in a different house but maybe there's a device menu we can access by the buttons.
I'll leave this issue open as a reminder to me since I'm adding some helpers entities to this device in order to allow some configurations from HA (like temperature correction and so on)
