### ISSUE TITLE
MTS100: hvac_modes

### ISSUE THREAD

**Issue by lucagasperi** [krahabb/meross_lan#111]
Hello @krahabb,

I really love your HA integration, everything works flawlessly and got it on first try.
I added all my 7 MTS100 thermostatic valves but I see in the HA "Thermostat" Card that show up only 3 modes: "auto", "heat" and "off".

I would really appreciate if it could be possible to have the same settings like in the Meross app:
auto
cool --> default set to 21°C
heat --> default set to 27°C
off

If it's not possible, at least I would like to make entities let to assume the "cool" hvac_mode in order to easily recognize which valve is asking for warm in my system.

Thank you very much for your work!

**Comment by krahabb** [comment]
Hello @lucagasperi ,
The HA thermostat panel by default only shows available hvac_modes while meross_lan uses 'presets' to accomplish what you are asking for since the different options available in Meross App are, by all means, presets for the same 'heat' mode. In order to choose the relevant Meross 'preset' ('cool', 'warm',...) you'd have to enter the HA climate form details and choose this 'preset' mode.
When you look at those preset you'll see I've chosen different terms than the one used by the app since HA already have a list of common mode names which are also localized and these modes don't always match with the Meross terms.
As an example, in HA UI you'll find 'Comfort' for what is 'heat' in Meross app. I'm sorry for the confusion but I didn't find a friendly way to overcome this since Meross app itself could have different localizations for those terms than the one I would use in HA and beside don't knowing how Meross localizes these, more importantly, there's no way (at least to my knowledge) I can put these localizations in HA.
So you're left with some 'intuitive' terms in HA which corresponds to these Meross settings.
Also, there's no actual way to explicitly change these preset temperatures from HA (i.e. there's no configuration form for these) but still, when you set a 'preset' mode in HA and change the target temperature, you're actually changing the preset in the Meross valve.

Very important: when you set the hvac_mode or the preset to 'Auto' (they'll both accomplish the same valve setting) the valve turns to 'time schedule' mode so it follows the timer scheduled settings configured by the app. These too are not configurable from HA.
