### ISSUE TITLE
Support MOD100 - Diffuser

### ISSUE THREAD

**Issue by gabriellferreira** [krahabb/meross_lan#127]
**Is your feature request related to a problem? Please describe.**
I integrated this module into my HA, and a MOD100 was detected but without any entity or control. I know this model is not supported and this is exactly why I'm writing this, I'd like to contribute integrating this one.

**Describe the solution you'd like**
I'd like to know if is your interest to integrate it, and how could I help.
This model to work has controls of on/off, RGB color, led intensity, and misty mode. 

**Additional context**
* [MEROSS - MOD100](https://www.meross.com/Detail/93/Smart%20Wi-Fi%20Essential%20Oil%20Diffuser)
* Short tracing log:

> 2021/12/07 - 20:25:54	TX	http	GET	Appliance.System.All	{"all": {}}
> 2021/12/07 - 20:25:54	RX	http	GETACK	Appliance.System.All	{"all": {"system": {"hardware": {"type": "mod100", "subType": "un", "version": "3.0.0", "chipType": "mt7682", "uuid": "################################", "macAddress": "#################"}, "firmware": {"version": "3.1.5", "compileTime": "2020/09/01 17:03:31 GMT +08:00", "wifiMac": "#################", "innerIp": "#############", "server": "##################", "port": "###", "userId": "#######"}, "time": {"timestamp": 1638905153, "timezone": "Europe/Madrid", "timeRule": [[1616893200, 7200, 1], [1635642000, 3600, 0], [1648342800, 7200, 1], [1667091600, 3600, 0], [1679792400, 7200, 1], [1698541200, 3600, 0], [1711846800, 7200, 1], [1729990800, 3600, 0], [1743296400, 7200, 1], [1761440400, 3600, 0], [1774746000, 7200, 1], [1792890000, 3600, 0], [1806195600, 7200, 1], [1824944400, 3600, 0], [1837645200, 7200, 1], [1856394000, 3600, 0], [1869094800, 7200, 1], [1887843600, 3600, 0], [1901149200, 7200, 1], [1919293200, 3600, 0]]}, "online": {"status": 1}}, "digest": {"triggerx": [], "timerx": [], "diffuser": {"type": "mod100", "light": [{"channel": 0, "onoff": 0, "lmTime": 1638904844, "mode": 0, "luminance": 100, "rgb": 2621184}], "spray": [{"channel": 0, "mode": 2, "lmTime": 1636250932}]}}}}

**Comment by krahabb** [comment]
Hello @gabriellferreira ,
I'm a bit busy at the moment but would definitely like to add support for this. Let's see if I can get back on it in the next weeks: I'll 'bump' you some updates

**Comment by LupoCri** [comment]
Hi @krahabb ...

any update about MOD100 device integration?

Thx for all.

LC

**Comment by krahabb** [comment]
Hello @LupoCri and @gabriellferreira ,
I'm back at coding for meross_lan and I'm trying to add some features like MOD100 support.
From the log chunk I can guess a bit but I would definitely need a full trace for the device ([instructions here](https://github.com/krahabb/meross_lan#troubleshooting)).
During tracing (which should last 10 minutes) you should operate the device a bit with all of the relevant actions you can do from the app: spray a bit, continuous mode, intermittent, change the light, and anything else (I really don't know for sure what the device is capable of so it's up to you)
This way I should get all of the state changes and then infer a correct implementation

**Comment by LupoCri** [comment]
Here my file.

[mod100-1644417922.csv](https://github.com/krahabb/meross_lan/files/8033711/mod100-1644417922.csv)

Tnx 4 all.

LC

**Comment by krahabb** [comment]
Awesome!!
ThkU

**Comment by LupoCri** [comment]
Hi @krahabb,

No temperature and humidity readings on app... Unfortunately... 
I also think like you about an hidden feature of the device and still not fully supported.

I am at your complete disposal for everything (almost!) ;)

Tnx 4 all.
LC

**Comment by LupoCri** [comment]
Hi all.

After deleting and re-adding the MOD100 I can see only  2 commands: _Light_ on/off and _Spray_. They are also read-only and the "eco" spray is not detected.

**Comment by krahabb** [comment]
That's sad :(
Could you post another trace with the new version?
Thank you

**Comment by LupoCri** [comment]
I hope that's what you need.

I also saw that the color and brightness of the light is correctly displayed by the light bulb icon. 
Is missed the _auto_ color palette function.

Tnx
LC

[config_entry-meross_lan-20941f90e2ad05d33c57b663d8993d71.json (2).txt](https://github.com/krahabb/meross_lan/files/8111174/config_entry-meross_lan-20941f90e2ad05d33c57b663d8993d71.json.2.txt)

**Comment by krahabb** [comment]
Hello @LupoCri ,
I have a couple of questions about the MOD100 - meross_lan integration:
is the SPRAY working somehow? I guess you can actually succesfully control (from HA/meross_lan):
off -> diffuser off
on -> diffuser on full speed
eco -> not working
If this is right I would also ask you if, when changing the device setting from the meross app, HA reflects those changes with the intrinsics delays (30 sec by default due to the polling interval). Of course I guess the eco mode would not be detected from HA and when you set it on the MOD100 HA should likely show you an 'unknown' value or so.
The trace you posted contains an unknown mode value (for the spray) which is likely the reason of meross_lan not working.
In order to correctly decode the meaning of this value we have to setup a more 'sophisticated' trace when you'll have time:
Supposing the MOD100 is more or less working in HA (that means the basic commands are ok) you should grab a trace with this sequence (use always the app to change the mode settings on the MOD100). Also, you can change the trace timeout in the MOD100 configuration on HA to be some like 4 minutes (240 seconds in HA config form)
- put the diffuser spray off 
- start tracing
- after 1 min put the diffuser on intermittent
- after 1 min put the diffuser on full/continuos 

This should help resolve the SPRAY function (at least)

As for the light part I don't understand what works and what not. From your description I understand you cannot control the light except for the on/off button: is this right? and does it work ?

You should check under 'Developer tools'->'States' the attributes reported for the light itself. You should get something like this:
```yaml
supported_color_modes:
  - rgb
color_mode: rgb
brightness: 255
hs_color:
  - 13.647
  - 100
rgb_color:
  - 255
  - 58
  - 0
xy_color:
  - 0.68
  - 0.316
friendly_name: Smart Humidifier (01234567890123456789012345678902)
supported_features: 0
```
we should try some tracing/testing in the same way as per the spray but I prefer to proceed step by step. Let's just focus on the spray and see what is happening

**Comment by krahabb** [comment]
Quick update,
I'm looking into https://github.com/bwp91/homebridge-meross and I've discovered a lot of stuff regarding the MOD100 (if their implementation is correct I could 'clone' informations from there to update mine)
From what I've read I've discovered that actual on/off/eco modes in meross_lan are at least mismatching the real working modes for the diffuser spray.

Also , the light is even more intriguing since it looks like the MOD100 light has 3 different operating modes:
color mode: where you set the rgb values and I guess the light stays fixed with the rgb set
temperature mode: I don't get it
rainbow mode: I don't get it

The latter are probably some kind of effects where the diffuser light behaves according to a predefined set (maybe changing with the spray intensity or just repeating a pattern..who knows)

Actually, meross_lan doesn't know how to set this 'mode' parameter (except I've seen that but I didn't know anything about its use) so.
I could guess that, if you set the light in 'color mode' on the app, then HA should be able to change the color.
If that is true, and my reported understanding of these modes is correct I'll go straight for a patch.

I need your explanations ;) so, if you can provide a sort of description of these features, like what you can do with the app and which options you have that would help me integrate my knowledge

**Comment by AndreaSpampi** [comment]
Se può essere d'aiuto il MOD100 ha le seguenti funzioni (da applicazione):

- Accendere la luce
- Impostare la colorazione della luce
- Impostare la colorazione della luce casuale
- Accendere lo spray (LOW)
- Accendere lo spray (ALTO)

Nel momento in cui sto scrivendo il MOD100 funziona solo con l'applicazione smartphone, su HA riesco solo a vedere lo stato (che si aggiorna modificando sull'applicazione smartphone) ma non è possibile attivare/disattivare lo spray, accendere e spegnere la luce e modificare i colori.

Spero che questa mia informazione sia d'aiuto in qualche modo. Grazie mille per il bellissimo lavoro che state svolgendo.

Andrea

**Comment by LupoCri** [comment]
Ringrazio @AndreaSpampi e mi scuso con @krahabb per il mio inglese maccheronico.

**Comment by LupoCri** [comment]
@krahabb intanto:

Per lo spray:
options:
  - 'off'
  - 'on'
  **- eco**
device_class: spray
friendly_name: Umidificatore Camera 

Notare l'eco _non stringa_

Per la luce:

supported_color_modes:
  - rgb
friendly_name: Umidificatore Camera Cristiano
supported_features: 0


LC

**Comment by AndreaSpampi** [comment]
@LupoCri dimenticavo, c'è anche l'opzione per la luce "ciclo automatico"!  Grazie per tradurmi io e l'inglese non andiamo d'accordo :)

**Comment by krahabb** [comment]
I've just published a 'beta' in pre-releases with a lot of fixes for the MOD100.
By learning through https://github.com/bwp91/homebridge-meross I've discovered my code (2.5.4) couldn't really send working commands.
Incoming (2.5.5) release should finally send the commands and (hopefully) work.

Thank you all for your contributions, I hope I finally got this device!

Waiting for your comments ;)

**Comment by AndreaSpampi** [comment]
Great! As soon as I get home, I check. In the meantime, thank you very much for your work! (This time I did the translation with Google lol)

**Comment by AndreaSpampi** [comment]
@krahabb My compliments, everything works perfectly :)
