### ISSUE TITLE
MSS425e not discoverable

### ISSUE THREAD

**Issue by labactani** [krahabb/meross_lan#133]
Hi, I am using the integration and works great with all my Meross switches (2x MSS210 and 1xMSS425e) with the exception of my second MSS425e which is not discoverable.
All the entities are still paired with the Meross app, so the communicate via HTTP.

Looks like the integration discover the switch, but fails in adding it.

This is what I get in the log 

__Logger: homeassistant
Source: custom_components/meross_lan/config_flow.py:110 
Integration: Meross LAN (documentation, issues) 
First occurred: 16:02:44 (4 occurrences) 
Last logged: 16:02:44

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 230, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/meross_lan/config_flow.py", line 110, in async_step_dhcp
    LOGGER.debug("received dhcp discovery: %s", json.dumps(discovery_info))
  File "/usr/local/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DhcpServiceInfo is not JSON serializable__

**Comment by krahabb** [comment]
Hello @labactani,
yes, there's an incompatibility with some new (2021.12) core api changes so the dhcp discovery is not working at the moment.
You should be able to add the device manually by just adding meross_lan integration from the 'Integrations' UI. Fill in ip address and device key and it should work without any other issue (the dhcp fix is coming but it's just a bug in the discovery process, no other consequences)

**Comment by labactani** [comment]
Hi @krahabb,
thanks for the feedback - I have tried to add the device manually but the UI just asks me for the device key and not the IP address - see screenshot.
And whatever device key I put in, the integration just create the MQTT hub..
<img width="540" alt="Schermata 2021-12-13 alle 08 43 09" src="https://user-images.githubusercontent.com/80811693/145771863-5cc49f05-3646-489d-8e1e-b2a49790fc17.png">
.

**Comment by krahabb** [comment]
Ah yeah..sorry for that.
The flow is not really 'user friendly'
That mqqt hub is a configuration entry for meross over mqtt and is not used if you're just using http.
Nevertheless meross_lan 'wants' this configured at first.
Now, forget about it, you could even disable it but not remove, and add a new meross_lan entry😊

**Comment by labactani** [comment]
Ok, got it! Now it works.
thanks a lot

**Comment by thorrrr** [comment]
HI 
I have tried adding a MSS210 i already have 3 which was auto discovered when i added them. I now find they are not found by HA working fully in Meross App but cannot get it discovered in HA

Log

Logger: homeassistant
Source: custom_components/meross_lan/config_flow.py:110
Integration: Meross LAN (documentation, issues)
First occurred: 16:34:12 (3 occurrences)
Last logged: 16:34:12

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 230, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/meross_lan/config_flow.py", line 110, in async_step_dhcp
    LOGGER.debug("received dhcp discovery: %s", json.dumps(discovery_info))
  File "/usr/local/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DhcpServiceInfo is not JSON serializable

**Comment by thorrrr** [comment]
When you say fixed has the fix been released yet?

**Comment by sk8er000** [comment]
My 2 MSS425e are discovered like "MEROSS LAN" devices and if I try to configure them they require the key to be added (wich I don't know). 
My mss310h was correctly discovered and configured without key and my msh300 hub is also discovered, but I'm quite anxious about configuring this last one since last time I added it (a year ago) meross banned my account and I lost all my heating programs

**Comment by thorrrr** [comment]
mine is working fully now

**Comment by sk8er000** [comment]
is using the devices along with the key risky? From my understanding if I provide the device key the device won't be reached locally but through the meross servers and if nothing is changed meross isn't happy habout that and prone to suspend the accounts

**Comment by krahabb** [comment]
@sk8er000 ,
meross_lan is not using any Meross cloud api to communicate with the devices so you should be safe from banning and the likes.

If any, the only feature which is actually using an official Meross service is the login procedure used to recover the device key when you initially configure the device.
This is evident since you have to provide your cloud credentials there. These credentials, nor any token, are not cached in meross_lan so any subsequent request would be started from scratch by providing the credentials again when asked for and this is only happening when configuring the device. meross_lan actually caches the device key which is unique per account so, if you later have to configure a new device meross_lan itself will pre-fill the device key with the cached one in order to not need a new cloud login

The 'official' device key is needed in order to communicate with the devices: be it local or cloud it doesn't make any difference: the device wants the protocol messages signed accorded to a basic crypto-signing algorithm using the key which is set by the app when it configures the device.
meross_lan uses the key to communicate locally over http when the devices are still paired to Meross app/cloud so it is a kind of parallel communication: 
- the device still works with the official Meross app through some 'owned' mqtt servers which form the Meross cloud infrastructure: this is where you could get 'banned' or 'rate limited'
- meross_lan talks directly via HTTP to the devices so bypassing any Meross service

The fact that you could get banned by using Meross devices in HA is related to using another previous integration which instead used to interact directly with the Meross MQTT servers acting more or less like the official app. This is not to blame that integration: the problem lies in the rate limiting posed by the official cloud api so it was like a real bottleneck.

So, if your devices are still paired with the Meross app you'd better off configuring the correct key for all of these: this will ensure the protocol exchanges are correctly signed. If not, a device configured with an empty key, would need to perform a key-hack scheme which still I'm not confident is working reliably every time

**Comment by sk8er000** [comment]
thank you for the detailed explanation, now I can use my Meross devices without the risk of being blocked on the Meross servers!
