### ISSUE TITLE
"Unable to connect" when configuring MSL120

### ISSUE THREAD

**Issue by klyoku** [krahabb/meross_lan#142]
## Version of the custom_component

v2.4.3

## Configuration

Configured through the UI

## Describe the bug
MSL120 RGB bulb gets discovered automatically. When I try to add it, it prompts for login and grabs the device key as expected. but afterwards shows the "unable to connect" error as seen below.

![2021-12-30_16-39-38](https://user-images.githubusercontent.com/43735351/147835499-49542005-b0b9-4403-be08-82f4c7e3f05b.png)

I was able to add my other devices (MSS110 and MSS130), but neither of the MSL120 bulb seem to work. 
Meanwhile I'm still able to use the meross app, and the other merossIoT integration seems to work fine. 

## Debug log

```text

This error originated from a custom integration.

Logger: custom_components.meross_lan
Source: custom_components/meross_lan/config_flow.py:94
Integration: Meross LAN (documentation, issues)
First occurred: December 30, 2021, 4:34:37 PM (90 occurrences)
Last logged: 10:18:24 AM

Error () configuring meross device (host:192.168.210.76)
Error (Server disconnected) configuring meross device (host:192.168.210.76)

```

**Comment by krahabb** [comment]
Hello @klyoku ,
I'm unable to figure out the issue at the moment. I'd probably need to add some specific debug/tracing features in order to better intercept what's going on here.
You could anyway try enabling debug logging for meross_lan (a bit verbose, depending on how many devices you have configured so be careful to disable it after few interactions and a bit boring manual process so it's up to you:)

In order to do so put this in global HA configuration.yaml
```yaml
logger:
  default: info
  logs:
    custom_components.meross_lan: debug
```

the logs would then be posted to the global HA log (usually in the same folder as configuration.yaml).
Copy-paste and then submit the meross_lan messages

**Comment by klyoku** [comment]
Thanks @krahabb. Attached is the debug log. 
[home-assistant.log](https://github.com/krahabb/meross_lan/files/7799836/home-assistant.log)

**Comment by krahabb** [comment]
Hello @klyoku ,
I've found your devices (those already working) are configured with an empty key since the log reports they're using the 'key hack' mode.
Nevertheless these devices are working good (apparently: I don't see any issue in the log so far...) likely due to their firmware being 'nice' against the key hack algorithm.
I suggest you to fix and configure the proper key for these devices in meross_lan configuration by using the same key you grabbed for the msl120 (I guess they're all binded to the same meross account).

This is not going to help with the msl120 but is a nice thing to do in order to prevent future issues.

Now to the msl120:
when detected by dhcp, meross_lan tries an initial automatic identification by using a set of keys from previous configured devices. It looks like meross_lan is not using any valid key in this step (2022-01-02 13:41:27 log time).
After that, there's a new interaction with the device, likely your configuration step after HA presents the discovered device UI but still the key is wrong at this point (2022-01-02 13:41:33 log time). Did you enter the previously recovered key from cloud account? (I was able to check your '354e418ea39c6a1be09be359bcef5c16' key against the replies appearing in the log and it is correct for this device)
It looks like you tried to configure the device with an empty key at least initially.
There's another configuration attempt some seconds after (2022-01-02 13:41:45 log time) and this time we see no 'key reply hack' so I guess you retried to configure by using the correct key but the outcome was a failure anyway.

If this is correct I'm supposing the device is actually 'blacklisting' the offending client (HA/meross_lan) so, after the initial key hack tries, even if you set the correct key, it refuses to respond anyway.

Just a guess though but if this is the case I would expect this 'blaklisting' to not last forever or at least to not last between reboots so you could do as follows:

when the device gets discovered try to configure it with the correct key from the beginning (no attempt with blank key). 
If it still fails, keep the HA discovered entry 'alive' i.e. hold on to the HA/meross_lan configuration UI, reboot the device, hope for the same ip address being assigned after reboot and try to configure again (basically just re-submit the configuration form after reboot)

**Comment by klyoku** [comment]
Thanks again for the in-depth response. 
First of all, I went ahead and added the device key to the other devices as you suggested. 

For the MSL120, I was able to successfully add it with the steps you suggested by power-cycling the bulb, and quickly adding it by submitting the correct device key from the get-go. Below is the configuration:
![image](https://user-images.githubusercontent.com/43735351/147963553-18b7e28e-bfa9-40a7-b81b-fc1b2cc76d03.png)

However, the entity seems to go offline pretty much immediately after being added with "unavailable" status:
![image](https://user-images.githubusercontent.com/43735351/147963935-b063d554-f685-416e-b47c-f44c96bc2f8b.png)

Here is the debug log:
[home-assistant.log](https://github.com/krahabb/meross_lan/files/7803326/home-assistant.log)

**Comment by klyoku** [comment]
Sometime else I noticed - all other plugs I have shows up with their model during discovery (right below), but the MSL120 doesn't (left below). 
![image](https://user-images.githubusercontent.com/43735351/148148508-3fcfebab-eb3f-44df-8104-ce1f09772aaf.png)

**Comment by barbatrukko** [comment]
I have the same proble, and also after power-cycling bulb, i can't ADD to meros LAN integration

**Comment by krahabb** [comment]
Hello @barbatrukko ,
The procedure to retrieve the device key from the cloud account is only available when initially configuring the device.
It works like this (sorry for that..I'm still thinking on a better UX for this..)
when you configure the device for the first time, enter the correct address and a non-empty bogus key. The UI should state the 'key is wrong' and you should confirm again with the same key: now you'll be proposed to retrieve the proper key from your meross cloud account.
If you can't make it work with the 'rebel' MSL120 you should remove and reinstall any of the already configured devices.
Once recovered, the key is the same for all of your meross account devices so you can just copy it in the existing configurations

**Comment by jmcollin78** [comment]
Same kinds off problem heree. Msl120dr bulb are sometimes discovered multiple times, sometimes not discovered at all: sometimes you cannot add an equipement because it says it is already added (but not or not visible). I try to remove all integrations, but the problem always arrive after some times. 

I’s seems ok with smart plus Msl210 and with msl120d.

All equipments works fine with the Meross application so I guess the problem is located on the integration.

**Comment by klyoku** [comment]
Not sure when this happened, but I was looking through unrelated things today and found the bulb is now working through this integration. Not sure something changed on Meross side, or this was fixed in another unrelated fix. Just wanted to report here. 
![image](https://github.com/krahabb/meross_lan/assets/43735351/29f07535-ddb5-4921-b58a-7f48dde16418)

**Comment by krahabb** [comment]
stale
