### ISSUE TITLE
MSH300 loses connection when enabled - what can i add to get help?

### ISSUE THREAD

**Issue by cesarebattisti** [krahabb/meross_lan#143]
I purchased an MSH300hk 4.0.0 hub kit with firmware 4.1.27 and
MTS150 valves.
As soon as I install the addon and enable it, the hub loses the connection and starts flashing green light 10 times, then orange light.
in the app I lose the connection with the valves the hub first loses the wi-fi connection then goes off-line in loop.
Naturally the hub and the valves are seen even if with the battery, temperature and windows sensors not available.
is there any way I can make it work or I have to send it all back and buy another type of tube
How can I help to solve problem
thank you

**Comment by krahabb** [comment]
Hello @cesarebattisti ,
Sorry to hear that. The MTS150 were working 'bad' in a previous thread/topic [here](#112) so I can't really say a definitive word.
In the thread, user @override80 was able to get something to work after a 'device return'.

If you are still using the hub paired to the Meross app ensure you configure meross_lan with the proper device key (you can find instructions here and there since the device key mis-configuration is a common issue)

Finally you can try grabbing a trace from the device on meross_lan (instructions are in the same [thread](#112)

**Comment by cesarebattisti** [comment]
Krahabb, thank you very much for the reply. I had read that thread but couldn't. I am seriously considering returning Meross and buying Tadoes which seem more homeassistant supported.
Thanks again.

**Comment by krahabb** [comment]
I've recently fixed a 'behavioural' bug in msh300 (see #167). Not sure if you kept your meross or switched to Tadoes but the incoming release maybe could help.
I'm anyway closing this for the moment. Feel free to restart the issue
