### ISSUE TITLE
[not an issue/bug]  Question about firmware update for MSG100 (Smart garage door accessory)

### ISSUE THREAD

**Issue by EmuZombie** [krahabb/meross_lan#144]
I currently use this integration in http mode in order to keep functionality with the meross app.  Lately I've been experiencing disconnection issue in the meross app and noticed there was a firmware update to "greatly improve connection issues".   

My question is, does anyone know if the new firmware creates issues with this component?  I'd hate to update only to break compatibility with home assistant.

**Comment by krahabb** [comment]
Hello @EmuZombie ,
A couple days ago I also incurred in a firmware update notice on the web (my devices are not paired so I cannot say anything about it) but I remember it was clearly claiming to improve 'homekit' connection experience.
I would hold on a bit anyway. Maybe your connection issues were related to their cloud infrastructure undergoing some issues/maintenance. If your devices were reliably working before, the issue is likely not in your current devices firmware level

**Comment by EmuZombie** [comment]
Thanks for the reply krahabb.  The connection issues I was having seem to have cleared up today, so my guess is your assumption is correct that it was on meross's end.  

Since I'm not experiencing any issues now, (or before for that matter) I will hold off on updating.
