### ISSUE TITLE
MTS200 floor heating thermostat

### ISSUE THREAD

**Issue by Cully81** [krahabb/meross_lan#154]
Hello,

I have a MTS200 floor heating thermostat. I was able to integrate this as device without any problems and can see it as "Smart Thermostat". Unfortunately it does not work yet. For example, I can not select it as a thermostat and see no suitable entities.
Has this not yet been integrated? If so, I am doing something wrong.
Otherwise, I would be very happy about an integration.

Thank you

**Comment by krahabb** [comment]
Hello @Cully81 ,
This is the first time I see the mts200 and, after inspecting its feaures on the meross site I hardly expect this to be integrated correctly except it gets recognized as a meross device.
This is good though since it allows us/you to collect a simple log trace which should be enough for me to provide an implementation for the thermostat.
In order to do so, go to the meross_lan entry configuration in the integrations UI and enable 'tracing' on the entry. The trace will run for like 10 minutes and it could be useful to also 'trigger' some actions on the valve by the use of the meross app or by physically operate it by its panel while the trace is collecting data.
After 10 minutes the tracing is stopped and you'll find the result under '.homeassistant/custom_components/meross_lan/traces'
Please upload it so I can inspect the device capabilities/api

Thank you!

**Comment by Cully81** [comment]
Hello @krahabb 

if I see this correctly, I can only enable tracing on detected devices, right? 
I have added MTS200 as integration. But I don't see it in the overview under integrations. 
There I see only my MSG100 and MRS100. The MTS200 does not appear there. But I can't add it again either, then I get the message "The device already exists".

Translated with www.DeepL.com/Translator (free version)

**Comment by Cully81** [comment]
Here it is:

![grafik](https://user-images.githubusercontent.com/96849812/149761452-f469e9fc-d8bf-4bd5-9171-05f91f0a395b.png)

But I can't see it here:

![grafik](https://user-images.githubusercontent.com/96849812/149761512-8891e89c-9ae3-4807-93ab-1a79f83a1832.png)

**Comment by krahabb** [comment]
Wow..that's weird!
Yes you should be able to see a related entry under integrations where you usually can configure the connection properties. Is it maybe 'ignored' or 'disabled' under integrations?

**Comment by Cully81** [comment]
It gets even weirder.
After a reboot I got the message "New device detected". Then I click on "Configure" the window appears with the message "The device already exists".

![grafik](https://user-images.githubusercontent.com/96849812/149775328-b27ef7c6-147e-4368-90a9-57623b29593f.png)

![grafik](https://user-images.githubusercontent.com/96849812/149775440-6c4652cd-218b-4aa4-8a30-7e17b4737795.png)


But yes, it was actually also in the integration list as "disabled". (I don't remember doing that myself).
I'll send you the logs via PM.

**Comment by krahabb** [comment]
Ok, after re-enabling the configuration entry you'll be able to manage its configuration by hitting 'Configure' on the entry panel.
Now, at the bottom, you should find a checkbox to enable tracing

**Comment by Cully81** [comment]
Here it is
https://www.dropbox.com/s/72mifd0sivihrjo/mts200-1642425928.csv?dl=0

**Comment by Cully81** [comment]
Hi,
I just installed the latest version.
Looks great, thanks a lot.
As far as I could see in my first tests, everything works perfectly.
Only one small thing I noticed:
The name of the middle button with the flame is "Heizen" (heat).
But the function behind it would be "Manuell" (Manually).
Can this be changed?

**Comment by krahabb** [comment]
Hello @Cully81 ,
Thank you for reporting it works: your trace was invaluable to get it right!
As for the 'Heizen' flame, if you refer to the small flame icon right under the big temperature reading on the thermostat physical panel, that should be indicating the current 'state' of the heating circuit i.e. heating (active) or not heating (inactive)
In HA/meross_lan that is reported by the climate entity attribute 'hvac_action' which is the one telling HA what the device is doing (beside its working mode). The value of this attribute is reported in the lovelace climate panel right under the temperature setpoint together with the current working mode (preset):
you usually read 'Idle' in the panel when the flame icon is off while you get 'Heating' while the flame is on. The term right to the hvac_mode is the actual 'preset' or working mode which could be: custom (manual) - comfort (heat) - sleep (cool) - away (eco) - auto (schedule)
There's a bit of mismatch between meross and HA/meross_lan regarding the mts heating modes: the meross uses terms like cooling or so which are not really correct since it is not capable of cooling: I take these 'meross modes' as 'presets' in meross_lan in order to comply with the HA climate entity behaviour.
There's a deeper explanation of these choices [here](#48): even if there were some tweaks to the code this describes the reasoning behind the way meross_lan implements the thermostat/climate and how to translate meross idioms to HA ones.

EDIT:
I might have got it wrong about the 'Heizen' flame you were referring to: if you're talking about the 'Heat' mode icon in the HA lovelace panel then [this thread](#48) is definitely the answer: that icon is HA stuff anyaway and there's no way (at least no one I know) to add a 'Manual' labeling there

**Comment by Cully81** [comment]
Yes exactly, I mean this button

![A62EB3A9-C519-4800-9C3A-B11EE1D1B61F](https://user-images.githubusercontent.com/96849812/155223146-2adf4496-9bb2-491d-9ba8-611d9ec60269.jpeg)

But if that can't be changed, it's not much of a problem.

**Comment by cagnulein** [comment]
@Cully81 is this integration still working to you with the last HASS? I'm getting no entites for a mts200 like yours.
