### ISSUE TITLE
Constant Warning Error in Logs is it an issue or a booting warning

### ISSUE THREAD

**Issue by thorrrr** [krahabb/meross_lan#165]
From Logs on every restart
This error originated from a custom integration.

Logger: custom_components.meross_lan
Source: custom_components/meross_lan/helpers.py:23
Integration: Meross LAN (documentation, issues)
First occurred: 08:30:16 (3 occurrences)
Last logged: 08:30:16

MerossDevice(2009223902001190831148e1e9344bb8) error in async_http_request: Server disconnected
MerossDevice(2009222728525590831148e1e9343614) error in async_http_request: Server disconnected
MerossDevice(2009221363906590831148e1e934418a) error in async_http_request: Server disconnected

Info re HA
System Health

version: core-2022.2.3
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.9.7
os_name: Linux
os_version: 5.10.96
arch: x86_64
timezone: Europe/London

GitHub API: ok
Github API Calls Remaining: 4719
Installed Version: 1.22.0
Stage: running
Available Repositories: 977
Downloaded Repositories: 24

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

host_os: Home Assistant OS 7.3
update_channel: stable
supervisor_version: supervisor-2022.01.1
docker_version: 20.10.9
disk_total: 30.8 GB
disk_used: 18.3 GB
healthy: true
supported: true
board: ova
supervisor_api: ok
version_api: ok
installed_addons: Samba share (9.5.1), Check Home Assistant configuration (3.9.0), SSH & Web Terminal (10.0.2), Home Assistant Google Drive Backup (0.105.2), Studio Code Server (4.1.0), MariaDB (2.4.0), InfluxDB (4.3.0), Grafana (7.4.1), Mosquitto broker (6.0.1)

dashboards: 3

resources: 16
views: 75
mode: storage

**Comment by krahabb** [comment]
It could be a device key issue then. 
Or something else... if you're up for a bit of tracing I suggest you to enable the tracing feature on any (or all) of the 'warning' entities ([instructions here](https://github.com/krahabb/meross_lan#troubleshooting)).
If we're lucky enough we could grab a trace (it only traces 10 minutes of traffic) while the error gets logged and try to understand maybe the reason.
If you grab an error please post the trace then

@krahabb

**Comment by thorrrr** [comment]
I am still getting errors logs periodically so i have turned on the trace feature :) 
This error originated from a custom integration.

Logger: custom_components.meross_lan
Source: custom_components/meross_lan/helpers.py:23
Integration: Meross LAN (documentation, issues)
First occurred: 08:11:54 (1 occurrences)
Last logged: 08:11:54

MerossDevice(2009222728525590831148e1e9343614) received signature error (incorrect key?)

**Comment by krahabb** [comment]
It could be the devices are configured with a wrong 'key'
If you left it empty when adding to HA integrations it might explain the random disconnects issue.

You can check this [post](https://github.com/krahabb/meross_lan/issues/167#issuecomment-1039162846) for an explanation on how to re-configure the correct key. At the moment the only way to recover the effective key for devices paired to the meross app is to delete/readd the integration configuration. Once done for a single device you can then manually copy over the key (it is the same for all of the same meross-account-paired devices) to the other devices.
There's a reference to the 'manual' way to recover the official key in this [post](https://github.com/krahabb/meross_lan/issues/167#issuecomment-1039400327) so you don't have to remove the device from HA

I hope you really left the key empty in meross_lan device configuration since it would explain the issue...else we're a bit lost!

**Comment by thorrrr** [comment]
All  3 items have the identical key  plus some other number on the hub which i don’t have
