### ISSUE TITLE
MSS310H energy entity appears as "Unavailable"

### ISSUE THREAD

**Issue by almico** [krahabb/meross_lan#17]
I just upgraded to the latest beta and this is what I see about my MSS310H:
![image](https://user-images.githubusercontent.com/15247405/115855783-f374d000-a42b-11eb-9fb7-fbce97442a80.png)

Basically, the entity `sensor.meross_lan_2009224801331190830948e1e9342911_energy` is now unavailable. Might this be a breaking change and it was replaced by `sensor.meross_lan_2009224801331190830948e1e9342911_power`?

**Comment by krahabb** [comment]
Hello @almico !
I've double checked with mine and it all works fine. With the last release no relevant changes were made to 'switches' but, of course, something bad could always happen with software releases so again I don't see any disconnect or unavailability on any sensor in my MSS310

What comes to mind here is the firmware version of the plug: it is more recent than mine so there's maybe a different approach in protocol handling for the energy reading.
Keep in mind (power, current, voltage) are read together in a message while (energy) is read in another one so it is no surprise that the former work while the latter (energy) does not.

It would be nice to have some debug log. You can enable detailed logging for meross_lan by following this https://www.home-assistant.io/integrations/logger/
Basically just add
```
logger:
  default: info
  logs:
    custom_components.meross_lan: debug
```

to your configuration.yaml

This of course could impact a bit your logging file so you want to maybe enable it for a while, use the plug a bit and then disable logging again. Keep in mind the energy reading normally happens every 1 minute so it is ok to log about 4-5 minutes of data while you use the plug
This is painful since you have to restart HA 2 times so I see if you would pass on that.
At any rate, I'm going to integrate an easier debug facility into the component in order to make it feasible to dump logs 'on the fly' when there's something odd and let you (as user) grab and send these logs with a few clicks in the UI without reconfiguring, restarting and digging into command lines or so. This is not happening soon sadly

**Comment by krahabb** [comment]
Btw,
It happens, at the start or when the plug comes back online, that the component looks connected except the energy sensor (or even the other entity readings):
this is known and 'normal' since I don't read the energy rightaway but the code just waits for the next polling loop to send the energy request end it behaves like that: the energy comes online a bit lazy like 30 seconds 1 minute later

**Comment by krahabb** [comment]
Stale
