### ISSUE TITLE
error in async_http_request: invalid literal for int() with base 10: 'pkubtyzzgoqtgzse'

### ISSUE THREAD

**Issue by jarodwilson** [krahabb/meross_lan#173]
## Version of the custom_component

v2.5.4

## Configuration

```yaml

2022-02-22 00:39:52 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(2104155069457390849748e1e96c4944) error in async_http_request: Server disconnected
2022-02-22 00:40:21 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(2104155069457390849748e1e96c4944) error in async_http_request: invalid literal for int() with base 10: 'pkubtyzzgoqtgzse'

```

## Describe the bug
Every time I restart Home Assistant, I see this in my logs. Doesn't seem to actually negatively impact anything, but it's always with my msl320cpr light strip.

## Debug log

```text
Can acquire if needed, but this fix might be obvious from just the warnings above.

```

**Comment by krahabb** [comment]
Hello @jarodwilson ,
Thank you for pointing out. The parsing exception was easily retrieved by the log you provided but there' s something I didn't expect. In a trace I have (from a friend's msl320) the effect id (which I suspect is the 'offending' field for your device) is used to set the effect from HA/meross_lan and that field carries an int value (that's why meross_lan optimistically tries to cast it to an int.
I would then need a trace to better figure out what's going on. 
In order to grab enough info you should try and switch different effects with the meross app while recording the trace so I can inspect what happens effectively with the different data payloads.

Thank you!

**Comment by jarodwilson** [comment]
(Apologies, been meaning to get that log dump, just been a bit busy, but it looks like it's probably no longer needed. Will give the update a spin to verify.)
