### ISSUE TITLE
Add support for MSG200, MLS610, MSS620

### ISSUE THREAD

**Issue by danielsza** [krahabb/meross_lan#185]
When trying to setup the integration, I can retrieve the key, but I keep getting stuck in a loop asking to login. I assume it’s because none of the meross devices I own are currently supported.

hopefully support can be added for  MSG200, garage door opener 
 MLS610, desk lamp
MSS620, outdoor smart plug

**Comment by krahabb** [comment]
Hello @danielsza,
The devices, even when not supported, should pass the configuration phase since feature identification is done later in code.
If anything is wrong with feature/device recognition this should result in 'incomplete' devices i.e. no entities or misbehaving ones, but the configuration phase would pass anyway since it only checks for basic protocol handling.

The 'loop' is either because the key is wrong or because of a bug in meross_lan config flow handling.

This is what should happen supposing your device is already paired with Meross app and HA prompted you after discovery:
- initial configuration panel reports:
key mode: cloud retrieve
device key: empty
- when you hit SUBMIT it shows you the cloud login form. After entering valid credentials this form closes and reports back to the main config form with the 'device key' filled with your secret key
- when you SUBMIT again, meross_lan checks the key is really correct for the actual device and, if it fails, it brings you to the cloud login form again

So, if you see the 'cloud retrieved key' in place and still you get to the cloud login form, I guess the device is either unpaired or paired to a different meross account.
Could be it ?

To check if the key is correct and avoid the cloud login form you can select 'key mode' = 'user set'. This way no cloud login form or check would happen but the device key you provide must be correct else you'd be stuck again.

If the device is still unpaired you could try set the 'device key' to empty and 'key mode' to 'Hack mode' and see if it pass the configuration phase but this way, even if configuration could pass, the device behaviour would be rather unpredictable (maybe working for some time maybe not at all, random unavailability..and so on)

**Comment by danielsza** [comment]
I double checked the login info, it looks like at some point I had a typo in my email address, and my password manager had both saved. 

I was trying to use the incorrect login. Since it did return a key I assumed it was the correct login.

I was able to add all 3 of my devices, and they do seem to correctly add the devices.

**Comment by krahabb** [comment]
It is possible that the meross api doesnt report an error when login informations are wrong or (most likely) that you just retrieved informations from a different login than intended

Good this was 'not' an issue ;)
