### ISSUE TITLE
"Key Selection mode" keeps going back to "Cloud retrieve"  ?

### ISSUE THREAD

**Issue by MasterCATZ** [krahabb/meross_lan#188]
Thanks for creating this , it does seem to be working ,
 at least better than having meross GUI asked them for years now to give us an hourly chart instead of a daily
 wish I knew of this sooner

however when I select 
"Hack mode" or "User set" 
it just goes back to 
"Cloud retrieve" 
and for the hell of me I do not even know how that is working as I never gave it my login details ?

**Comment by krahabb** [comment]
Hello @MasterCATZ ,

The behaviour of that setting is 'dynamic' i.e. it is not set in configuration itself:
The UI always tries to 'force' you through a cloud retrieve procedure (this is because the vast majority of users are still using their devices with the Meross cloud - my guess) whenever the actual key is not working.

meross_lan, nevertheless, tries to use the actual key before going to the cloud retrieve mask and, if it works, it assumes no need for cloud retrieve and shouldn't ask you for any.
so in the end, even if your key is not actually 'cloud retrieved', the configuration UI 'guesses' it would be better to go through cloud retrieve should the actual key not work.

This is because at the time, when implementing this flow, there was a big 'issue' with wrong or unset keys for many of the meross_lan users with originally cloud configured devices.

There's now a new UI pattern available in HA which could allow putting menu choices in the configuration flow and better fit this use case. I'll have a look and maybe refine the configuration UI with a better behaviour

**Comment by MasterCATZ** [comment]
all good thanks anyhow 

currently my main issue is working out a way for graphana to grab raw data and not the aggregation mean

if the data connection is lost it just keeps doing average data even tho I know full well the meross has no power connection and completely offline

**Comment by Vincenzo-8** [comment]
Hello @krahabb,
I think I have the same problem. Before the last meross update this socket (mss310x firmware 2.1.2) worked very well but not anymore. I removed the integration and am trying to re-add it but it sends me back to "Cloud Retrive" which itself doesn't work. I hope I was clear why I am not well versed
<img width="569" alt="Schermata 2022-04-25 alle 13 14 29" src="https://user-images.githubusercontent.com/68118955/165078912-6066c766-68a5-4082-a570-bd8eb6671681.png">
.

**Comment by krahabb** [comment]
Hello @Vincenzo-8,
If your device is still paired to Meross (which seems to be the case since you've just updated the firmware) you have to configure the exact device key (the 'empty' key was a trick and likely not working anymore when you update to the latest firmwares)

You have to select 'Cloud retrieve' and provide your meross credentials on the next form so meross_lan would be able to download the exact device key from your meross account informations.
After the login form retrieves your credentials (with no error on cloud login) you should be back to the configuration form with the key field populated by the retrieved key (something like '11cc4533a7e2336e29ce7e6afa422bce') : now, hitting submit should pass the validation and configure the device.
If not, it means the device has a different key than the one you recovered: maybe you're using different meross accounts?

If the cloud login form doesn't work than it's another story but I've just checked and it looks like it is working on my meross_lan configuration

**Comment by sonnicolo83** [comment]
Hello,
I have the same problem reported from Vincenzo.
Meross account is correct but once the key is retrieved via the form, I press submit and the home assistant form returns to the login form again ...

**Comment by krahabb** [comment]
Hello @sonnicolo83 ,
When you retrieve the key through the cloud login form you should be sent back to the main configuration form with the proper cloud key set in the key field. If the key field is still empty or contains an invalid key when you come back from the cloud login form then the process will restart with the cloud login.
In order to be 'sure' the key you see in the configuration form is the original cloud retrieved key, try to delete any value in the key field and proceed. Now, you'll get the cloud login and after that, if everything is fine, you'll see the retrieved key (a sequence of random chars).
As previously said, hitting submit now should validate this key and, if you still get to th ecloud login form then the key is wrong (as to shy the retrieved key should be wrong I can't really tell..)

There are some issues with the cloud login flow which are being fixed in the incoming release (#186) and maybe are related to the same issue you're experiencing. I have found a couple of bugs and fixed hoping this will improve the overall process
