### ISSUE TITLE
Meross MSL320CP

### ISSUE THREAD

**Issue by GeorgeCaliment** [krahabb/meross_lan#189]
Hello, after long time I come back here with a problem with meross devices, this time with the led strip rgb ww MSL320CP, the MSL320c, the only rgb one is working like a charm. The first problem is that i can't connect device to my local mqtt broker, i guess they locked in some way the 10.10.10.1 gateway, trying to connect to it returns error "Unable to connect to device", the cause I'm pretty sure is the firmware version the 6.x.x (other devices and rgb strip has 4.x.x firmware). Tried to find some other way, but i guess there isn't. I gave up on this solution for the moment, i went with http, the device works nice, rgb, whites and dimmer, the problem is that after some seconds in idle device goes offline, so i have to reboot entity to be available again. I found a workaround using an automation that triggers everytime the entity goes offline, but i wonder if is some better solution.

Here's the trace.
[msl320cp-1651248869.csv](https://github.com/krahabb/meross_lan/files/8592509/msl320cp-1651248869.csv)

**Comment by krahabb** [comment]
Hello @GeorgeCaliment ,
I'm guessing you're still on an 'old' meross_lan version since the trace log reports some old conflicts/messages which were fixed and refined later on. 
I don't think the issue would be fixed anyway with latest meross_lan release but I suggest you to update (if I got it right!) to the latest stable release (Dare.1 or 2.5.7)

Since your device is paired to your meross account you should also set the device key in meross_lan configuration. If you left it empty that could explain the disconnections. It seems to me that latest firmwares from meross became more strict on protocol key hacking (the one used by meross_lan when the device key is left empty). Moreover it looks like they don't replay with any error messoge: they just drop the connection when the key is wrong or they detects a 'key reply hack'

**Comment by GeorgeCaliment** [comment]
Hi,
tried the 2.5.7 and yes indeed the led strip with the newest firmware works fine, but with this meross-lan version seems that my old devices with 4.x.x firmware over my local mqtt broker doesn't work anymore, just over http.

**Comment by krahabb** [comment]
That shouldnt happen!
I'm using that version with my mqtt paired devices and they work fine. Do you have any meross_lan log message in HA log to share ? Have you tried to fix the protocol behaviour in meross_lan configuration? keep in mind that when set to auto, meross_lan will switch automatically between MQTT and HTTP depending on 'transient' issues but should automatically choose the 'best' transport in every situation (it's a bit complicated since the algorithm chooses the 'best' transport based on my personal assumptions and the way the device was added/discovered)
Also, meross_lan could be in 'HTTP mode' while still being able to listen to 'MQTT' messages so you're still having almost instant updates from switches and so

**Comment by GeorgeCaliment** [comment]
Hi @krahabb, sorry for the late answer, i had to test with old switches too. So, in order, for the led strip with firmware 6.x.x+ with disconnection the problem was the device key indeed, once set that worked. For the strip with 4.x.x strip seems that with bytespider utility to connect to my mqtt broker, the device doesn't even try connect, while with firmware 3.x.x seems to work fine. Do u know a way to connect also 4.x.x firmware to my mqtt broker, I don't really like the http status fetch delay. I tried much eveything and really don't know why device don't try to connect (from broker registry is not logged anything from device) but it connects correctly to my network.

**Comment by krahabb** [comment]
Hello @GeorgeCaliment,
I can't really figure out where the issue could lie since the process of MQTT pairing should really be straightforward and I don't see any reason they woul fail on later firmwares...but I really don't have any recent experience with all the pairing procedure so I really can't tell.
I suggest you to try [the 'pairer app'](https://github.com/albertogeniola/Custom-Meross-Pairer). Same as @bytespider utils but more friendly in some way

**Comment by GeorgeCaliment** [comment]
I tried the pairer app, but i have some issues, device won't connect to broker. I created an user with mac and md5(mac) as username and password. Works fine using this https://github.com/bytespider/Meross, but not the app.On the app i just logged in with my meross account, do i need some more configs on app or missed something?
My mosquitto config is this:  
`logins: []
require_certificate: false
certfile: server.crt
keyfile: server.key
customize:
  active: true
  folder: mosquitto
anonymous: true
cafile: ca.crt `
