### ISSUE TITLE
Add support for Meross valves

### ISSUE THREAD

**Issue by Ameglialuna** [krahabb/meross_lan#19]
Have you any plan to add support for Meross valves (MTS100 valves with MTS100H Hub)?
Thanks!

**Comment by krahabb** [comment]
Hello @Ameglialuna 
I definitely would like to add support for the valves (and any other Meross device) but I don't own any at the moment.
I'm waiting to see how much interested the 'community' is around the different devices in order to prioritize development (and device spending!)

I can try setup an experimental support based on knwoledge from Meross Iot library and other sources and guess an implementation (I did this for lights and it did not work tho...I had to buy bulbs in the end ;)

Anyway the response is yes: sooner as far as more people are interested

Thank you for starting this!

**Comment by Ameglialuna** [comment]
Thanks to you for your work!

**Comment by Ameglialuna** [comment]
And please let me know if I can be useful for some kind of testing

**Comment by krahabb** [comment]
Hello @Ameglialuna,
Support for thermostats (I've tested mts100v3) is online! Let me know if it works and fits your use case.
I'll wait for comments (no rush!) before closing this down in few days

**Comment by Ameglialuna** [comment]
Thanks, @krahabb  I'll test immediately! Thanks again

**Comment by Ameglialuna** [comment]
From a first quick test it seems that the hub and valves are working perfectly.
I didn't find any issue until now, you did an amazing job!
