### ISSUE TITLE
Integration stopped working and it is impossible to reinstall

### ISSUE THREAD

**Issue by marcobuzzanca** [krahabb/meross_lan#209]
Hi, 
I was using Meross Lan integration for  several months until yesterday. All the devices (Meross 310 smart plug) were disconnected and also restarting the devices or Home assistant nothing changed. So i decided to remove the integration and install it again.  First of all i deleted all the device and then i removed the integration from HACS. Downloaded again the latest version when i try to install i have this error message: _Impossibile caricare il flusso di configurazione: [object Object]_
Meross lav V2.6.1
Hasssio working on a VM on Win10 PC
              Tipo di installazione | Home Assistant OS
              Sviluppo | false
              Supervisore | true
              Docker | true
              Utente | root
              Ambiente virtuale | false
              Versione Python | 3.9.7
              Famiglia del sistema operativo | Linux
              Versione del sistema operativo | 5.10.88
              Architettura della CPU | x86_64
              Sistema operativo dell'host | Home Assistant OS 7.1
              Canale di aggiornamento | stable
              Versione supervisore | supervisor-2022.08.3
              Versione Docker | 20.10.9
              Disco totale | 28.8 GB
              Disco utilizzato | 14.1 GB

Can you help me?

**Comment by krahabb** [comment]
Hello @marcobuzzanca ,
This is very hard to decode.
Do you see the error when installing ? (i.e. is it related to HACS failing in some way)
or do you see it when the integration is loaded? or configured ?

Basically, if you've just removed all of the configuration entries for meross_lan from the 'Integrations' page, you should not see any error related to meross_lan until you start configuring a new integration entry for that.
If you see the error while 'installing' meross_lan from HACS then it is liely an issue with HACS itself

A partial HA log would be nice in order to better understand where the 'Impossibile caricare il flusso di configurazione: [object Object]' comes from.
