### ISSUE TITLE
Report consumption through sensors - mss426

### ISSUE THREAD

**Issue by Swaeltjie** [krahabb/meross_lan#212]
**Is your feature request related to a problem? Please describe.**
There is currently no power consumption being reported for model mss426. Only to toggle each channel on/off. 

**Describe the solution you'd like**
To be able to have power consumption reported per channel and, if possible, USB as well. 

**Describe alternatives you've considered**
Buying something other than Meross smart plugs. 

**Additional context**
Currently, only the following information is being retrieved:

(Trace Log)

2022/09/12 - 18:06:35		auto	GETACK	Appliance.System.All	{"system": {"hardware": {"type": "mss426", "subType": "uk", "version": "4.0.0", "chipType": "MT7686", "uuid": "################################", "macAddress": "#################"}, "firmware": {"version": "4.1.1", "homekitVersion": "2.0.1", "compileTime": "Sep  8 2020 13:45:19", "wifiMac": "#################", "innerIp": "#############", "server": "####################", "port": "###", "userId": "#######"}, "time": {"timestamp": 1663002395, "timezone": "Europe/London", "timeRule": [[1648342800, 3600, 1], [1667091600, 0, 0], [1679792400, 3600, 1], [1698541200, 0, 0], [1711846800, 3600, 1], [1729990800, 0, 0], [1743296400, 3600, 1], [1761440400, 0, 0], [1774746000, 3600, 1], [1792890000, 0, 0], [1806195600, 3600, 1], [1824944400, 0, 0], [1837645200, 3600, 1], [1856394000, 0, 0], [1869094800, 3600, 1], [1887843600, 0, 0], [1901149200, 3600, 1], [1919293200, 0, 0], [1932598800, 3600, 1], [1950742800, 0, 0]]}, "online": {"status": 1, "bindId": "Iu65RgFHg4F9hRz5", "who": 1}}, "digest": {"togglex": [{"channel": 0, "onoff": 1, "lmTime": 1662807085}, {"channel": 1, "onoff": 1, "lmTime": 1662807085}, {"channel": 2, "onoff": 1, "lmTime": 1662807085}, {"channel": 3, "onoff": 1, "lmTime": 1662807085}, {"channel": 4, "onoff": 1, "lmTime": 1662807085}, {"channel": 5, "onoff": 1, "lmTime": 1662807085}, {"channel": 6, "onoff": 1, "lmTime": 1662807085}, {"channel": 7, "onoff": 1, "lmTime": 1662807085}], "triggerx": [], "timerx": []}}

**Comment by krahabb** [comment]
Hello @Swaeltjie ,
By the look of it, the mss426 doesn't report power consumption by itself (no hardware support in the dveice for power readings) so there's no option to add it in meross_lan. Also, other devices reporting consumption, generally do so for the whole device even if it carries multiple ports/sockets) but I may lack knowledge of newer ones of course.
You can confirm there's no power reding available by checking if the official app supports it for the device: if not it means I'm correct stating the device doesn't offer power readings.

If instead you can read power consumption on the app I would then need a full trace log in order to reverse engineer the protocol and try guessing where meross_lan is failing
