### ISSUE TITLE
Full dimmer support (MSS560, MSS570)

### ISSUE THREAD

**Issue by simbo1984** [krahabb/meross_lan#218]
Congrats for the integration, it is truly awesome! I'm having a bit of a problem with the dimmers though...It looks like two messages are sent when I turn on the device which results in a quick flicker (as if the switch was turned on, quickly turned off and on again).

It would be awesome to be able to benefit from full support of dimmers (MSS560, MSS570 and the likes). 😎

I did a quick debug tracing to understand what was happening :

`2022/10/07 - 18:07:31	RX	http	GETACK	Appliance.System.All	{"all": {"system": {"hardware": {"type": "mss570x", "subType": "us", "version": "3.0.0", "chipType": "mt7682", "uuid": "################################", "macAddress": "#################"}, "firmware": {"version": "3.2.1", "compileTime": "2021/09/30 08:14:53 GMT +08:00", "encrypt": 1, "wifiMac": "#################", "innerIp": "############", "server": "##################", "port": "###", "userId": "#######"}, "time": {"timestamp": 1665180450, "timezone": "America/Toronto", "timeRule": [[1647154800, -14400, 1], [1667714400, -18000, 0], [1678604400, -14400, 1], [1699164000, -18000, 0], [1710054000, -14400, 1], [1730613600, -18000, 0], [1741503600, -14400, 1], [1762063200, -18000, 0], [1772953200, -14400, 1], [1793512800, -18000, 0], [1805007600, -14400, 1], [1825567200, -18000, 0], [1836457200, -14400, 1], [1857016800, -18000, 0], [1867906800, -14400, 1], [1888466400, -18000, 0], [1899356400, -14400, 1], [1919916000, -18000, 0], [1930806000, -14400, 1], [1951365600, -18000, 0]]}, "online": {"status": 1}}, "digest": {"togglex": [{"channel": 0, "onoff": 0, "lmTime": 1665173130}], "triggerx": [], "timerx": [], "light": {"capacity": 4, "channel": 0, "luminance": 25}}}}`
`2022/10/07 - 18:07:31	TX	http	GET	Appliance.System.DNDMode	{"DNDMode": {}}`
`2022/10/07 - 18:07:31	TX	http	SET	Appliance.Control.ToggleX	{"togglex": {"channel": 0, "onoff": 1}}`
`2022/10/07 - 18:07:31	TX	http	SET	Appliance.Control.Light	{"light": {"capacity": 4, "channel": 0, "luminance": 25}}`
`2022/10/07 - 18:07:31	RX	http	GETACK	Appliance.System.DNDMode	{"DNDMode": {"mode": 0}}`
`2022/10/07 - 18:07:31	RX	http	SETACK	Appliance.Control.ToggleX	{}`
`2022/10/07 - 18:07:31	RX	http	SETACK	Appliance.Control.Light	{}`

It looks like ToggleX namespace is for the ON/OFF trigger and the Light one is for the dim (or luminance in that case).

I will probably take a look at your code meanwhile.

Thanks 🙂

**Comment by krahabb** [comment]
Hello @simbo1984,
The dimmer are effectively recognized as 'bulbs' (like msl120) in meross_lan since they're showing the same capabilities (by the look of it!)
The flicker is likely due to my code sending both 'ToggleX' and 'Light' messages when initially turning on the device. This is of course due to how the legacy bulbs were working (and tested).

Also, being the mss570 a 3 way switch, that could introduce some unexpected (unknown) behaviour since the physical switch is actually a deviator and not a simple on/off even though it still has 2 physical positions in the end.
It would be nice to see how the device processes single commands like 'ToggleX' and/or 'Light' in order to better undrstand its behaviour.

By looking at the code you should be able to easily disable the ToggleX sent on turning on and see if that completely fixes the issue.
Also, you could use the HA UI to directly send some manually crafted payloads/commands by using the 'Services' UI in 'Developer Tools'. There look for 'some meross_lan service call' and it should be pretty straightforward.
You could try send this kind of payload '{"togglex": {"channel": 0, "onoff": 1}}' with the 'Appliance.Control.ToggleX' namespace.

What I can't figure out right now is:
do the "onoff" field in this payload work to actually turn on the light and so behaves like a logical 'on' in every situation? I mean: when the other 3-way switch on the electrical line is toggled so reversing the logic of the circuit, does the "1" always turn on the light or is it reversed? and you need a "0" to turn it on?

**Comment by simbo1984** [comment]
Hi @krahabb!

Thanks for your quick response! 🙂

I tested using the Service in Developer Tools by sending the recommended payload (using ToggleX namespace) and it's working as expected (no flicker). Regarding your question : the fact that the switch is 3-way doesn't seem to have any impact at all (they act like single-pole switches as far as I can tell - I have one 3-way that is not a dimmer and I didn't have any problems so far). The payload sent does not reverse the state of the switch meaning if I send "onoff=1" it turns on but doesn't turn off if its state is already on (or 1).

I did additional tests because I was curious of how it was acting but it seems that the Light namespace is a better integration as you can adjust the dim when turning it on. When sending this payload : `{"light": {"capacity": 4, "channel": 0, "luminance": 25}}`, the light is turned on with a 25% dim. When I send this one : `{"light": {"capacity": 4, "channel": 0, "luminance": 0}}`, the light is turned off. This is really neat! 👍🏻 

Let me know if you need me to run some other tests but all in all, I think this just need some minor adjustment!

**Comment by krahabb** [comment]
Yeah, thank you for your deep testing!

Now, in order to accomodate the usage of the light payload without sending the 'flickering' togglex I need to know how to disambiguate this behaviour from the standard meross bulbs.

Actual meross_lan implementation uses the exposed status from the device in order to decide which api to use. The status is the one queried through the Appliance.System.All namespace and when this payload exposes a 'togglex' structure I use this as a signal it would be better to use the ToggleX command in order to initially turn on the light. Other messages to change the luminance or any light parameter will then just publish 'light' commands since the device keeps its state as 'on' anyway. 

Nevertheless, in my experience, various lights don't need the ToggleX payload in order to be turned on but they just turn on when receiving the 'light' command alone, this is like yours.

Now, I guess it would be better to add a simple heuristic in order to identify the device model and act accordingly (drop the ToggleX command flow). I'm scared all of this logic doesn't really depend on the device but rather on the firmware level but we can't afford to do extensive testing so I'll just go with this very 'local patch' in order to fix this behaviour and see whats next :)

Thank you
