### ISSUE TITLE
Wrong power cosumption

### ISSUE THREAD

**Issue by PrastoDj** [krahabb/meross_lan#221]
Hi,
using Meross MSS310H there is a issue with the power consumption: the value is reset every night at 00:00, most probably because the value read is the daily, not the total, like:

![image](https://user-images.githubusercontent.com/75693328/200135502-b8ef11ed-200d-4e25-9352-f5ab71533a03.png)

Can you resolve please?

Thanks

Mirko

**Comment by krahabb** [comment]
Hello @PrastoDj,
This is how the device itself reports power usage internally: every day it resets its counter and provides the daily consumption so meross_lan doesn't really add or remove anything to the device data.
In order to 'accumulate' your power usage readings over days, weeks or months, you'd better use the official 'Energy' features of HA.

You can do so by entering the 'Energy' dashboard (Settings -> Dashboard) and add the device (daily) consumption entity into the 'Individual devices' list. This will add more powerful reporting statistics well integrated with the HA power reporting features.

Also, beside that, you can use 'statistics' or 'Long term statistics' (another feature of HA UI) to report the 'sum' of the daily readings in your customized dashboards

**Comment by PrastoDj** [comment]
> Hello @PrastoDj, This is how the device itself reports power usage internally: every day it resets its counter and provides the daily consumption so meross_lan doesn't really add or remove anything to the device data. In order to 'accumulate' your power usage readings over days, weeks or months, you'd better use the official 'Energy' features of HA.
> 
> You can do so by entering the 'Energy' dashboard (Settings -> Dashboard) and add the device (daily) consumption entity into the 'Individual devices' list. This will add more powerful reporting statistics well integrated with the HA power reporting features.
> 
> Also, beside that, you can use 'statistics' or 'Long term statistics' (another feature of HA UI) to report the 'sum' of the daily readings in your customized dashboards

Hi krahabb, I know that meross_lan doesn't reset any value, infact the value is reset by meross cloud/device. The issue is caused by the wrong read value, because meross_lan reads the daily_value instead of the total_value (also avaiable in meross app).

Thank you for the suggestion about energy dashboard, I didn't know that it can collect and sum data also for values reset every day. This could be a nice workaroun, but I hope this issue could be fixed in the future
