### ISSUE TITLE
Issue with cover and other handy sugestion

### ISSUE THREAD

**Issue by pedrompamaral** [krahabb/meross_lan#23]
Great Job! Several switches are already working "offline".

MRS100 cover switch is recognized, but shows as unavailable, and don´t let send any command.

Also would be very useful to add an entity to all switches to let us turn the presence LED light on and off.

**Comment by krahabb** [comment]
Thank you @pedrompamaral,
I'll try to review the code for MRS100. In the meantime if you can attach some logs (by enabling the debug level for meross_lan in HA - warning: it is very verbose so don't leave it on!) that could be helpful

What do you mean by presence LED ? is it the MSS510 switch one? If the device has the ability to control it I would need some response payloads from it: I'll instruct you how to do that if you wish but basically I would need the responses for 'Appliance.System.All' and 'Appliance.System.Ability' from the device in order to guess which command to use in order to control it

P.S. if you enable debug logging in HA you'd need to restart it and you could see also some relevant MSS510 messages during boot/initialization

Thank you for signaling this anyway!

**Comment by pedrompamaral** [comment]
Hello @krahabb 

Sorry, but i'm still a bit noob on this. How do i degug meross_lan to give you the information you need?

What i mean by the presence LED is the green light that all the meross switches have (watch 3º attached image), In the Meross app, those LED's can be turned off. It would be great if they can be controlled in HA.

Updating some information... The MRS100 smart roller switches already work in HA by http method, but still not at 100%. At this moment, they are working like they where a garage door opener. They only open or close fully. The HA can´t recognize when the shutter is midway (for example, if it's a 20% or 50%). In the HA i have a "0%-100%" bar, but it only open fully, or close fully (according to the seconds i have programmed in the Meross app), it don't respect the percentage shown on HA. It would be nice if i can set in HA the full cycle time, and then i can control if i want to open 20%, or 50%, or whatever. The way it is, is perfect for a garage opener, but still not perfect for the shutters. When i send the command to open or close, the shutters still respect the time i have programed in the Meross app.

Thanks a lot for your work tho. You're a genius. =)



![Print 1](https://user-images.githubusercontent.com/80420452/124164519-aa2ea580-da98-11eb-9e5a-7e2d066bbc9c.jpg)
![Print 2](https://user-images.githubusercontent.com/80420452/124164539-ae5ac300-da98-11eb-9637-6dff1ae02e3c.jpg)
![ImgW ashx](https://user-images.githubusercontent.com/80420452/124164543-b0bd1d00-da98-11eb-8230-385c39b9786a.jpg)

**Comment by krahabb** [comment]
Hello @pedrompamaral ,
I've currently refined support for the MSG100 (GarageDoor) and planning to 'port' what I've discovered so far to the roller shutter including complete support for position.

Please wait for the next release since I'm adding a feature to ease data gathering for unknown or problematic devices without the need to restart HA or polluting the HA log

Thank you for your effort!

**Comment by krahabb** [comment]
Hello @pedrompamaral ,
I've published 'Rebirth.2' with no real update to the 'Shutter' code but with a nice feature to gather traces/logs from your devices without the need to mess with HA debug log options and stuff.
Just enter the single device config UI (in your 'Integrations' panel) and enable the 'Activate device debug tracing (for 10 min)' check.

This will start dumping the device discovery informations and all of the protocol exchanges happening for a limited timeframe (10 minutes - hardcoded) starting when you confirm the configuration. There's also a maximum file size (64K) limit after which the trace gets stopped.

You will then find the tracefiles under the directory 'custom_components/meross_lan/traces'.

During the trace please action your devices both from HA and from the Meross App (if still paired with the cloud) and send me a little sequence (together with the traces) describing your actions like:
- Turning on the switch led
- Turning off the switch led
- Opening the shutter
- and so on...

set the polling period for both the shutter and the MSS5XX in the 10 seconds area so to have a nice sampling rate.

WARNING: the traces will contain some 'private' informations like mac addresses and ip(s) which usually are not very relevant but that's it. Also, more important, if the devices are still paired with the official app, these traces will contain the 'userId' associated with your Meross account and set into the device. I'm not planning to use it of course (and I don't have any idea how that could be exploited) but you can eventually look for it into the plain text file(s) and hide the real number. It usually only appears at the beginning of the trace where I dump the discovery informations but could happen (rarely) even then if the device jumps offline/online.
I'm sorry for this but I was rushing to release this and I couldn't find an easy/fast way to obfuscate sensible data from the payloads

I hope you can easily set this up and that everything is working as intended. As soon as you can send me the traces I'll start reviewing the MSRXXX

Thank you!

**Comment by pedrompamaral** [comment]
@krahabb 
Thanks for all the information. I will try to do what you asked and get back to you as soon as i get the information you need.
Also thanks for all your work.

**Comment by pedrompamaral** [comment]
@krahabb 
I think i've done it. Can i attach a notepad file with all the info, or you prefer other pethod?
This way i can delete the personal information easier.

Tell me what you think.

**Comment by krahabb** [comment]
@pedrompamaral 
That's ok, if you remove your personal info and post the file here would be awesome!
Thank you

**Comment by pedrompamaral** [comment]
@krahabb 

I don't know if it's helpful, but i created another notepad file where i made the list of commands/actions i gave to the switch in the order that it should appear on the debug tracing. I never let the shutter open or close fully, to use the "stop" command. I used the app, the hardware touch, the HA commands i have now (open, close and stop), and the turn on and off of the LED presence lights of the switch. I don't remember any more action i can use.

In the debug trace file i used the " * " symbol to replace the personal information. That way it keep the original format appearance. 

I hope this can help you. If you need me to make more tests with this debug tracing, just let me know.

Thanks a lot.

[Test list.txt](https://github.com/krahabb/meross_lan/files/6766119/Test.list.txt)
[Commands  mrs100 shutter switch.txt](https://github.com/krahabb/meross_lan/files/6766120/Commands.mrs100.shutter.switch.txt)

**Comment by krahabb** [comment]
Hello @pedrompamaral !
Thank you for quickly posting. I'm a bit overwhelmed trying to fix this and that so this is taking a bit longer...
Anyway, I would also need the same trace for the mss510 since the one you posted is about the RollerShutter alone (every device record it's own trace)
Please, restart the tracing just for the mss510 and use it in order to turn on/off the status light while the trace is running
The rollershutter itself should be enough with what you sent me :)

**Comment by pedrompamaral** [comment]
Hello @krahabb 
I attached the debug trace and the command list for the mss510h, just like before. Let me know if everything is ok, and if you need me for some more information.

I will install the latest version of the meross lan and test it for the mrs100 (shutter switch). If it's working fine, i will update the information on the other post i did (confirmed supported devices).

Thanks


[MSS510H command list.txt](https://github.com/krahabb/meross_lan/files/6778818/MSS510H.command.list.txt)
[MSS510H Debug Trace.txt](https://github.com/krahabb/meross_lan/files/6778820/MSS510H.Debug.Trace.txt)

**Comment by krahabb** [comment]
Thank you,
I've found the feature allowing to turn off the status light.
Coming in the next release!
Thank you
