### ISSUE TITLE
Device key

### ISSUE THREAD

**Issue by rjnca** [krahabb/meross_lan#235]
I got the Meross LAN integration installed, but when I try to configure it, I just get a pop-up window that asks for a device key.  Any idea where I can find this?

![SCR-20221220-fai](https://user-images.githubusercontent.com/19576143/208745483-1c798879-c0d5-40e0-8366-a9d58b6e361b.png)

**Comment by krahabb** [comment]
Hello @rjnca,
This configuration is needed for the MQTT integration to be able to automatically discover devices.
Every Meross device in-fact, uses a secret key to communicate so this is needed overall to setup your devices.
If you don't use MQTT (this involves disconnecting meross devices from their cloud service and re-bind them to your private MQTT broker) you still need a device key and this key can be configured directly in every device you setup.
Long story short, if you don't use MQTT, this entry must be left 'as is' (meross_lan needs it anyway as the first entry configured) and you can add another meross_lan configuration by adding the integration again, once per device that is.

There, you'll need the ip address (unless the device gets automatically discovered by DHCP on your LAN) and the device key but you will be able to recover the key by logging into your meross account (meross_lan will ask you for credentials right for the purpose)

**Comment by rjnca** [comment]
Thanks for the information

**Comment by Phibins** [comment]
> Hello @rjnca, This configuration is needed for the MQTT integration to be able to automatically discover devices. Every Meross device in-fact, uses a secret key to communicate so this is needed overall to setup your devices. If you don't use MQTT (this involves disconnecting meross devices from their cloud service and re-bind them to your private MQTT broker) you still need a device key and this key can be configured directly in every device you setup. Long story short, if you don't use MQTT, this entry must be left 'as is' (meross_lan needs it anyway as the first entry configured) and you can add another meross_lan configuration by adding the integration again, once per device that is.
> 
> There, you'll need the ip address (unless the device gets automatically discovered by DHCP on your LAN) and the device key but you will be able to recover the key by logging into your meross account (meross_lan will ask you for credentials right for the purpose)

Hi @krahabb

I have been scoring the questions in order to get this set up, but keep failing.

I understand from your answer here that I need to leave the device key BLANK/EMPTY. (I am NOT using MQTT).

My device (MSG100) is not found after several restarts in the last week - I can see the device on my router, I even gave it a static IP.

I am lost on what to do next. If I misunderstood, and in fact DO need the device key - I am at my wit's end trying to retrieve it.  The MEROSS LAN was added through HACS - I am using HA-OS.

**Comment by krahabb** [comment]
Hello @Phibins,
I'm sorry for the issue here, the Meross LAN Hub entry must be configured first even if you're not using it and, as stated above you can leave the key empty and forget about the entry configuration.
Once configured (empty that is), start over again adding meross_lan integration another time. At this point you will be provided the 'real' device configuration form where you can set the address and device key. 
The pairer app is already providing you the device key (it's the 'MQTT Key' but it is used also for HTTP communication) but in meross_lan too there's an option to retrieve the 'real' device key from your Meross cloud account, nevertheless, the pairer app should be good at providing the correct one anyway ;)

Still, it is very strange the device is not automatically discovered. If not, I suggest you to install the 'Lazy.alpha.0' pre-release which has some tweaks both on DHCP discovery and MQTT configuration. In order to do so, you might have to instruct HACS to show you pre-release versions of the repo in order to see that

**Comment by Phibins** [comment]
Thank you Krahabb for your quicks response. Thanks to you - I managed to add all my devices into home assistant (after a lot of struggle and head scratching). 

I think the read me is great - but I am not so smart it appears, and I would like to suggest some edits to the READ ME so as to accomadate the not so smart users such as myself.

1. More explicit wording explaining that the "Device Pairer" is a separate android/ios app that can be installed on the phone. Some links to the apps on the Play-Store/App-Store would be helpful.

2. More explicit wording explaining that you need to install the Meross Lan Integration - ONCE for set up... then again FOR EVERY device you wish to add as an entity. This was not clear to me until your comments, even after reading the instructions multiple times.

Also using the terms "meross_lan integration" and "Meross Hub Lan" interchangeably, when in fact they are the same thing - caused a lot of confusion for me and led me to think i was missing something.

Thank you again for all your help!

**Comment by HarveyHeart** [comment]
I've been looking for where to find the Device/MQTT Key for a bulb, but I am unsure if I am just missing the answer or if what I've found is incomplete.
I am trying to find the Device Key without giving Meross login info to home assistant. My roommate and I both have our own sets of bulbs, and both show up after installing Meross_lan but we cannot pair them to Home Assistant without the device key or login. 
<img width="669" height="448" alt="Image" src="https://github.com/user-attachments/assets/29cdbf90-a8ba-49b1-9110-9b536e1e2257" />

<img width="565" height="393" alt="Image" src="https://github.com/user-attachments/assets/318e5a78-1434-4311-a60f-1869166f0260" />

Can we get the Device Keys on our own? Or are we _required_ to log into our Meross accounts into Meross_lan or the Pairer App?

**Comment by krahabb** [comment]
I don't think it's possible to get the device key in any other way (at least in my knowledge)

Maybe, 'sniffing' the clear traffic between the official app and the device being configured on initial setup since the device key is configured exactly when the device is being paired to the Meross account and the initial pairing is typically 'clear enough' (i.e. not encrypted)
