### ISSUE TITLE
native unit of measurement '%' which is not a valid unit for the device class ('signal_strength')

### ISSUE THREAD

**Issue by B-Hartley** [krahabb/meross_lan#239]
Home Assistant 2023.1.0b1
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221228.0 - latest

error in home assistant log.

thanks

**Comment by krahabb** [comment]
Thank you for signaling this...I'm looking for some info about the real unit/scale of the device value since HA 'etiquette' would allow only 'dB' and 'dBm' for 'signal_strength' entities

Any hint would greatly help!

**Comment by B-Hartley** [comment]
Dev channel on discord suggests that you should drop the device_class and have uOM of %.

**Comment by jkp** [comment]
Seeing this too - imagine its low prio but would be nice to help clean-up cruft in my logs :)

**Comment by roby1o** [comment]
Some problem here.

I know Meross App indicate signal with % too, but maybe HA is right and a 30% Wifi signal means nothing.
30% of what?

**Comment by krahabb** [comment]
I agree the log is annoying, I've tried investigating the base power reference level of the devices in order to convert the % to a reasonable dBm but there's no official info available so I'll likely drop the sensor 'device_class' in order to retain the '%' uOfm

**Comment by Fonsos** [comment]
Same error showed on another HACS integration and they dropped the sensor 'device_class'. At least we have the value there so we can know if it's near or away from the signal source.

**Comment by nigam-sa** [comment]
I am seeing similar from couple of Meross devices. Strangely its coming for devices which has over 90% signal strength and also for meross hub. Its not coming for all the devices i have around 20

logs below if it helps - 

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:980
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 15:45:34 (9 occurrences)
Last logged: 15:45:35

Entity sensor.smart_switch_2008200067413990825748e1e92cc930_signal_strength (<class 'custom_components.meross_lan.sensor.MLSensor'>) is using native unit of measurement '%' which is not a valid unit for the device class ('signal_strength') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.smart_plug_1911079471302425186948e1e9110148_signal_strength (<class 'custom_components.meross_lan.sensor.MLSensor'>) is using native unit of measurement '%' which is not a valid unit for the device class ('signal_strength') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.smart_hub_1912186804966326280548e1e913ca18_signal_strength (<class 'custom_components.meross_lan.sensor.MLSensor'>) is using native unit of measurement '%' which is not a valid unit for the device class ('signal_strength') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.smart_switch_2010266184378990833348e1e9392093_signal_strength (<class 'custom_components.meross_lan.sensor.MLSensor'>) is using native unit of measurement '%' which is not a valid unit for the device class ('signal_strength') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.smart_plug_1911073938290625186948e1e91100de_signal_strength (<class 'custom_components.meross_lan.sensor.MLSensor'>) is using native unit of measurement '%' which is not a valid unit for the device class ('signal_strength') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by zigomatichub** [comment]
The device class for % is 
device_class: power_factor

Example:
state_class: measurement
unit_of_measurement: %
device_class: power_factor
friendly_name: WiFi strength

**Comment by B-Hartley** [comment]
power_factor is a totally different thing.
It relates to electricity supplies, (the ratio of real power and apparent power) not signal strength.
I don't think it is appropriate for this measurement.

**Comment by zigomatichub** [comment]
It's appropriate and used by other integrations into HA.
power_factor: Power factor (unitless), unit may be None or %

**Comment by B-Hartley** [comment]
but it's not appropriate as a device_class for signal strength.
The point of a device_class surely is so you know the type of thing that you are recording.
if you are recording power_factor than a device_class of power factor would make sense.
If you are recording signal strengh, then ideally a device_class of signal strength would be ideal, but as we know at the moment that cannot be %, it can only be dB. 
So no device_class is the only logical way forward.

(in my opinion)

**Comment by zigomatichub** [comment]
To transform a WiFi signal strength from percent to dBm, you can use the log10 function to convert the signal strength:
dBm = -100 + (20 * log10(percent / 100))
Then you can use the appropriate device class if you prefer.

**Comment by krahabb** [comment]
Hello,
I definitely agree with @B-Hartley here on the device_class matter since 'power_factor' usually refers to the ratio of apparent power vs effective power (or whatever ratio in that regard...) in energy delivery/distribution and does not fit for this case.
I'll leave the device_class empty and the unit as '%' since I'm not sure about the base power the Meross(s) are using in regard to calculating their signal strength percentage so the suggestion from @zigomatichub , even though formally correct, leave us with an unknown base power to be used in calculations (unless some insider at Meross could disclose that base power level:)
