### ISSUE TITLE
MTS200b 7.0.0

### ISSUE THREAD

**Issue by cagnulein** [krahabb/meross_lan#245]
Hi, this device is correctly recognized but i can't see any statistics at all. How can I help you with the integration?

**Comment by cagnulein** [comment]
![image](https://user-images.githubusercontent.com/48216/213193368-8b245520-d047-44a6-8bd8-69f2bcca9bb8.png)

@krahabb thanks! this is what i see from hass. 

i'm a firmware developer so if you need some information i guess i'm the right one :) 

just tell me how can i collect some information about this (i'm out of this meros thing completely)

**Comment by cagnulein** [comment]
[mts200b-1674112759.csv](https://github.com/krahabb/meross_lan/files/10455547/mts200b-1674112759.csv)
attaching the trace
i see that the data are fine, so it simply doesn't populate the entities on HASS any idea @krahabb

**Comment by krahabb** [comment]
yeah....
that's weird..to say the least...
It looks you only can see the 'device_tracker' entity (likely coming from your router integration).
I've tried your trace in my 'emulator' and it shows up fine with every supposed entity so I think it's something happening when the device configuration gets loaded. Either the device key is wrong (but then you shouldnt be able to set it up from the beginning..also the trace looks like communication is ok so this is a dead end)

Maybe there's a sudden exception during device initialization (should have some log in HA for that) due to a bug or unexpected state. The device got somehow initialized but entities were not added to HA

**Comment by cagnulein** [comment]
there is no error at all. I will try to restart HASS this evening (I have to play safely here because my wife is really dependent from HASS nowadays :D )

**Comment by cagnulein** [comment]
@krahabb I feel very sorry about this: i saw that your integration wasn't updated in my HASS installation. Updated and now works perfectly! Sorry for the time lost!
