### ISSUE TITLE
Devices unavailable on 3.0.0

### ISSUE THREAD

**Issue by pops106** [krahabb/meross_lan#252]
Hello,

I just upgraded to 3.0.0 and all but 1 of my plugs are unavailable. Downgrading to 2.6.2 fixed the issue. I am just using http so no mqtt. 

Ignore the vintage bulb, it is off at the moment.

Logger: custom_components.meross_lan
Source: custom_components/meross_lan/helpers.py:27
Integration: Meross LAN ([documentation](https://github.com/krahabb/meross_lan), [issues](https://github.com/krahabb/meross_lan/issues))
First occurred: 14:28:31 (12 occurrences)
Last logged: 14:28:34

MerossDevice(Smart Plug Washing Machine) MerossKeyError in async_http_request:
MerossDevice(Smart Plug Study Fire) MerossKeyError in async_http_request:
MerossDevice(Smart Plug Dishwasher) MerossKeyError in async_http_request:
MerossDevice(Smart Plug Solar Charger Block 1) ServerDisconnectedError in async_http_request: Server disconnected
MerossDevice(Smart Bulb Study Vintage) ClientConnectorError in async_http_request: Cannot connect to host 192.168.5.30:80 ssl:default [Connect call failed ('192.168.5.30', 80)]

**Comment by Cippo2019** [comment]
Hello
me to
update to 3 and all devices become unavailable
roll back to 2.6.2 and all device are all on ! :-(

wbr

**Comment by krahabb** [comment]
Hello @pops106  and @Cippo2019,

I think you were using your devices with a 'wrong' configuration that is, the device key you are using is likely set to 'empty' and the device is working with the 'key-hack' 
This is no more allowed on 3.0.0 sinc eit can cause random issues and disconnection so I've decided to completely disable this feature.
On 3.0.0 you should enter the integration configuration for each device and set the proper key. 

From meross_lan readme:
`device key: this is used to sign messages according to the official Meross protocol behaviour. This should be prefilled with a known key from other devices if you already configured any before. If you enter a wrong or empty key a menu will ask you if you want to manually retry entering a different key or if you want to recover the key from your Meross account. If your device is still paired to the Meross App, this is the way to recover the device key since it is managed by the Meross App and saved in your cloud profile.`

I apologize for not clearly stating this sort of 'breaking change' coming with 3.0.0 and I'm going to better clarify this on the release page.
Thank you for submitting the issue so I can 'repair' the docs with more info!

**Comment by Cippo2019** [comment]
ops..:-(
thanks Krahabb

could yu help me into the steps to get the value and use to maitenin the device id and so on and not loose the device into HA ? 

thanks a lot

**Comment by pops106** [comment]
@Cippo2019 

That was exactly it, I always thought it was just doing the cloud retrieve in the background.

Cheers

**Comment by guybw** [comment]
How do you find the key? I'm looking on the meross app ?

**Comment by Joshndroid** [comment]
Where in the Meross App do you find the device key? I have a bunch of switch not working after updating and likely need to add the key as well

**Comment by krahabb** [comment]
Hello @Joshndroid,
It's not in the Meross App (even if maybe last versions of the app allow you to see the device key).
Simply go to the integrations page for your devices and re-configure them. When you submit the configuration it will check if the key is good and if not it will prompt you for the cloud retrieve

**Comment by gianlucasullazzo** [comment]
Hi, I'm not able to use device key. 
After update to 3.0.0 all my devices (msh300 + 6 valves) were unavailable.
I just re-pair hub with meross cloud to get device key, then and re-paired with local broker but when adding hub to home assistant using the key, I get "key invalid" and all valves goes offline.
Roll back to previous and it worked.
Am I doing something wrong?

**Comment by krahabb** [comment]
If your device is not paired to the meross cloud you have to use the key used to reprogram the device pairing (likely 'empty') for your local broker.
So you have to use the key you used when re-pairing and not the meross key. The cloud one is valid when devices are paired to the meross app

**Comment by gianlucasullazzo** [comment]
> If your device is not paired to the meross cloud you have to use the key used to reprogram the device pairing (likely 'empty') for your local broker. So you have to use the key you used when re-pairing and not the meross key. The cloud one is valid when devices are paired to the meross app

Thanks for reply. Where  can I found the key I used when re-pairing? I just used the hack mode

**Comment by krahabb** [comment]
well..if you have not set anything specific while re-pairing for your local broker that should be empty. In meross_lan just try with the key field empty. The @bytespider utilities worked with a default empty key (which you could change on the command line when re-programming the device)

**Comment by gianlucasullazzo** [comment]
empty value does not work with 2.7.0.
Do you suggest to update again to 3.0.0 and try use empty value as well?

**Comment by krahabb** [comment]
As far as the key is correct any version should work but...versions pre 3.0.0 where able to use a key hack in case the key was wrong but this was configured in meross_lan by using no value for the key (This is a bit confusing..that's why I've removed this 'trick')
Which tool you used to pair the msh300 to your local broker ?

**Comment by gianlucasullazzo** [comment]
> As far as the key is correct any version should work but...versions pre 3.0.0 where able to use a key hack in case the key was wrong but this was configured in meross_lan by using no value for the key (This is a bit confusing..that's why I've removed this 'trick') Which tool you used to pair the msh300 to your local broker ?

The custom pairer app

**Comment by guivazcabral** [comment]
Upgrading to 3.0.1 also made my devices unavailable. Tried re configuring them but didn't work. If I try to configure the integration from scratch I get an error `Config flow could not be loaded: {"message":"Invalid handler specified"}`

**Comment by krahabb** [comment]
Hey @guivazcabral,
This kind of issue looks like related to a corrupted download from HACS. I've retested the config flows and they work ok both on 2023.1 and on 2023.3 (development). I need more time to install the 2023.2 (actual) release and test it there but I strongly suggest you to redownload the meross_lan integration from HACS (this is not the first time this kind of 'everything is broken' errors come up and usually resolve with redownloading..maybe there are some issue in HACS which is not able to guarantee a reliable installation..dunno since HACS is a good piece of software but 'trust no one' is always safe)

**Comment by Cippo2019** [comment]
Hi krahabb
so are you suggesting to wait until you test on 2023.2 before uprade t0 3.0.0 or 3.0.1 ? 
just to be sure becuase after problem i roll back to previuos release and i collect all keys.
now i am ready to upgrade againi to new meross lan version.
:-)
thanks

**Comment by Cippo2019** [comment]
hi
update now t 3.0.1 with correct key inserted. it works for me. thanks a lot @krahabb

**Comment by krahabb** [comment]
Hello @Cippo2019,
I don't think there's a general issue with 3.0.0 nor 3.0.1 since a lot of testers confirmed it working correctly and upgrading with no issues.
Beside a very specific bug in #254 all other issues should be related to 'incomplete' configurations which were working on previous versions just because of some 'woodo magic' which is now gone.
In some way the new version is stricter in setup and so the issues for those configurations lacking the correct key. But this should be just a little pain for the good since, once fixed, the devices should work more reliably than before

**Comment by gitioda** [comment]
> h a 'wrong' c



> Hello @Joshndroid, It's not in the Meross App (even if maybe last versions of the app allow you to see the device key). Simply go to the integrations page for your devices and re-configure them. When you submit the configuration it will check if the key is good and if not it will prompt you for the cloud retrieve

**Comment by Joshndroid** [comment]
> Hello @Joshndroid, It's not in the Meross App (even if maybe last versions of the app allow you to see the device key). Simply go to the integrations page for your devices and re-configure them. When you submit the configuration it will check if the key is good and if not it will prompt you for the cloud retrieve

Thanks mate, this worked perfectly!

**Comment by anant418312** [comment]
How could one retrieve the Device Keys if their devices were not registered with the official Meross Account?

**Comment by krahabb** [comment]
If you've used any of the tools to bind your devices to a private MQTT broker, the key is usually configured during pairing.
It could have a default of null or empty so you could try that...if not you should check the documentation for the pairing tool you've used
