### ISSUE TITLE
MTS 200 lose connection every 2-3 weeks

### ISSUE THREAD

**Issue by FelixGraf404** [krahabb/meross_lan#260]
Hey,

every 2 weeks my mts200 lose their connection to homekit/homeassitant

Finally i get an log from the error time:

[errorlog_meross.txt](https://github.com/krahabb/meross_lan/files/10776725/errorlog_meross.txt)

To reconnect them i have to reset them and add them new to homekit/homeassitant.

Sometimes i have to reconnect them complete.

**Comment by BlackDragon7402** [comment]
I noticed the same behaviour.
But there are mutliple error cases for me:

1. Disconnects in homekit and home assistant and wifi led blinks (still connected to wifi and also pingable)
2. Disconnects in home assistant and after a few minutes in homekit. wifi led doesnt blink this time also pingable
3. Just disconnects from home assistant. Homekit still works fine

Instead of resetting I just power them off which fixed the issues everytime except ones.
Due to this weird behavour I wasnt sure if it is a bug in the integration or maybe in the firmware of the meross devices themselves

**Comment by BlackDragon7402** [comment]
> You could try isolate the issue by temporarily disabling meross_lan and see if their connection with homekit is stable.

Will try this out for one of my thermostats. Probably still hard to troubleshoot because the error seems to occur every 4-8 weeks per device (not all of them at the same time). This makes it hard to tell if it just didnt happen again or if its caused by meross_lan

**Comment by Virus88** [comment]
I get the same error.

It doesn't matter whether you operate with Meross_lan or only via homekit or via the Meross APP.

I'm starting to think that the devices are just not good for anything.

In the home assistant I see the following message:
MerossDevice(Thermostat Buro) received signature error (incorrect key?)
MerossDevice(Smart Thermostat (2206242699353760120148e1e999c8a4)) received signature error (incorrect key?)
MerossDevice(Thermostat Badezimmer) received signature error (incorrect key?)
MerossDevice(Smart Thermostat (2206240777096460120148e1e999cadf)) received signature error (incorrect key?)
MerossDevice(Thermostat Wohnzimmer) received signature error (incorrect key?)

**Comment by CTJohnK** [comment]
Here is my experience.  

I have over 30 devices, some are HomeKit.  I use Ubiquiti network equipment with all my smart devices on a VLAN.  I have not and do not expect to update any of the Meross devices.  With the exception of two devices which completely stopped working, the Meross devices have been pretty stable.

I do have one wall switch which is problematic.  It is in my garage, in a metal electrical box, below the main level of the house and does not have a great WiFi signal.  To help, I setup an old TP-LINK WiFi extender in the garage which is closer to one of the WiFi access points.  Even with this setup, sometimes the switch goes offline and will stay offline for days.

I found the remedy is to reboot the TP-LINK extender, and within a few minutes, the switch is back online.  Reviewing some logs, without the extender, I see the switch in Unifi showing in an energy saving mode.  With the extender I don't see this happening, because when the switch connects to the extender, it disappears from the Unifi dashboard.  Looking in the TP-LINK extender dashboard, I see the switch.  When the extender is used and the switch goes offline, Unifi is showing the TP-LINK as being in energy saving mode.  Reboot the TP-LINK and everything works as it should.

A long story to suggest this - when the smart device goes offline, try rebooting the WiFi device which the smart device is connected.

**Comment by cagnulein** [comment]
same issue here, it happens in the 4-8 weeks range to me too. I was happy when I installed this meros on a room as a sample to extend it to the whole house (8 thermostats) but at this point I guess I should check something else. 

Anyone has some suggestions?

**Comment by Virus88** [comment]
According to my test, it doesn't matter whether it runs via Homeassistant or via the normal APP from Meross or via Homekit.

The thermostats lose the connection again and again and do not manage to reestablish it themselves.

I don't know if an internal key expires and can't refresh it.

It is only clear to me that I will expand these things and see if I can find some with Zigbee. Why does everything always have to be cloud-based... Too bad

**Comment by cagnulein** [comment]
@Virus88 thanks, at least we know what we don't have to buy. i will buy a zigbee one too.   I will do the same experiment without meross lan on my own too, just to confirm your behavior

**Comment by madner81** [comment]
I'm experiencing the same issues, but at the same time I've seen that when my Home Assistance instance is off (at the moment I'm running it only on a virtual machine), the MTS200 (b, in my case) works fine. So I'm starting to suppose that the integations (using this addon or the HomeKit Controller) are not well managed.

**Comment by cagnulein** [comment]
is https://github.com/krahabb/meross_lan/releases/tag/v4.0.0 could be possible releated also to this?

**Comment by krahabb** [comment]
@cagnulein,
release 4.0.0 was rolled out way after these issues arose so it is definitely a 'no'. As far as my experience goes, even if some meross_lan bugs could be implied (and sometimes they were) my general feeling is that Meross devices are not 100% (not even 99%) reliable both in hardware and in firmware so they often fail with no other responsibility beside their internal 'bugs' (both hw and sw)

It happened to me, a device (new) was apparently working (i.e. connecting, pairing, all ok) but then it wasn't always able to execute commands (with the original app). Sent back and substituted (thanks Amazon!) it's sibling was working ok with no flaw.

Other users sometimes reports similar behavior and what is described in this thread looks really like the same: sometimes (I'd say in a range around 5-10% of the devices - but this is only a 'feeling' so it is really a personal opinion) they fail for a factory issue.

In order to have some exact measures about the reliability of the ecosystem (HA/meross_lan/homekit) It would be nice to see if, among all of the users, is there anyone (or how many) able to see 'no issue at all' but that's hard to accomplish since people usually don't report 'good news'...

**Comment by mutlow89** [comment]
firstly, @krahabb thank you for all your work on integrating meross devices into home assistant!

I thought i should share my experience in case it is useful. I purchased 2 mts200b devices at the end of January this year. Initially I was using them via the meross app only and had a very stable connection without dropouts. The heating was being regularly used and adjusted via the app during this period.

As we progressed into the year two variables changed at roughly the same time (i can't remember exactly when).... as the weather got warmer i set the thermostats from "auto" to "off". I also installed the meross_lan integration.

Currently every 1-3 weeks, i notice both devices become unavailable in homeassistant. I will often check if they can be accessed in the meross app, this typically throws a timeout error. Checking the devices themselves they are still powered - but the wifi light flashes. Cycling the power to the devices gets them back on the network and functioning.

I had assumed the issues were caused by the lower frequency of use during the summer months. If there is any further info I can provide to assist with determining a root cause I would be happy to help out.

**Comment by BlackDragon7402** [comment]
Cant confirm this 100% (as it could also been caused by Home Assistant or Meross Lan Updates) but for like 2 months my MTS200 havent had any disconnects.
Im pretty sure this is since I installed the new firmware introducing the 0.1 degree measurement feature (7.6.7.1.1.4) on my meross devices

**Comment by cagnulein** [comment]
@BlackDragon7402 thanks for the feedback! Just upgraded the firmware too and I setup again meross lan to confirm your theory! I will let you know!
