### ISSUE TITLE
Home Assistant energy not reset

### ISSUE THREAD

**Issue by 0p3t0** [krahabb/meross_lan#264]
Hi, starting from last HA Update (march version), energy seems to be not well resetted to zero ad midnight
![image](https://user-images.githubusercontent.com/59409205/223063723-f90cd3f4-7d31-45d8-be8b-2170d92db587.png)
![image](https://user-images.githubusercontent.com/59409205/223063868-5738b4e2-de26-4baf-8937-118178e50ec3.png)
This is happening only on 
mss310r 2.0.0 Firmware: 2.1.4 (latest today)
But is working fine on
mss310 6.0.0 Firmware: 6.3.6 (latest today).

I'm running MerossLAN V.3.0.2

Do you have any suggestion?
Thanks a lot

**Comment by krahabb** [comment]
Eh..that's bad since it happens also on my mss310 (exactly same old fw 2.1.4) but I still have HA 2023.2.
Also, the sensor values sent to HA are exactly the state coming from the device (This is a design decision I try to enforce almost everywhere possible). This is especally true for the device energy reading so I really guess it's a bug in the firmware.

Now this opens a question if I should fall apart a bit in the design rule and maybe process the device data to acually reset them but still, if the device doesn't report the expected consumption this might be worse than the bug itself.
I guess the energy statistics are not affected though (they should reset for the day) since HA should rightly process the reset for the sensor at the first reading posted after midnight.

**Comment by 0p3t0** [comment]
I think identification with firmware can help.
Eventually, if is possible to enter a manual number for each device, can be dynamically subtracted from the readed value, but of course would be better a restore of previous behavior.
I'm part of beta program, so I'm glad to help debugging and give you feedback using beta releases, just let me know how you prefer to proceed.
Thanks a lot in advance for the wonderful integration you've done :)

**Comment by krahabb** [comment]
Thank you,
I've checked the HA statistics and they seems affected too but the problem lies in the firmware and I have to think a bit about it...
sadly enough these data will 'corrupt' the long term statistics..I'll try and see if I can come up with a quick patch

**Comment by krahabb** [comment]
Oddly enough, I have a spare mss310 with same fw level that I use for development and its energy value got reset correctly on 1st of march.
Maybe, since I keep unplugging it, a boot cycle of the device could reset the device state (I hardly think this is tru since historic energy data are surely stored in a sort of eprom/flash inside the device but this is the only thing that comes to my mind in order to explain why, this very same device model, doesn't show the issue.

You could try too to unplug and restatrt the mss310 and see what happens

**Comment by krahabb** [comment]
I'm working on a 'quick' (not so quick tbh) fix but while working on that different things popped up in my mind...
I hope to finalize that tomorrow and update the release.
I'm basically building a new sensor for the energy based off device power readings. I'm still testing a bit of things but the idea is
to bypass the meross integral sum (or give the option to)

**Comment by krahabb** [comment]
Hello @0p3t0,
You could find the patched code in the 'lazy_dev' branch. If you're up to you could give it a shot and see if it works.
As I've previously said, patching the original readings might lead to worse results as soon as the devices change their behavior (which happened with the bug but could happen again with unforeseen ramifications)
Long story short:
the original device consumption reading is still there but I've added an euristic to try reset it's daily reading when catching the behavior of this bug. If the device doesn't show the bug the patch doesnt kick in so the readings are still the 'original' one.
Beside this, I've added an extra sensor ('energy_estimate') which instead calculates the integral sum of power readings in meross_lan thus emulating the energy consumption. This sensor is totally in code and, in my experiments, looks pretty promising and follows accurately the consumption readings from the device, except that, being implemented in meross_lan, any bug should be fixable in case ;)
Those two sensors in the end should show 'almost' exact same values when the device is connected.
Of course, when the device is not reachable, the software sensor cannot calculate any sum so it will just sit and start counting again only when the device is connected again. You could then see this sensor falling a bit behind every time the device is working (so its counter summing) while not connected to HA
The software sensor sum should survive HA restarts too since it (should) restores its last good state and restart from there when HA is restarted or the configuration changes

Last thing but the most important: HA/meross_lan must be connected to the device across midnight in order to catch the first consumption reading from the device for the new day and see if it needs to 'offset' the readings for the day or not. If not, it cannot tell if the day was starting good thus relying on what the device is reporting.

That said, when you install this, you should see the energy reset kick in correctly by midnight

**Comment by 0p3t0** [comment]
Thanks a lot, just downloaded the source and replaced custom component folder.
I'll plan a midnight reboot in order to reconnect to HA all devices and start the communication in right way.
I'll let you know in next days the behavior, in the meanwhile thanks a lot for the excelent work!

**Comment by krahabb** [comment]
You should have it running 'before midnight' (at least before the last consumption update before midnight to be more precise) so the transition could rightly be intercepted else it will not know something wrong happened from the last known value from the day before. Anyway I will post some other improvements over the day and let you know. Right now, your version should work (mine got correctly 'fixed' tonight)

**Comment by 0p3t0** [comment]
I confirm is now working much better!
![image](https://user-images.githubusercontent.com/59409205/224537019-21666aa0-8f6c-4a69-a041-1db0e0a5bd41.png)
Also new sensor Energy Estimate is working, not same values, but acceptable to have an idea about consumption :)
![image](https://user-images.githubusercontent.com/59409205/224537074-cbeaa031-8a7d-42bc-9507-0ead8113dd6a.png)

**Comment by krahabb** [comment]
# How the energy sensors work with Lazy.3

This is  a recap of the features provided in Lazy.3 for energy consumption. Their final implementation is based off the current thread issue and some other tweaks which are detailed here:
There are now 2 energy measures per device in meross_lan and they work as this:
- 'energy' (the legacy one): This sensor is just reporting the energy measure computed inside the device. This sensor, usually resets at midnight in device local time (this is important to know if you want to see the reset 'aligned' to HA local time midnight). HIstorically, meross_lan didn't process at all this reading so, the values reported in HA, were exactly the (last in time) values reported by the device with almost no 'data processing'. This has changed in Lazy.3 in order to fix the bug (in device firmware 2.1.4) reported on this issue. Now meross_lan tries to detect if the energy reset (which still occurs at device midnight local time) is 'reasonable' (it should always reset to 0 or 1 in a simple world but this is not true, actually depending on the average power consumption level during the update period, so, if you have a big consumption across midnight, the value starting the new day is not 0 but a bigger level). The fix then is trying to compute a reasonable value for the starting level and if it detects the device is not reporting a good value, meross_lan will offset the readings for the day (on next midnight it will compute the reset/offset again). This behavior (and the fact meross_lan is 'offsetting' readings) is inspectable in the sensor attributes: you will see an 'offset' attribute in case meross_lan is patching the value or nothing if the reading was 'good' at midnight and is not being patched. In the end you should always see a proper reset after midnight (always in device local time!) even for devices experiences this and maybe other accumulation/tripping bugs. This offset is persisted through reboots so, if you'll restart HA during the day, you should still see the sensor data 'patched' for the day. Important to note: meross_lan will detect the issue only at midnight tripping so it will not patch any value 'in the wild' when you re-start HA
- 'energy_estimate' (new sensor in Lazy.3): While working on the fix, I've found it reasonable to provide a 'completely new' sensor reporting energy in a different way. This sensor is implemented in meross_lan and is not reporting energy computed in the device. It just provides an integral (trapezoidal) sum of power readings (something you could even implement with templates or with https://www.home-assistant.io/integrations/integration/). This sensor is initially disabled to not clutter your UI and HA with an almost duplicated sensor but you could easily put it at work should you prefer it over the legacy one. Check the pros-cons for hints on deciding

## Short comparison
### 'energy' (legacy): 
- provides almost native values computed in hw (should be very accurate)
- as far as the device is powered it measures energy even if not connected to HA (so you don't lose data should you have HA offline or any connection issue)
- resets at device midnight local time
- even if unusual it sometimes fails because of firmware bugs (not always 'patchable' at meross_lan level)
- on HA restarts, if meross_lan was offsetting the data for the day, it will keep (restore) the offset for the day
### 'energy_estimate' (newer software implementation): 
- it is slightly less accurate since it estimates energy only on power sampling (which happens every 30 sec by default) by HA/meross_lan
- if HA is not running it doesnt measure (so you lose data)
- it resets at midnight HA local time
- doesnt suffer any device firmware bug (unless power readings are bugged!) and you can always blame me for any inconsistency. Any bug, being in meross_lan, could be fixed
- on HA restarts it restores its previous reading for the day and re-starts accumulating energy (so you just lose energy consumed while offline)

**Comment by krahabb** [comment]
Just for future (and past) reference, I finally came across the same type of issues previously reported for the same kind of bug. It looks it is not only on 2.1.4 fw but spreads across multiple ones.
Oddly enough it looks like the 1st of march is a kind of a trigger...
At any rate the Lazy.3 patch would fix all of these since they all show the same pattern
