### ISSUE TITLE
No TimeZone field

### ISSUE THREAD

**Issue by Ostepanov** [krahabb/meross_lan#267]
Hello,
I'm trying to reconfigure the rest of my devices, but it seems that time zone field is completely dissappeared from integration.
How can I enable it? Or how to send a message to device with a correct timezone?

Thanks!

## Version of the custom_component
3.0.3

## Version of the device
Name/Model: Meross M310
Hardware: 6.0.0
Firmware: 6.3.21

## Describe the bug
![mers](https://user-images.githubusercontent.com/73646505/226196326-539ef00f-c30d-4056-9d25-bca00ae4decb.png)

**Comment by krahabb** [comment]
Hello @Ostepanov,
The feature to configure the timezone for the device is only available when the device is binded to your local MQTT broker and receives regular mqtt messages.
This is a kind of 'safety' feature since when devices are instead Meross-bound some of their timezone settings are kept updated by the Meross cloud services and I don't want to mess with that.
In the ongoing release there are some news about it but it will take some time since I'm working on a huge improvement
