### ISSUE TITLE
Warning in log: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by czornikk** [krahabb/meross_lan#268]
Since Meross LAN version 3 (currently on 3.0.3) on Home Assistant 2023.3 (currently on 2023.3.5) I get the following warning in Home Assistant logs after restarting Home Assistant:

```
ConsumptionSensor(energy): error(invalid literal for int() with base 10: '0.000') while trying to restore previous state
```

**Comment by ChristophCaina** [comment]
just received the same error - and, it seems that it corrupted my statistics in the energy dashboard - which I had to recover manually.

**Comment by krahabb** [comment]
I'll check this.
To be honest, the ConsumptionSensor carries int values (the native Wh from the device) so that 'float' state shouldnt really happen. Maybe you set the precision to show 3 decimal digits? This would help me investigate why this value popped up in your state.
As for @ChristophCaina losing its statistics this too shouldnt happen. The error is just logged but the sensor should work as expected. The state recovery is only needed to 'patch' the daily consumption when the device is reporting incorrect offsets.
If your device is not (which I hope are the majority) the state restoration is simply useless and any error there should be no harm. Of course this is by design and the fact it's happening means there's some bug linging around.
I would need more context in order to see what else (if any) is 'ruining' your statistics. Nevertheless I'll try to review the whole thing to try guess where things could go bad with regard to statistics

**Comment by czornikk** [comment]
I have my own [integration sensor](https://www.home-assistant.io/integrations/integration/) for the energy tracking and I do not use the one delivered by the Meross integration, I have left it as default (and could actually disable it, I'll way to see if I can help in the search of the bug). 
The estimated sensors from the integration are also disabled (per default I think?)
An example configuration of one of the normal energy sensors:
![image](https://user-images.githubusercontent.com/47973790/227271875-8db55446-3852-45c0-a9dd-49032566e941.png)
Also to note, I have disabled the history for this sensors (in the recorder). Could this be causing that issue?

**Comment by ChristophCaina** [comment]
> Also to note, I have disabled the history for this sensors (in the recorder). Could this be causing that issue?

I don't think so, because I keep the history and recorder for them... and facing the same issue here.
I think - the change from Wh to kWh COULD be the issue here

![image](https://user-images.githubusercontent.com/26391061/227272695-4911837d-a57e-420b-9f9e-b9a1d3b7fa8c.png)


When I remember right, the sensors default was Wh -> with the change to kWh, it probably also changed the precission.

**Comment by czornikk** [comment]
> > Also to note, I have disabled the history for this sensors (in the recorder). Could this be causing that issue?
> 
> I don't think so, because I keep the history and recorder for them... and facing the same issue here. I think - the change from Wh to kWh COULD be the issue here
> 
> ![image](https://user-images.githubusercontent.com/26391061/227272695-4911837d-a57e-420b-9f9e-b9a1d3b7fa8c.png)
> 
> When I remember right, the sensors default was Wh -> with the change to kWh, it probably also changed the precission.

You are right, when switching back to Wh the warning does not appear on restart.

**Comment by ChristophCaina** [comment]
thanks for that confirmation.
Then, I will change the sensor back to Wh until an update might fix the issue

**Comment by krahabb** [comment]
Hello @ChristophCaina  and @czornikk,
Thank you for the quick check! 
I've reviewed the code and I can (sadly) confirm the state restoration failure, even if not 'harming' by itself and only appearing when HA sets a display precision with decimals, could mess the statistics since the sensor starts with a default of 0 as soon as it gets registered in HA and so triggers the statistics reset.
This is a 'side' effect of making the sensor now available to HA even if the device is not connected.
Since we can't really control how HA stores the state (decimals or not) I'm anyway going to fix this for the better and make it safer
