### ISSUE TITLE
MSG100 garage opener

### ISSUE THREAD

**Issue by MelleD** [krahabb/meross_lan#272]
## Version of the custom_component
v4.2.0

## Describe the bug
If I open the garage and click close while opening, the garage door stays in position. Then I can only click open, but nothing happens when I click because the garage can only be closed.

**Comment by krahabb** [comment]
Hello @MelleD,
The MSG100 real state is hard to know since the device only has the 'closed' contact and doesn't really tell if it is stopped halfway or wherever.
This in turns make every assumption about the state an 'optimistic' one easy to bug when you for example stop the opening run halfway.
In a real case what happens next really depends on how the garage controller (not the msg100 itself but the hardware physically controlling the movement) interprets subsequent command pulses received by the msg100).
For example you could also 'mess' the state by using the garage controller remote in parallel with the msg100.

The state is not always messed of course: if the command runs in full, the msg100 clearly reports garage opened or closed but still you have to keep in mind that the only reliable msg100 state is 'closed' (that's because the msg100 has the close contact in place and working good)

Having sayd that, I can't really tell if the behavior you are experiencing is a direct consequence of this 'optimistic' state or a real bug in meross_lan.

As I've said, meross_lan could be bugged by the fact it thinks the garage is opened (and so the next command will just close) or the opposite while what happens next really depends on the garage controller state (which is unknown in general)

For your issue, if you can only click open, I guess you stopped the opening movement before the physical contact of the msg100 got 'opened' so the device (and meross_lan) still thinks it is closed even if the run just did a few centimeters. In this scenario the garage controller could instead think the garage is opened and so the next command will just close (that's a mess I know)

If you can reproduce the issue while the meross_lan device is 'tracing' (https://github.com/krahabb/meross_lan/wiki/Diagnostics#debug-tracing) and then upload the results I could try catch the issue: maybe it is a 'real' bug in meross_lan which just kicks in when you stop the run halfway

**Comment by MelleD** [comment]
Hey @krahabb,

Thank you for the detailed answer 👍 
I'm aware that the conditions for the MSG 100 probably don't give much information.
As a test, I simply opened the garage and stopped "halfway" how you described.

Then I just had a "deadlock": I could then press open again, but nothing happened. And the door status is not changed.
The Meross app probably handled this "correctly". Once the door is shown as open, you can only close it.

I guess, the close button should probably always be displayed as soon as the door has been opened.


I'll turn on the tracing and upload the log later :)

**Comment by MelleD** [comment]
I tested it again:

Current behavior:
1. Open the door
2. Stop (midway)
3. Open only is available as switch. However, this does nothing and it can be pressed several times.
4. Deadlock door stays half open and nothing can have been done


From my point of view it should behave:

1. Open door
2. Stop (midway)
3. Close button should be active until the gate is closed completely.

Log

[msg100-1680536495.csv](https://github.com/krahabb/meross_lan/files/11140287/msg100-1680536495.csv)

**Comment by MelleD** [comment]
@krahabb hey again

 I think now i have the issue and can reproduce it.
 
 1. I open the garage door with HA
 2. I close it half way with the a physical button
 3. HA show i can close it ( up is disabled)
 4. Press close, but the garage will open
 5. HA open (permanent) enabled, but nothing happens when i click on it, because garage is open
 
 With the meross app directly it works.
 
 Should i provide some logs?

**Comment by krahabb** [comment]
Hello @MelleD,
sorry for being absent here..I'm a bit off at the moment but we'll be back soon chasing this and other issues ;)

**Comment by MelleD** [comment]
@krahabb it's okay not very critical. Have a good time :)

**Comment by krahabb** [comment]
I guess I've found the origin of this bug as it appears when `meross_lan` is also using the Meross cloud connection to optimistically monitor the state. This fix will be soon in the pre-release (4.4.x series).

**Comment by MelleD** [comment]
@krahabb cool thanks. I will try it.

I actually don't need a cloud connection at all because I don't even use the app. What is your recommendation for this? Should I delete the Cloud Connection?

**Comment by krahabb** [comment]
Well, since your device is anyway Meross cloud paired, having the cloud mqtt connection is a nice plus since it allows you to receive 'instant' status updates from the device through MQTT...else, having HTTP only, `meross_lan` needs to periodically poll the device in order to get its state. This means, when you operate the garage door from the remote or the app, HA would receive the correct state only after the polling cycle (on 30 seconds by default)
