### ISSUE TITLE
Error in async_http_request: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by scannifn** [krahabb/meross_lan#28]
Hi, I'm trying to replace Cloud integration  with this one (LAN). I'm using the last one integration v2.0.1 on HASSIO.

Just for your info I still have installaed Meross Cloud IoT integration.

After added my two devices MSG100 cover garage I checked in the registry and there is this error:

Logger: custom_components.meross_lan
Source: custom_components/meross_lan/logger.py:29
Integration: Meross LAN (documentation, issues)
First occurred: 11:08:41 (2 occurrences)
Last logged: 11:08:41

MerossDevice(2008204790056336100448e1e92ceb3d) error in async_http_request: 'str' object has no attribute 'get'
MerossDevice(2008206126994936100448e1e92ce8b8) error in async_http_request: 'str' object has no attribute 'get'

**Comment by scannifn** [comment]
Hello @krahabb , please could you leave a comment related to your action: closed? It will be appreciated

**Comment by krahabb** [comment]
Hello @scannifn 
Very precious hint here since I cannot really test the garagedoor since the code is just 'guessed'
This  error is of course related to a lack of safety checks when parsing responses and I'm already working on making it more robust but I would need some more logging in order to better sort it out.
We'll continue this topic on #29 if you're up to.

To enable debug logging please follow this one: https://github.com/krahabb/meross_lan/issues/12#issuecomment-846390799

**Comment by krahabb** [comment]
I thought I was able to write before the GitHub UI close...

**Comment by krahabb** [comment]
Like I said we'll contine on #29 in order to have a consistent flow :)

**Comment by scannifn** [comment]
I'm really sorry!! I was too fast... whatelse can I say: SCUSA!
Ok, we can continue to troubleshooting on #29.
Thanks!

PS I f you need to have more details you are welcome!!! :)

**Comment by krahabb** [comment]
FIGURATI!!!
I'm italian too :) You were very fast in replying but it was me dumb closing that way!

See you
