### ISSUE TITLE
no IP to mss310 only Host: MQTT

### ISSUE THREAD

**Issue by Voosjey** [krahabb/meross_lan#298]
Ich kann bei meinem mss310 keine IP vergeben, das System will nur über die Cloud schalten.

I can't assign an IP to my mss310, the system only wants to switch via the cloud.

**Comment by krahabb** [comment]
Hello @Voosjey ,
This is actually 'by design' and it happens when devices are discovered over MQTT rather than HTTP. In this scenario, if you 'still' want to manually set the IP address you have to remove the configuration and manually add it back with the desired IP.
At any rate, even if you can't configure the IP, meross_lan should be able to communicate with HTTP since the IP address is known anyway via some protocol messages (in some way the meross_lan IP address configuration is really only needed to initially discover the device when it doesn't work automatically)

**Comment by krahabb** [comment]
Latest version allows to set/reset the host field in configuration even when 'MQTT binded'
