### ISSUE TITLE
mss425f socket strip main sensor issue

### ISSUE THREAD

**Issue by chipsn** [krahabb/meross_lan#314]
Hello, on my socket strips mss425f (hardware version 3.0.0, firmware 3.1.2) the main sensor of the entire strip does not switch on when switching on a single socket or the USB, but remains off, and vice versa. However, this works perfectly with the mss425e socket strips (hardware version 6.0.0, firmware 6.2.3).
Best regards Carsten

**Comment by krahabb** [comment]
Hello @chipsn ,
I'm sorry to not being able to help you for this since I don't know these devices in details. Maybe other users could help here by confirming/denying the same behavior for theirs.
My suggestion would be to overcome this issue by using an HA automation in order to automatically turn on the main switch whenever any other 'child' is turned on.
Of course, this could be implemented as a 'native' feature in `meross_lan` too but I'm not in a position to consider this as a 'desirable' one for every user. Let's see if something pops up in the discussion but, as I've said, I guess you could esily fix this with the HA automations feature
