### ISSUE TITLE
Automations Change Color on Smart Wi-Fi Ambient Light MSL430

### ISSUE THREAD

**Issue by moebis** [krahabb/meross_lan#317]
I'm happy to report that the Smart Wi-Fi Ambient Light (MSL430) works perfectly with your integration. I couldn't get it to show up on the other HACS plugin that promises Meross integration. I setup an automation where an action happens (fridge opens, 3D printer stops, etc) and the ambient light turns on, doors closes light turns off. Great, fantastic. I wish I could specify the color, so I could use it as a status indicator. Any plans for that?

Thank you BTW. Do you have buy me a coffee link or sponsor this project? Would be happy to donate.

**Comment by krahabb** [comment]
Hello @moebis,
thank you for your comment! 
The option to select the rgb color should be available if you use the `light.turn_on` service in your automation(s). Just follow the official docs for the service in order to do so.

If you're able to use the light panel in HA to correctly set the light color and/or temperature on the MSL430 then, for sure, the `light.turn_on` service will do the job the same way.

If not, then I'd need a [diagnostic trace](https://github.com/krahabb/meross_lan/wiki/Diagnostics#download-diagnostics) for the device in order to better understand its features
