### ISSUE TITLE
Can't Add mss560 Dimmer Switch

### ISSUE THREAD

**Issue by tvillini** [krahabb/meross_lan#326]
Description:
I have 2x MSS560 Dimmer Switches. They were not auto-detecting, so I went in and added them manually... or at least tried to. The first one I did was fine. Worked beautifully.  The second one is giving me a Device Key Error. I saw something in the past where someone was getting a similar error, but I think it was after their device was already added and it was working fine.

## Describe the bug
I am unable to add my switch. I only get a Device key error when I try to add:
![image](https://github.com/krahabb/meross_lan/assets/28534987/6a0b87d5-73e7-492f-98d4-2948893fabd7)
This did work for the exact same switch type only a minutes before I tried adding this one.

## Debug log

This error originated from a custom integration.

Logger: custom_components.meross_lan
Source: custom_components/meross_lan/helpers.py:160
Integration: Meross LAN (documentation, issues)
First occurred: 5:22:00 PM (3 occurrences)
Last logged: 5:22:00 PM

MerossDevice(Smart Switch (2210192545481358080148e1e9abff85)): received signature error: computed=6d407c35dd1a825c9224c6e092c013d4, header={"messageId": "8f588287356f40668dbab91a751bee99", "namespace": "Appliance.System.Debug", "method": "GETACK", "payloadVersion": 1, "from": "/appliance/2210192545481358080148e1e9abff85/publish", "uuid": "2210192545481358080148e1e9abff85", "timestamp": 1697750519, "timestampMs": 945, "sign": "af013ff31905add093974264a559ff7c"}
MerossDevice(Smart Switch (2210192545481358080148e1e9abff85)): received signature error: computed=9a2bd194215bb29e01b857152982c1cf, header={"messageId": "56555137577f4141b2dd5266ce0a7bd3", "namespace": "Appliance.System.All", "method": "GETACK", "payloadVersion": 1, "from": "/appliance/2210192545481358080148e1e9abff85/publish", "uuid": "2210192545481358080148e1e9abff85", "timestamp": 1697750519, "timestampMs": 61, "sign": "9be6239050df48dd7e7887f4d61a2e75"}
MerossDevice(Smart Switch (2210192545481358080148e1e9abff85)): received signature error: computed=ce61fed68a24a68a813233a5278a790c, header={"messageId": "55eb6b98b40448fe957e4d64abc3a33b", "namespace": "Appliance.System.DNDMode", "method": "GETACK", "payloadVersion": 1, "from": "/appliance/2210192545481358080148e1e9abff85/publish", "uuid": "2210192545481358080148e1e9abff85", "timestamp": 1697750520, "timestampMs": 222, "sign": "e58dc50b40ef7055ea69a98ef3267db4"}
```

**Comment by krahabb** [comment]
Hello @tvillini,
The log you've posted says '...received signature error...' and it is usually not impacting the correct message management: in fact, `meross_lan` just checks the replies from the devices and eventually logs the signature error but still accepts the message as good. This could be regarded as a security failure in `meross_lan` since the signing check is a basic anti-tampering feature and the failing should mean the device/message was tampered but since meross_lan is 'almost always' local and the signature algorithm is weak anyway and sometimes, somehow, the devices (mine too) fail to sign, I've decided to not discard these messages which, 99.9% of the times are lecit and legal

Anyway, this shouldn't happen.
How are your devices configured? Are they binded to a Meross account? If so, their device keys must be the same (for the same account) - I guess you've already configured them so in meross_lan but..better be sure.

Beside that, there are other reports of this 'signature error' which I can't explain at the moment since in general, if the device key in meross_lan is wrong, the device doesn't reply at all or it just replies with a 'key error' which is managed and logged by meross_lan in a different way
This implies that, when meross_lan receives a message and uses the same (correct) key to verify the signature made by the device, the check should pass...but it is not happening (hence the warning log) and the only explanation would be that the message coming from the device was 'tampered' before coming into meross_lan

The next step would be to check if the devices hardware and firmware are the same and proceed to compare their respective [diagnostic traces](https://github.com/krahabb/meross_lan/wiki/Diagnostics#download-diagnostics) for any meaningful clue.

Also, what happens if you reboot your devices ? If it's a device firmware bug most of the times a reboot 'fixes' that....

**Comment by tvillini** [comment]
Hi krahabb,

Things seem to be better now. A bunch of my devices started working… without really doing anything to them. We should be able to close this now. Thanks!
