### ISSUE TITLE
mts200b Thermostat Heating Issue

### ISSUE THREAD

**Issue by geidorei** [krahabb/meross_lan#327]
Hi Folks

My mts200b central heating thermostat, after a few hours of operation, stops heating when in auto mode even though the temperature hasn't been reached, and says 'auto (idle)'. It doesn't appear to come back on unless I turn it off and on, or set to heat.

Does anyone have any ideas why this is happening?

**Comment by krahabb** [comment]
Hello @geidorei, I don't have one to check this behavior but we could try some steps in order to see where the issue lies.
My reasoning is:
if the device in `meross_lan` appears as 'idling' it means the device is correctly connected and the protocol is working since the 'auto(idle)' in `meross_lan` corresponds to a very specific bit of information sent by the device which is stating it is idling.
Now, there are issues in the MTS100-150 line of valves where they report this idling condition while they're in effect not idling: they're still heating 'full open' since the target temp has not been reached. `meross_lan` actually trusts this bit of information and reports 'idling' so this looks like a sort of bug in the device firmware sending incorrect informations (#331).

For your MTS200 we should check: 
- first if the device itself, disregarding what you see in HA, is still heating
- see if the device physical panel has any corresponding state indication: is it saying idle or heating?
- see what the Meross app says

If the device itself is reporting idling and it is effectively shutting down the connected heater then it could be a sort of internal timeout or protection where the device automatically idles after some time of heating (maybe a safety precaution? looks very strange)

I know for example that the MTS200 (maybe right the mts200b) has an overtemp protection feature used to avoid overtemp in a floor heating system
