### ISSUE TITLE
New MSS310 do not broadcast wifi network in coupling mode

### ISSUE THREAD

**Issue by fritut08** [krahabb/meross_lan#328]
I am not sure whether this is the right repository for this particular issue. I just bought a new set of Meross smart plugs (MSS310, not compatible with HomeKit) and noticed that they do not appear to broadcast a wifi network in coupling mode anymore. This network is used in @bytespider's [software ](https://github.com/bytespider/Meross) or the pairer app available for android devices to communicate with the plug and tell it to use a custom mqtt server. Did anyone else notice this yet? I do not see a way of using these new plugs with my own mqtt server. The plugs I bought a year ago have the same model number and could be set up through their wifi networks.

**Comment by fritut08** [comment]
Setting the plugs up via the Meross app for android works. The device is automatically discovered within a fraction of a second.

**Comment by fritut08** [comment]
The Meross app tells me the following information for the new plugs:
Firmware version: 8.3.2
Hardware version: 8.0.0

**Comment by krahabb** [comment]
This is really new!
I think the best repo(s) for the issue would be both the @albertogeniola [meross pairer app](https://github.com/albertogeniola/Custom-Meross-Pairer) or the @bytespider [meross utility](https://github.com/bytespider/Meross) since they're the tools used to configure unpaired devices.

I've read in some threads (likely in the @bytespider repository) that the devices, while in pairing mode, are able to either broadcast (AP) their own wifi (legacy pariring procedure) or, if they find an AP broadcasting their same wifi ssid, automatically connect themselves without setting up their own AP. Maybe this is the case.
Another way could be via bluetooth (with the device broadcasting some BLE services while in pairing mode) so the Meross app could detect them via this protocol. Just a guess

**Comment by SerialVelocity** [comment]
I encountered the same thing with the MSS315 matter-enabled plugs. To get around this, you can use any "matter" app to add it (Google Home/Meross/Home Assistant/etc) to your wifi, then you can just send the `SET Appliance.Config.Key` message manually to setup MQTT

**Comment by fritut08** [comment]
> This is really new!
> I think the best repo(s) for the issue would be both the @albertogeniola [meross pairer app](https://github.com/albertogeniola/Custom-Meross-Pairer) or the @bytespider [meross utility](https://github.com/bytespider/Meross) since they're the tools used to configure unpaired devices.

I just got around to writing an [issue ](https://github.com/bytespider/Meross/issues/72) in @bytespider's repository. So, I guess I can close this issue here.
