### ISSUE TITLE
MTS100 Unavailable

### ISSUE THREAD

**Issue by gianlucasullazzo** [krahabb/meross_lan#335]
Hi guys, I have 1 meross hub with 6 valves (mts100) connected. I used "auto" configuration with cloud key retrieve methods.
Since a couple of days some valve became unavailable in home assistant. I found the error in logs:
`MerossDevice(Smart Hub (.....)): received signature error: computed=d4182b326dbdbed01a16c4a74509e40b, header={"messageId": "be187a24b02b45f0b79d16ae54ade505", "namespace": "Appliance.Hub.Mts100.ScheduleB", "method": "GETACK", "payloadVersion": 1, "from": "/appliance/<appid>/publish", "timestamp": 1700579178, "timestampMs": 464, "sign": "b0eeb5d530691357911445e00595e114"}`

I changed batteries to valves but issue still persists.
After some hour they went back "online" for few minutes and then again unavailable.

**Comment by krahabb** [comment]
The log itself is appearing here and there in various installations but `meross_lan` is just logging that and then working as if the message was good (since it looks good overall, except the signature verification)
I have no clue why this happening here and there. Moreover, I've decided to completely suppress the log warning in future releases since, even if it might indicate an issue, 99,9% of the times it is not (and devices are working good beside the failing check on the `meross_lan` side).

At the moment I can only think of a firmware bug in some devices/versions, maybe transient, depending on some internal conditions hard to predict for 'us'. As it is now, it looks like the device setup its response (when queried from meross_lan) and then fails to sign it even if everything else looks correct.

Maybe the valves going offline and the signature 'fail' are related each other but there's nothing we can do to fix it: the logical conclusion might be the valves are broken somehow. Even if the Meross devices generally work ok, there are many reliability issues reported, where devices stop to work or just start to behave erratically
