### ISSUE TITLE
MSG100 delay sensors unavailable in V4.4.0  (also V4.4..x alpha had to revert to main stream)

### ISSUE THREAD

**Issue by Duke-Box** [krahabb/meross_lan#338]
- Issues without a description (using the header is not good enough) will be closed.

open and close delay sensor not supported and now use the defaults of 35 seconds for opening.
Device MSG100, Firmware 3.2.7
-  From changelog
"added support for newer garageDoor (msgXXX) firmwares with open/close delay x channel (fixing also #301)"

- Issues without debug logging will be closed.
 irrelevant

- Issues without configuration will be closed
Standard config I.e no change to my config apart from meross lan update
HA core 2023.11.3, OS 11.1, Supervisor 2023.11.3, frontend 20231030.2

-->

## Version of the custom_component

V 4.3.0 but issues is in V4.4.0 (only started in alpha V4.4.03 ? (latest alpha))

Reverted back to V4.3.0 solves issue

**Comment by krahabb** [comment]
Hello @Duke-Box,

My fault, nevertheless!
It looks like your fw 3.2.7 falls in an edge case not covered by latest 4.4.0 implementation.
I knew this could happen since I had a trace log in the past with exactly this garageDoor fw version.
That device fw is particularly 'wrong' since it doesn't support interacting with the device configuration for open/close duration
Previous meross_lan version was aware of this and built a total mess (behind the scenes) in order to 'emulate' the device open/close timeouts in HA with various issues in between (but finally resolved through various patches)

Now, for this release I've totally removed all of these 'emulation' since I thought that fw should have been superseeded by now with something newer (and less faulty) but either Meross didn't update the fw for that particular device hw version or you don't have the option to upgrade it so we're left with the issue.

I'll restore the 'emulation' behavior in the next update!

**Comment by Duke-Box** [comment]
A possible coincidence but about a week ago, Alexa stopped communicating with the MSG100 and a powercycle of the device brought it back
I wonder if the firmware was trying to update?

Anyway glad you know about it and I'll wait for the update.

Thanks
Mike

**Comment by Duke-Box** [comment]
@krahabb 

Hi
I notice that this is 'emulation' behaviour has snot been implemented in the latest release v4.4.1, Is this correct?

I still have to use v4.3.0 to make my MSG100 work properly with my automations.
Can you give me an expected timeline for this fix.

Many thanks
Mike

**Comment by krahabb** [comment]
Yeah, I've quickly restored the behavior but the dev branch has now gone too far away and I'm far from being able to quickly release the fix in the stable releases :(

Since I'm releasing a small patch in the meantime I'll see if I can merge this fix into the main branch together.
I'll let you know

**Comment by krahabb** [comment]
The pre-release channel has (or should have) the fix. You have to enable HACS pre-releases download in order to be prompted for the update (by default HACS only notifies and installs stable releases)

**Comment by Duke-Box** [comment]
Thanks

You mean beta releases?

**Comment by krahabb** [comment]
Yeah..kind of..I always struggle to identify where HACS asks for this and it is in the 'redownload' page for the repository in HACS: there you can instruct HACS to show beta versions (which are the github pre-releases despite the fact that I usually mark them as 'alpha' ;)

**Comment by Duke-Box** [comment]
Many Thanks - That's fixed it for me.
