### ISSUE TITLE
Cannot add integration

### ISSUE THREAD

**Issue by domoZAM** [krahabb/meross_lan#348]
Hi all, 
i'm a newbye and i try to use this integration.. The problem that i found is that i cannot add integration in my HA (Home Assistant Core 2023.1.7), when i try to add the integration  i receive an error popup "Impossible to load config flow:”Invalid handler specified"   
Any suggestion about where could be the problem?  ..Maybe the release of HA?
Thank in advance  you for your attention.

**Comment by krahabb** [comment]
Hello @domoZAM,
`meross_lan` used to be 'very' beckward compatible with older HA cores but latest changes (and especially the migration to python 3.11) in core led to abandon this 'policy' and support only very recent HA cores
I'm sorry I didn't update the requirement check in HACS configuration so that it now still states its compatibility with HA core 2023.1
As I've said, due to these continual changes I'm a bit lost at the moment about which versions are compatible but I'm almost sure latest releases only works on HA cores after 2023.7
If you 'need' to install it on core 2023.1 you're left with using a rather old meross_lan implementation (you could try with the first 'Cloudy' release....)
