### ISSUE TITLE
mts200b:  Issue with Preset Temperature Update and Missing Documentation for Schedule

### ISSUE THREAD

**Issue by robertoamd90** [krahabb/meross_lan#355]
Hi,

I have integrated 6 mts200b devices via MQTT into my MQTT broker, hosted on Home Assistant using the Mosquito add-on, and I'm very satisfied!

I have encountered 2 minor issues:

1. When I change a preset from Home Assistant, the command is reflected correctly on the mts200b, but the new temperature associated with the preset is not updated on Home Assistant as the new target temperature.
2. In the latest release (currently [v4.5.0](https://github.com/krahabb/meross_lan/tree/v4.5.0)), you have added schedule read and configuration features, but I can't find any documentation about these.

Thank you for your great work; I'm very grateful.

Roberto

**Comment by krahabb** [comment]
Hello @robertoamd90,
Usually, on the MTS100 (where I test the code) the current target gets updated after a while when you just update the presets setpoints. This is likely due to the fact that the MQTT message is getting PUSHed only after a while (this happens for different status messages though and is likely a way to avoid sending too much traffic when the device is getting operated)

The schedule instead is a very mess: it is something more than a toy at the moment since the HA framework doesn't have a proper entity system to manage this kind of feature so I figured out how to use the calendar entity which is the closest available.
At this point the calendar entity is well..a calendar, and seems to fit but there are a lot of subtleties trying to synchronize the HA calendar entity with the valve schedule.
This is a long story to say: don't expect too much ;)

You can set a new schedule by entering a new event with the target temperature typed in the event summary. Since the MTS schedule has its own rules, when entering an event this way, meross_lan 'converts' this info to something acceptable by the MTS. For example:
- you can't span multiple days with a single event
- the MTS only allows 6 slots x day to accomodate events. when you manually enter one it will move and adapt the other events since in the valve, the schedule is always full (i.e. it covers the full day) and events need to be contiguos
- In general, keep in mind meross_lan is always trying to accomodate your schedule with its 'full day covered 6 events scheme' even if you just see less (they're hidden from the UI but the device still have all of them)
- At the moment I've quikly tried the UI and seems like the HA calendar has introduced some feature to automatically accorpate events spanning across a day... this is introducing something unexpected in the meross_lan adaptation algorithm and need to be investigated. To be honest the calendar entity is keeping getting remanaged/improved on the HA side and this complicate things a lot in trying to mantain this feature usable enough for meross_lan..I'll try to keep up

**Comment by robertoamd90** [comment]
Hello @krahabb,

Thank you for your reply; I appreciate it.

Regarding the first point I noticed, if I change the preset directly on the device, after the blinking time, the preset and the associated temperature update on Home Assistant. However, when the preset change starts from Home Assistant, I have to reload the integration on the device to get the update of the new temperature.

I have two hypotheses:

1. When I change the preset from HA, the device sends the new temperature to the MQTT broker, but the integration doesn't capture the message.
2. When I change the preset from HA, the device doesn't send the new temperature to the MQTT broker because the original app sets the new temperature from the preset value directly.

I haven't done any thorough testing to verify my hypotheses yet. I hope to be able to do so soon!

for the scheduling, I did not understand where i can make the setup, temperature, slot etc.

Thank you,

Roberto

**Comment by robertoamd90** [comment]
Hi @krahabb,

I need to manually compose an MQTT message to update the schedule map on my MTS200B. However, I can only read messages from the MTS200B to the Meross LAN on my broker.

Could you assist me in crafting a message to change the standard schedule? 

I'm on a fully local setup and don't have the Meross app.

Thank you,
R
