### ISSUE TITLE
Add support for MTS960 Smart Thermostat

### ISSUE THREAD

**Issue by MylesHarding** [krahabb/meross_lan#356]
**Is your feature request related to a problem? Please describe.**
I recently added the MTS960 to my Meross smart devices. The Meross LAN did recognise it and added it to Homeassistant for me. It does not however show up as something that can be displayed with the Thermostat card.

**Describe the solution you'd like**
When I edit the dashboard on Homeassistant and pick a thermostat card, I would like the entity list to allow me to pick my MTS960 to control it (rather than having to goto the Meross app or the Apple Home app).

**Describe alternatives you've considered**
I have limited knowledge of the inner workings of Homeassistant and was not able to experiment. Currently I am having to manage the MTS960 via the Meross app or Apples Home app.

**Additional context**
Not sure what would be helpful as a screenshot, let me know what would be useful and I can try to get that for you.

**Comment by MylesHarding** [comment]
> A [diagnostic trace](https://github.com/krahabb/meross_lan/wiki/Diagnostics#download-diagnostics) will greatly help!

is this the thing you want?

[config_entry-meross_lan-7eab3229d5b1c5fa3b597674caec37ef.json.txt](https://github.com/krahabb/meross_lan/files/13794871/config_entry-meross_lan-7eab3229d5b1c5fa3b597674caec37ef.json.txt)

**Comment by krahabb** [comment]
Awesome!
Lot of work to carry on ;) right now seems good..I'll try implement something even though we're going to need som eiterations
Keep in touch!

**Comment by MylesHarding** [comment]
Thank you @krahabb 🍺

**Comment by krahabb** [comment]
The new release (Moonlight) with support for the MTS960 is now in [beta](https://github.com/krahabb/meross_lan/releases/tag/v5.0.0-alpha.3) 
If you would like experimenting with it I'd really appreciate your feedbacks

The implementation should be almost complete, except the fact I don't know how to 'map' the thermostat modes (cool/heat/comfort/sleep whatever they're named in the MTS960).
At the moment I've used the same codes as for the MTS200.

**Comment by redpizza69** [comment]
Installed the beta yesterday, and all seems good. No problems. Fantastic to have the temperatures displayed now. Thank you very much.

One thing though, is it possible to have a binary sensor to show when the temperature point has been reached and the power socket is now live? I have this thermostat in a greenhouse, and when the temperature falls below 5C the thermostat turns on the power socket in which a fan heater is plugged. The only way to see if the fan heater is on is by looking if the current is greater than zero.

**Comment by krahabb** [comment]
the state (idle or heating/cooling) is being decoded but if you don't have a consistent feedback in the UI the decoding is likely wrong.

I'd need a new trace (or more traces) in the different conditions i.e., when it is 'activated' because of the setpoint and so. I think these data are carried from the protocol but just I don't know which.

To be more clear, this is the actual assumptions of these data carrie din the '...modeB' paylaod (extracted from your previous traces):
```
        {
            "channel": 0,
            "mode": 2,
            "targetTemp": 2000,
            "working": 1,
            "currentTemp": 1915,
            "state": 1,
            "onoff": 1,
            "sensorStatus": 1
        }
```
some are pretty self-explanatory but other fields are more or less obscure. I've used my knowledge about the mts200 to infer that:
- 'onoff' means the thermostat is 'just on' i.e. working (being it in setpoint or not doesn't matter)
- 'state' usually carries the thermostat output i.e. 'state' == 1 means the output is active (heating/cooling) while 'state' == 0 means the thermostat is idling (but this could be different in mts960...)
- 'working' and 'sensorStatus' don't really tell me anything. Maybe 'working' is what we're looking for in order to see if the plug is active or not but we need the traces with these values changing in order to infer their meaning
- 'mode' also, should tell us if the thermostat is in cooling, heating or whatever mode. In current implementation I've used the same codes from mts200 but I don't expect the mapping to really be the same

I think I'm going to add a 'bunch' of diagnostic sensors to expose these values 'live' so you could maybe check their behavior without the need for tracing

**Comment by redpizza69** [comment]
I upgraded to alpha.4 and can now see extra diagnostic sensors. When the temperature drops below the threshold and the socket is turned on, the "State" sensor changes from 2 to 1. 

"Mode", "Onoff", "Sensorstatus" & "Working" all remain at 1.

**Comment by krahabb** [comment]
That 'state' being ==2 when the socket is off is very exotic. There should be more to it but as for now we 'know' that only 'state'==1 means socket active (actual code just interprets that value as a bool since I expected to be 0 for off, 1 for on)

If you have the time, could you check the 'Mode' is correctly mapped to the operational modes reported in the manual?
In alpha.4 I've already mapped those and they should be:
- Mode "1": Temperature control - heat
- Mode "2": Temperature control - cool
- Mode "3": Cycle timer
- Mode "4": Countdown-on 
- Mode "5": Countdown-off
- Mode "6": Temperature schedule - heat
- Mode "7": Temperature schedule - cool

In meross_lan you could use the preset to select the device mode and the HA preset is mapped according to that table (I hope it's right).
As for HVAC modes reported in HA it's a bit tricky since the timer modes are not really HVAC 'compatible' they're not heating or cooling anything based on a setpoint. They could fall in the category HVAC mode == 'Auto' which means the control is not through the setpoint temp set in HA and that's ok (I've mapped these timed modes and the schedule modes too to HVAC mode == 'Auto')
The HVAC action reported in HA then might be confusing and I've opted for HVAC action == 'FAN' (when mode is any of the timed ones) to distinguish this from actual 'Heating' or 'Cooling' since the action is not controlled by a setpoint/schedule temperature.
The HVAC action will be 'Heating' and 'Cooling' when the device plug is active in either manual control temp or schedule temp.
One might argue that if the plug is connected to an HEATER device even the timed modes are actually HEATING but the code doesn't know for sure (you might have connected the plug to a COOLER instead)

Of course, since alpha.4 is 'bugged' in interpreting the socket state, the HVAC action reported will be failing at the moment

**Comment by electricmini** [comment]
Hi there,

I've also got one of these Meross MTS960 units (in my greenhouse as well) and have just installed Meross-LAN into HA....

If you need another beta tester, let me know (though I might need some guidance for installing the beta into HA/HACS)
