### ISSUE TITLE
Can i run meross devices completely LAN and still have them work with Alexa/Google?

### ISSUE THREAD

**Issue by Pleasant-exe** [krahabb/meross_lan#368]
I was wondering if i can still use my devices via Alexa/Google if i use my own 'private' MQTT broker? i know google/alexa usually automatically detect them along with HA but would this only work if im connected to Meross servers?

**Comment by krahabb** [comment]
Once added to HA (either they're still Meross bound or privately MQTT binded) you can control them through the Google/Alexa integration in HA exactly as every other device. I don't know what you can do at this point since I'm not using any voice assistant but I guess you should be able to manage turning on/off and light settings for example.

If you leave them Meross binded, then you can also use the Alexa/Google integration originally provided by Meross itself so you could theoretically 'reach' to them in 2 different 'paths' on the voice assistant (maybe a mess)

If you privately MQTT bind the device instead you're left with just the HA voice assistants.

Also, in the end, even if I'm totally ignorant at the moment, I would expect that newer Matter enabled devices, could/should theoretically be reached locally either by an Amazon ECO (Alexa) device or by a corresponding Google Nest Hub and now you'd have a third path for the voice assistants to get to the device (independent of HA and of Meross servers)
