### ISSUE TITLE
Can't add a 2nd device (Meross Smart Plug MSS315)

### ISSUE THREAD

**Issue by feu77** [krahabb/meross_lan#370]
## Version of the custom_component
<HA 2024.1.0>

## Configuration

```yaml

Add your logs here.

```

## Describe the bug
I can't add this device which appears through AutoDiscovery. I paste the deviceID I got from an existing garage door opener. Even with a wrong key it won't work. I've read that an recovery from the cloud should appear when entering a wrong code but nothing. The device is paired in the Meross App and is controllable via Homekit, the ip is correct.

## Debug log

<Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.meross_lan
Source: custom_components/meross_lan/helpers.py:166
Integration: Meross LAN (documentation, issues)
First occurred: 15:18:44 (4 occurrences)
Last logged: 15:23:08

Error () configuring meross device (host:192.168.2.82)>

```text

Add your logs here.

```

**Comment by krahabb** [comment]
I cannot really figure out where the issue could lie. At the moment though, the cloud profile configuration (in order to esily get the device key) is not working correctly (see #372).

Anyway, the `Error () configuring meross device (host:192.168.2.82)>` doesn't say much about the kind of error (it happens sometimes, depending on the kind of error, that the error message detail is not reported)
