### ISSUE TITLE
MSH300HK HUB disappeared from the device list

### ISSUE THREAD

**Issue by attilhacks** [krahabb/meross_lan#371]
Hello,

for some reason I disabled a smart hub wifi, the message said I could enable it again later on. I can't find  it in the devices list, not cannot add it again because apparently is already configured and I get an error

thanks

**Comment by krahabb** [comment]
Hello @attilhacks,
if you disabled the configuration (from the `meross_lan` integration page) you'll have to re-enable it and not the device.
Not sure if I got your issue right!

**Comment by attilhacks** [comment]
The integration is enabled, just can't see the disabled hub, nor adding it again because it shows already configured... 
![Screen Shot 2024-01-09 at 7 04 23 AM copy](https://github.com/krahabb/meross_lan/assets/148806174/e93a05aa-b430-455c-a569-b9720ffa996c)
![Screen Shot 2024-01-09 at 7 04 38 AM copy copy](https://github.com/krahabb/meross_lan/assets/148806174/261248a5-56e6-45c5-bda3-664ba5ef9a71)

**Comment by krahabb** [comment]
I cannot figure out the possible cause.
One thing I notice is the fact that your msh300hk only shows 1 device and 4 entities and these are likely just the hub device itself and its entities (DND, etc)

It looks like no other (sub)devices are paired to the device via the 'radio pairing'. 
What happens if you go to the device details by clicking on the highlighted '1 device' link? . You should see at least the 'DND light' entity and if so it should work.
If this is the case then I would focus on the missing subdevices, provided they are correctly radio-paired with the hub.

Also, are your devices accessible from the Meross app and how do they work there?
