### ISSUE TITLE
MSG 100 Firmware Update 4.2.12 not applicable

### ISSUE THREAD

**Issue by Rollocko** [krahabb/meross_lan#379]
Hey there.

I am getting the notification that a new firmware for my msg 100 is available. Unfortunately the Meross app doesn't show this update.
I am not able to update to 4.2.12 coming from 4.2.6. Every time I click on "Install" nothing happened. Already restarted HA several times.
Any ideas?

**Comment by krahabb** [comment]
Hello @Rollocko ,
sorry for that misleading you (and others - #363)
The 'Install' feature available is just a placeholder for the actual upgrade process and is not (yet) implemented.
Since I don't get a chance to actually test/try the upgrade process that button will disappear from the incoming version (until something new happens) so that users are not 'fooled' into thinking it could work

**Comment by Rollocko** [comment]
Thanks for the explanation.
