### ISSUE TITLE
Smart Switch (mss210)

### ISSUE THREAD

**Issue by flo2126** [krahabb/meross_lan#380]
I cant add my plug to Meross in home assistant. I got an error message that it is already exist in ha, but there is no plug in the meross integration.

What can i do here?
[home-assistant_meross_lan_2024-01-28T20-21-46.624Z.log](https://github.com/krahabb/meross_lan/files/14077601/home-assistant_meross_lan_2024-01-28T20-21-46.624Z.log)

**Comment by flo2126** [comment]
I can't remember that. What can I do now. Now it is always discovered automatically but I just can't set it up. What options do I have now?

**Comment by krahabb** [comment]
If you hit 'Configure' on the discovered item panel it should just work.
there's a bug (investigating if it's HA or meross_lan though) in which the 'discovered item' doesn't disappear until you refresh the browser or login again into HA but that doesn't prevent the correct working of the device once acknowledged.
If you'll hit 'Configure' again on the discovered item flow it will show you an error because the configuration process has already finished (just the browser UI isn't refreshed correctly)
You should anyway find the configured device in the list of meross_lan actual entries. If not, check if you're maybe hiding some 'disabled' or 'ignored' entries from the HA UI
