### ISSUE TITLE
The device of this entity is disabled.

### ISSUE THREAD

**Issue by sharkpunch5** [krahabb/meross_lan#386]
I have connected my Meross msg200 using the plugin (using 5.0 beta)

it adds all the entities and connects to the device however I cannot change the state, all of these devices are 'this device is disabled by config entry'

appears to be a bug, not sure how to fix

**Comment by krahabb** [comment]
Does it work with the latest official 'Cloudy' release?

**Comment by sharkpunch5** [comment]
i could test it as i require the update that allows for 2FA when setting up (I can roll back to the most recent version that was enabled and test?)

**Comment by sharkpunch5** [comment]
i tried to rollback to latest official and i get a different error now however the entities are still disabled
`MerossDevice(Smart Garage Door (2105266257668690851548e1e971c44b)): AttributeError('NoneType' object has no attribute 'data') in handle GETACK Appliance.GarageDoor.MultipleConfig`

**Comment by krahabb** [comment]
Yes, as in my testing, once the device appears disabled, the code is not able to recover and you have to manually disable/enable the configuration (config entry) from the meross_lan integration page.

The error you see is the only one I've discovered (and patched in beta.1) and was present since the beginning of the feature so I think it is not related (still annoying though - as said, now the beta.1 is published and fixes this)

I'm still trying to figure out where the issue lies but, since I've also seen that and then I wasn't able to reproduce it anymore, it will be hard to fix (at least at the moment :)

I'm inclined to think this issue might arise only in combination with other conditions (to me happened just when creating the device configuration - I guess it was the case for you too)

Anyway, doing the manual 'disable/enable' proved to be a solution (not a real one but...)
