### ISSUE TITLE
Using MTS200 with Powercalc

### ISSUE THREAD

**Issue by skoef** [krahabb/meross_lan#387]
## Version of the custom_component
v4.5.3

## Configuration
No additional configuration

## Describe the bug
I would like to use Powercalc to calculate the consumed power of the electric heating that is hooked up to my MTS200. I know the power the heating will draw when enabled but I can't seem to find a sensor from the integration that tells me when the MTS200 is heating and when not. I could combine those two to determine the kwh's that the heating is using.

Is this even possible with this plugin? Did anyone else succeed in doing something like this?

**Comment by krahabb** [comment]
If it works (this is by design but not sure if any bug could prevent this...) the 'hvac_action' attribute in your climate entity reflects the actual state of the device (i.e. actively heating/cooling or not) so you can just 'template-extract' this from the entity and use as a virtual toggle to drive calculations.
It could have different values though:
`off`: the mts is turned off
`idle`: the mts is turned on but not heating/cooling
`heating`: the mts is actively heating
`cooling`: if the summermode is available this could be used to indicate the mts is (actively) working in cooling mode
