### ISSUE TITLE
UNABLE TO CONNECT

### ISSUE THREAD

**Issue by TheMastro-11** [krahabb/meross_lan#389]
Error while connecting to meross account, btw from the meross app works fine.
`int([x]) -> integerint(x, base=10) -> integerConvert a number or string to an integer, or return 0 if no argumentsare given.  If x is a number, return x.__int__().  For floating pointnumbers, this truncates towards zero.If x is not a number or if base is given, then x must be a string,bytes, or bytearray instance representing an integer literal in thegiven base.  The literal can be preceded by '+' or '-' and be surroundedby whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.Base 0 means to interpret the base from the string as an integer literal.>>> int('0b100', base=0)4`

**Comment by krahabb** [comment]
Hello @TheMastro-11,
It is likely the same kind of issue as in #372,
This was fixed in some of the latest pre-release versions 'Moonlight' and it is maybe related tou your account being configured for MFA.
The cryptic error you see might be due to other reasons (the message you get is just a bug in meross_lan when trying to manage a cloud api error response)

So to fix both the bug in error handling and the full MFA support, you'd have to try the latest beta (which should be reasonably stable, at least I still haven't found any particular issue in there)

If you're already on latest beta then we might have another issue, please report the actual version so I can review that.

**Comment by TheMastro-11** [comment]
Yes It was the problem, anyway unfortunately my device doesn't work

**Comment by krahabb** [comment]
Hello @TheMastro-11,
I'm closing this to cleanup of bit of issues, but if you still have problems with the device feel free to open e specific issue for the matter (or look for similar opened issues).

Thank you
