### ISSUE TITLE
Integration missing more than 4 smart-plugs - recognises/displays 4 smartplugs, yet 8 are in DHCP and the Meross_lan config entry

### ISSUE THREAD

**Issue by pbrooks29** [krahabb/meross_lan#429]
## Version of the custom_component
"meross_lan": {
      "version": "5.0.4",
      "requirements": []
    }

## Configuration
config_entry.yaml attached.  Note there are 8 x MSS310 smart-plug devices detected in the "store" section (and 1 lamp, which it correctly detects) which I presume is downloaded from the meross app/server

Screenshot of HA Ubiquiti DHCP table showing 8 Meross smartplugs - 4 recognised by Meross integration, and 4 which are not
Screenshot of HA  device list, showing 4 plus recgnisd by Ubiquiti and Meross, and 4 others only recognised by Uniquiti.

## Describe the bug
I have 8 MSS310 smart-plugs on the network, but no matter how many times I power off or clear and re-pair the last 4, the integration only recognises the first 4. 
When I cleared all data in the integration, deleted all the devices, deleted the hub and started again, it also auto-recognised the first four from the LAN, and stopped after 4. Seems there is a problem recognising more then 4 MSS310 devices.

## Debug log
Attached debug log - includes turning one of the missing devices off, then on again 10 - 15 seconds later, to see if there are any events detected from the missing devices

```
[config_entry-meross_lan-1f051c2453a2b73c991d83679129b2ec.json.txt](https://github.com/krahabb/meross_lan/files/15156211/config_entry-meross_lan-1f051c2453a2b73c991d83679129b2ec.json.txt)
![HA devices table - 4 recognised, 4 not recognised by Meross integration](https://github.com/krahabb/meross_lan/assets/151645043/24fb8d59-a0bf-4456-8e63-528ba0c57d71)
![Meross 4smartplugs](https://github.com/krahabb/meross_lan/assets/151645043/df7d5ec7-b566-4ecb-9986-b834ce68052b)
[home-assistant_meross_lan_2024-04-30T00-21-45.849Z.log](https://github.com/krahabb/meross_lan/files/15156566/home-assistant_meross_lan_2024-04-30T00-21-45.849Z.log)

**Comment by krahabb** [comment]
It could be the unrecognized entries are due to the devices mac addresses being out of the address ranges configured in meross_lan.

You can check (and eventually edit) the `manifest.json` file in meross_lan folder and see that it filters dhcp discoveries by mac address mask(s):

```json
  "dhcp": [
    {"hostname": "*", "macaddress": "48E1E9*"},
    {"hostname": "*", "macaddress": "34298F1*"},
    {"registered_devices": true}
  ],
```

I've checked a bit of internet and seen that there's a new address range registered to Meross: `C4:E7:AE*` so I guess I should add that to the manifest too....
You could rightly check if this is the case by adding the relative entry in manifest.json and reload (restart HA)

**Comment by pbrooks29** [comment]
I did consider the MAC thing - and checked that all devices have the same MAC prefix (which is one of the prefixes in that table). They are also connected to the same VLAN with IP addresses in the same range.
Screenshot from Ubiquiti showing all the MACs and connection parameters to the LAN.
Looks like the 4 that are recognised and the 4 that are not are all identical as far as LAN connectivity and MAC ranges are concerned - so I think that isn't the issue.
![MerossLAN](https://github.com/krahabb/meross_lan/assets/151645043/eac1a6e8-d11f-4581-aec0-fe31452f030d)

**Comment by wacholderpolka** [comment]
I have the same problem. 
I had to setup my homeassistant from scratch and now only four devices (out of about 20) are recognized. I have about 16 mss710 in the network, and they do work perfectly in Homekit or Alexa. 
They also worked in Homeassistant before. The system drive failed, so I replaced the drive ans stated from scratch.

Four different devices where detected right away, but that's it, nothing else.
(Two of them are 710, one 120b and one 110)

I will try to setup manually.

**Comment by wacholderpolka** [comment]
Seems like I am able to add the devices manually by IP address. 
This is ok so I can ho on with the HA setup, but would be interesting to see, why the auto discovery failes.
Maybe too many devices :-)

**Comment by wacholderpolka** [comment]
Additional Hint: After adding a few plugs manually, some devices where discovered automatically. 
I have now all the devices setup, a little bumpy road, but it works, so many thnks for the integration and the work behind it.

**Comment by krahabb** [comment]
This is very hard to track down...I know HA DHCP component has a lot of caching/optimizations so it might get fooled somehow, meross_lan too might be buggy for the matter but, if it receives a DHCP discovery from HA core it should:
- log a warning in case of any failure
- either show you a device needing to be identified/configured (since the device key is unknown)
- or show you a device needing final acknowledge since meross_lan already knew the key
