### ISSUE TITLE
Smart plug not more available afer HA version update

### ISSUE THREAD

**Issue by robertomontinaro80** [krahabb/meross_lan#434]
## Version of the custom_component
5.0.4
## Version of Home assistant
2024.5.3

## Configuration
no yaml configuration involved for my integration

## Describe the bug
After upgrading my HA docker hub to the newst version (2024.5.3) My meross smart plug mss310h is not more available. I just see the log below.
With the oldest version 2024.5.2 everything worked fine.

## Debug log
`2024-05-13 15:02:09.811 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module inside the event loop by custom integration 'meross_lan' at custom_components/meross_lan/meross_device.py, line 472: module = import_module( (offender: /config/custom_components/meross_lan/meross_device.py, line 472: module = import_module(), please create a bug report at https://github.com/krahabb/meross_lan/issues`

**Comment by robertomontinaro80** [comment]
the logs appear continuosly as you can see in the screenshot.

![image](https://github.com/krahabb/meross_lan/assets/96392935/1a6b01c8-7857-4bc3-9fcb-9e555c6765f0)

**Comment by krahabb** [comment]
Yeah, 
this is very annoying I see since the 'offending' call is used multiple times during initialization and new HA core established this new policy where it is now actually forbidden to use that.

New meross_lan preview release already has a fix for this but, in the end, except the HA core log, this should not be a real issue since the HA core is just 'pressing' (with this scary log) to update the component asap since it will not work anymore in future releases..

See #427 for other users reporting the same log but not having any meaningful issue related.

If any, there should be some other errors/logs about other issues for the mss310 not working..

**Comment by robertomontinaro80** [comment]
So do you honk there will be soon a release of meross integration with this fix?

**Comment by krahabb** [comment]
The fix for the warning log should come in few days

**Comment by krahabb** [comment]
The new incoming release has a fix for the log warning while the issue itself looks like not being related.
Closing this down right now.
Feel free to re-open (or check for other similar issues about devices becoming unavailable which should be related) if the issue persist.
