### ISSUE TITLE
New hub around the corner: MSH450

### ISSUE THREAD

**Issue by webwude** [krahabb/meross_lan#435]
Hi.

There is currently a beta program ongoing introducing a new Ethernet based hub, MSH450.

If you like, I can share any details or log. 
Currently I don't know if it will replace MSH300 or MSH300HK or both (or neither).

Keep you posted. 
Best regards 
Michael

**Comment by krahabb** [comment]
If it gets somehow recognized in meross_lan it would be nice to start with a 'Download diagnostics'...just to inspect the features

**Comment by webwude** [comment]
Installed the hub today. It has matter on board and was not recognised by HA at all. Even trying to connect it as matter device in HA currently fails, maybe as it is already connected to meross app.

I added a water link sensor to it and it does show up in the meross app but not in HA.

I will try to remove it from meross app completely for testing but I guess then I cannot add any device to it without the Meross app.

The hub is capable to add new temperature sensors, water leak, smoke detector and door opener, ms100f, ms200, ms400 and gs559a - similar to the ms300 Homekit hub.

**Comment by krahabb** [comment]
Hello @webwude ,
Awesome! It looks as though it is the same as the wifi hub.
Does your waterLeak sensor work? the trace looks very short so it misses some dialog between the sw component and the device but the general diagnostic info's look like everything is in place

**Comment by webwude** [comment]
I think so. But I can create another diagnostic log.

**Comment by krahabb** [comment]
I don't know about Matter discovery but that has nothing to do with meross_lan.
meross_lan just uses DHCP broadcasts for local discovery but I see your component version still has the old mac group addresses and looks like Meross got a new mac address range recently (likely right for this ethernet device though).
New meross_lan release will have this new mac address mask in order to be able to detect these 'new' devices but now that you've manually added the device via IP it's no more relevant ;)

**Comment by webwude** [comment]
another log just to make sure. 
[meross_lan-7426db2431950a53a8205e480b9a1f0a-Smart Hub Matter-3eb22219e4208d5a899efbeb0cff857d(1).json](https://github.com/krahabb/meross_lan/files/15341098/meross_lan-7426db2431950a53a8205e480b9a1f0a-Smart.Hub.Matter-3eb22219e4208d5a899efbeb0cff857d.1.json)

**Comment by krahabb** [comment]
There's a lot of new stuff but it's meaning is obscure at the moment.
All in all, the current implemented features for msh300 hubs seems to work the same way. I should try to better understand those 
 other new features in order to be prepared for future behaviors but I'm confident this should work fine at least with the range of currently implemented subDevices like mts100/150, smoke sensor, waterLeak, temp/humidity and so on.

As a final step you should test if the water leak sensor in HA reports correct values (as compared to what's in Meross App) since I don't remember if current implementation was confirmed to work. No need for diagnostic traces or so...just check if the states you see are aligned to what the sensor should report

**Comment by webwude** [comment]
Looks good. I just tested it.

![Screenshot_20240518-110813](https://github.com/krahabb/meross_lan/assets/7056632/ee8b53f9-2ff4-44af-bada-477a78df6a66)
