### ISSUE TITLE
Custom entity names are being reverted with version 5.1.0

### ISSUE THREAD

**Issue by andyblac** [krahabb/meross_lan#441]
If you set a custom entity name, for a switch it gets reverted to default after a day or so.

version: 5.1.0

**Comment by andyblac** [comment]
as @stevemcan changing the switch entity names, after a while it seems to sync back with actual device, but there is no way to change the switch. names in the Meross App.

**Comment by stevemcan** [comment]
Just updated to the latest core update and names have reverted to default again.

**Comment by madasus** [comment]
I'm also seeing this on v5.1 on my MSG200 devices

**Comment by andyblac** [comment]
update, after disabling the cloud part of the integration the switch names have stoped syncing to device names.

<img width="1060" alt="Screenshot 2024-05-28 at 21 09 49" src="https://github.com/krahabb/meross_lan/assets/77936/4a9cad14-573f-4146-b8b8-e09bbb27d523">

**Comment by krahabb** [comment]
That's interesting..I'll check why HA core doesn't preserve entity customizations when meross_lan updates the device name.
In case, I'll add an option to the cloud profile to disable Meross cloud device name sync

**Comment by krahabb** [comment]
> Nothing has changed on entities name management...surely nothing which could interfere with HA entity customizations. Do you refer to the single entity name or to the device name?
> 

This is not totally true (blame on me..)
5.1.0 introduced cloud synchronization for device 'channels' which are typically mapped to some entities in meross_lan.
This feature depends on the kind of device and surely mines do not expose the issue since they don't have 'cloud channels names' in their cloud database....
The fault is on myself anyway since I've mapped this update to what I thought would have been the 'default entity name' (and so always anyway overriden when users customize the entity name) but I was fooled by HA api which named these parameter with a different  convention with respect with what I've learned from device name updates.

Fix is incoming though..just 1 question in order to see if everything else is in place:
Is the name value overwriting your custom entity name the same as defined in the Meross app for that same channel? (It should be like this since I'm copying over the device cloud definition)

**Comment by andyblac** [comment]
> Fix is incoming though..just 1 question in order to see if everything else is in place: Is the name value overwriting your custom entity name the same as defined in the Meross app for that same channel? (It should be like this since I'm copying over the device cloud definition)

yes. if I change the switch name to `Lounge Charger`, when sync occurs this Is replaced by `Switch 1`, which is what the switch is called the Meross App, the field is not `Empty` with the name as `Switch 1` which it would be if it was default name, but it actually has the text in the field.

Hope that makes sense.

**Comment by madasus** [comment]
I'm still having this problem on 5.2.1

My MSG200's show a single garage door until the door is cycled and then it adds another entity.  The other entity seems to always show as open as well.

![image](https://github.com/krahabb/meross_lan/assets/9310056/331425e4-eb5e-4116-8a1a-5c2708c635bf)

**Comment by krahabb** [comment]
Hello @madasus,
I don't get if this is the same kind of issue as per this thread...
The 'added' garage looks like related to #428 where these (new?) msg200 firmware publishes info for an extra channel (at index 0) which looks like non-sense of course but meross_lan cannot really ensure this is a fake channel or not...

I suggest you to just disable the entity in HA so that it'll not hurts while I see for a reasonable workaround (not that I didn't think about it but any solution might be worse than the issue itself...)
