### ISSUE TITLE
Meross Lan integration with Meross Cloud iot

### ISSUE THREAD

**Issue by xvolte** [krahabb/meross_lan#46]
Hello,

I do use Meross Cloud since a lot of time.
However, there are more and more issues with some "random" errors, saying the devices are "unavailable" from time to time... a full reboot resolves this, but it is painful, especially with automation.

So i wanted to try this module, but i don't understand how to configure it, when i installed the repo through HACS.
if i go on "integration", i can add the installed module, but it is asking for information that i don't have (key + device ip address)

My question is : Is it compatible with Meross Cloud IOT, or Should i select only one of them?

thanks in advance,

**Comment by krahabb** [comment]
Hello @xvolte,
Sure this integration is 'compatible' since you can have both running on the same Home Assistant and talking to the same devices. The two integrations will just communicate over different 'channels'.
The Meross Cloud integration is actually talking to the Meross official infrastructure so it works like if it was the Meross app 'side by side'
Meross LAN instead will talk directly to the device in LAN only mode and will use HTTP to do this. You have to look for the actual  IP of the device as per how it is configured in your LAN (probably through DHCP on your router). 
Anyway, given 'some time', the device should be discovered automatically by Home Assistant through its own dhcp integration and so you'll just have to confirm the device entry discovered this way.
The 'device key' is a secret key which is used by the official Meross protocol in order to be able to talk to your own devices (it works like a 'password' in some ways). Your devices configured through the Meross App with your Meross account will be assigned all the same key but this key is a little hard to recover (see #43 ).
If you're in luck (and 99% of users are) this key is not needed for meross_lan and you can leave it empty so my software will try to hack the protocol and should be able to communicate anyway (unless you fall in #43 )

Good luck!
