### ISSUE TITLE
Multiple Macs

### ISSUE THREAD

**Issue by mschingel** [krahabb/meross_lan#460]
https://ibb.co/4fb2M1H Here is a picture of what I am researching.

How do I fix the multiple MACs
![Screenshot 2024-06-16 102729](https://github.com/krahabb/meross_lan/assets/109315303/05908840-0c9a-40c7-9398-f3c237db1547)

**Comment by krahabb** [comment]
I can't say for sure but this could be related to #341.
In short, it happened (before the related fix dating back to Cloudy.5 - v4.5.xxx) that if you had multiple 'similar' devices on LAN, and these were 'exchanging' their IP addresses without HA/meross_lan being updated of the change, that meross_lan wouldn't be able to detect the 'mismatch' and so was starting to communicate with a device which was different from the originally configured.
This led to serious misconfiguration, one of the effects (one of the less problematic though) was the device appearing as having multiple MACS. This was fixed so that it shouldnt happen anymore after the fix, but the 'dirty configuration' polluted the HA core device registry and that's a bit unfixable in code (it would really be too dangerous to try automatically fix a possibly random situation).

The only option left is to manually edit the `core.device_registry` file into the `.storage` folder in HA config dir. It should be pretty easy to manually edit and fix it, with the only issue that this file might be huge (more or less) and so a bit 'hard to deal with'.
You should find a way to search for the correct device entry in there and then remove the wrong mac address mapping. save. restart HA

As usual, a temporary backup of the file before any modification could save your life should your edit go wrong.

The other way would be to remove the configuration of the device (from meross_lan) and then re-configure it.
