### ISSUE TITLE
Show renamed names instead of "cryptic" ones in Integrations

### ISSUE THREAD

**Issue by almico** [krahabb/meross_lan#47]
**Is your feature request related to a problem? Please describe.**
I started using Meross LAN "in production" 🥰 and this is what I see in Integrations page:
![image](https://user-images.githubusercontent.com/15247405/127641829-2c9dfecf-1fd6-4a87-89da-825f112a5436.png)

![image](https://user-images.githubusercontent.com/15247405/127641882-32b6b6f1-efa0-4430-8f4c-89c4ac9bb595.png)

But I already renamed that device to:
![image](https://user-images.githubusercontent.com/15247405/127642002-284b44d9-9642-4e6a-8a4d-e84f1e878758.png)

**Describe the solution you'd like**
I would really love to see "Presa studio (via LAN)" instead of "mss310r 19122468131046908074...".

**Comment by krahabb** [comment]
Hehe,
well..doable..but in logic terms it would not be correct since the integration itself is a different concept than the device or even the entities it carries: it's just a configuration container.
Of course, in meross_lan we always (not really sure) have 1 integration <-> 1 device so the mapping could be always 'deterministic' but I'm not really motivated to enforce that because, like I said, they're two different concepts (and also because retrieving and updating the integration entry name might be easier said than done)
At any rate, you can edit it manually from the integration(s) UI  ;)

**Comment by almico** [comment]
I fully understand 😃
