### ISSUE TITLE
Support for MS130 sensor

### ISSUE THREAD

**Issue by HeikoTietze** [krahabb/meross_lan#478]
https://www.meross.com/en-gc/smart-sensor/thermohygrometer/174

The gadget shows up as "tempHumi (1A00694ACBC7)" but lists only the sensor Battery and the configuration Togglex.

**Comment by krahabb** [comment]
Hello @HeikoTietze,
I would need the 'Download diagnostics' for the device in order to better understand its characteristics

**Comment by HeikoTietze** [comment]
[meross_lan-dd57d95b97da35a8f75df9fc4eed7198-tempHumi (1A00694ACBC7).json.txt.zip](https://github.com/user-attachments/files/16409812/meross_lan-dd57d95b97da35a8f75df9fc4eed7198-tempHumi.1A00694ACBC7.json.txt.zip)

**Comment by krahabb** [comment]
Hello @HeikoTietze,
The feature should be working on current pre-release (5.3.1-alpha.2). I'm not sure when I'll be able to publish a stable release but, even if the name contains 'alpha', it should be as reliable as the latest official.

**Comment by HeikoTietze** [comment]
Awesome! That's why I love open source. Works like a charm, thanks a lot.

(The app shows a couple more infos like illumination; not of much interest to me.)

**Comment by HeikoTietze** [comment]
The sensor reports somewhat random nonsense values or undefined. Not sure who is to blame for this, I'll keep the issue closed. The log is at https://pastebin.com/XZq6N63J

**Comment by krahabb** [comment]
The trace itself is not showing anything unexpected..do you also maybe have some warnings in general HA log?

**Comment by HeikoTietze** [comment]
This illustrates what I mean: https://imgur.com/a/Nc911kf - Blue: MS130, Red: MS100 (on a another hub; which has a usually varying signal strength, to pick one attribute)

**Comment by krahabb** [comment]
I think I got it...I forgot to setup proper polling...

**Comment by krahabb** [comment]
After better checking, polling should be just fine (it follows the same rules as for ms100) but this device is slightly different and I've found another message in your latest diagnostics where the sensors data are pushed (together with light sensor level).
I'll add parsing for this 'special' message too even if it'll take some time since this new message has a slightly different layout than usual.
In the meantime, I'd ask you to set the protocol to 'fixed' HTTP in related hub configuration just as a test. I see you have cloud mqtt config in place and this leads to a whole set of 'optimizations' in polling (basically skipping most of the polls and relying on MQTT pushes for status updates). This way, forcing the meross_lan device to operate only on HTTP, the polls should be more predictable and we could see if the sensors are better sampled.

**Comment by krahabb** [comment]
I've published a new pre-release with handling for the message which carries the 'light' sensor value. It might be this message (carrying light/temp/humi)  is automatically sent by the device when any sensor value changes and so this might also fix the delays observed in temp/humi updates.
As for now, the light sensor value is reported 'raw' since I have no clue which scale (nor the unit) it has.

**Comment by HeikoTietze** [comment]
It's measured in lux and the reported value is the same as in the app. I'll monitor the status for the next hours, but everything looks good on the first glance.

**Comment by HeikoTietze** [comment]
Reasonable data, consistent with the app. Thanks a lot!
