### ISSUE TITLE
Change the email account registered in the meross lan integration

### ISSUE THREAD

**Issue by SmartHome-AIG** [krahabb/meross_lan#489]
Good evening.
I have been using Meross-LAN for a long time. Recently I decided to change the email account with which I registered the integration. My question is, can I change/how can I change that parameter without having to reset all entities?

Thanks in advance.
Great job.

Regards,
Alberto.

**Comment by krahabb** [comment]
If you mean you've changed your Meross account registration email then you could just remove the configuration for the Meross cloud profile and setup the new one (changing email address for a configured one is not supported).

Removing that cloud account profile from meross_lan (without removing any configured device) will just 'break' cloud connectivity.
Once reconfigured, if the devices are the same in the new cloud account (I mean the internal cloud account identifier didn't change when you changed the email address - but this is 'Meross account policy details' which I don't know...), cloud connectivity should work again.

Since I didn't test the procedure I eventually suggest you to backup HA before proceeding (standard safety policy;) but I'm sure the devices configuration will not be removed when just removing the cloud profile.

**Comment by SmartHome-AIG** [comment]
Good afternoon.

Everything went well.
I did what you suggested, I deleted the Meross LAN account, the item where the old email account appeared. Then I added it again, but this time with the new credentials. Now I have all my devices working correctly again.

As a curiosity:
The only strange thing (but that for the moment is not affecting anything) is that within the Meross LAN integration, where the email is displayed, below it it says "No devices or entities".

Thanks for all the help.

Regards,
Alberto.

**Comment by krahabb** [comment]
Hello Alberto,
The 'no devices or entities' is because I preferred to keep the devices linked to their own configuration instead of linking them to the cloud profile. It would be possible in HA to have a device linked to multiple entries and so I could also link every configured device to its cloud profile but, that would complicate keeping those links updated since this link is very 'light' in meross_lan as you experienced by totally removing the cloud profile and having no issue with the devices config.

In the development process the cloud profile appeared very late and it has 2 main purposes:
- provide every configured device the ability to reach the cloud MQTT broker. This works as an 'extra configuration' for the device and is obviously shared by the cloud profile entry among all of the devices linked to the same cloud account (keep in mind you can add multiple devices in `meross_lan` from different accounts or even devices which are 'locally binded' i.e. have no cloud connection at all).
- provide a way to discover/connect (cloud) devices through the registered account. This means you could also discover/access devices which would be not locally reachable by any other mean (say they stay in a different home for example).

Nevertheless, if you enable diagnostics in the meross cloud profile you would see some sensors (likely only 1) with the state of the cloud connection(s)
