### ISSUE TITLE
Add temperature entity to TRVs

### ISSUE THREAD

**Issue by almico** [krahabb/meross_lan#49]
**Is your feature request related to a problem? Please describe.**
These are the entities I see for my TRV using Meross LAN:
![image](https://user-images.githubusercontent.com/15247405/127651776-c93ba574-03f3-479c-9853-7cfa07a4ae16.png)

**Describe the solution you'd like**
I would really love to see the following additional one (the "current" temperature):
![image](https://user-images.githubusercontent.com/15247405/127651694-e7496694-dd91-45bc-a2c0-d0bb99e1ae1d.png)

**Comment by krahabb** [comment]
Hey @almico ,
I was thinking about that too and right now I prefer to not automatically create that entity since in HA you could easily add a template sensor entity 'extracting' the actual temperature from the climate entity representing the mts100.
The 'actual temperature' is a common property of climate entities and so I guess the typical HA user is comfortable with that and, if not, has already implemented its own template sensor extracting the temperature value so, in the end, for meross_lan would be the same:
- you either like seeing the temperature 'inside' the climate entity
- you don't like it and you build template sensors for all of your climates

Still might be easier to have the sensor already in place (so to not write templates) but I'm sure it would not fit all of the users and (I guess) most of them would see it like a duplicate.

We'll see..I'm not totally against it...

**Comment by almico** [comment]
I understand your point of view, but I think the immediate availability of the plain "current" temperature would be highly beneficial to the casual user, while the advanced one shouldn't see it as an issue to have to simply "disable" it.

**Comment by krahabb** [comment]
This is coming in the next release due in a couple of hours (maybe days :)
