### ISSUE TITLE
Document how to migrate from "trick" to "MQTT" mode

### ISSUE THREAD

**Issue by almico** [krahabb/meross_lan#50]
Since Meross has been heavily limiting API access, I decided to pull the plug and move to Meross LAN for my production environment, and it is working very well. In a few months we'll see how it works with TRVs, but, in the meantime (it's summer here), I can use it to see TRV temperatures and control a light bulb.
I didn't configure my devices to use MQTT, thus, as far as I understood, I'm leveraging the "flaw" in Meross protocol, and it is working great.
Now the question: what will happen when Meross will update the firmwares and, eventually, fix this flaw? I will be forced to configure them all for MQTT.
How difficult will the migration be?
Might it be useful if you write some document about it?

**Comment by krahabb** [comment]
Hey @almico,
If Meross would 'fix' this, you could still use the devices in their original 'pairing' with Meross. You'd just need to know the key in order for the http protocol to work correctly (#40) and still use them with meross_lan.
Pairing the devices to your own MQTT environment is a different story. The process is neither easy nor hard: it works but you'll need a good preparation setting up the correct environment and re-pairing all the devices. It works both with HASSIO mqtt addon and with a 'raw' MOSQUITTO server (this one would need to be setup carefully with certificates, ports, authentication so that's a lot of stuff).
Pairing with your MQTT doesn't free you from the key: you just know it since when you re-pair your devices you set the key in configuration and so you can use it in meross_lan too.

I suggest you to slowly plan and try some testing with just one meross device: you first setup your MQTT environment (I guess HASSIO MQTT addon is the best option in order to keep your HA installation the more 'streamlined') and then re-pair the device and then check it really works. It could be a little pain (or not) but you'll see. Maybe it's easier done than said.

Bear in mind that:
- putting Meross devices in your MQTT environment will isolate them from the cloud (good or not)
- you'll have 'instant' updates of devices state
- you'll 'loose' firmware updates (but you can just disable automatic device updates inside the Meross app)
- you'll loose the option to control your devices from another platform (so for instance if your HA is not working/reachable you can't use the device from the Meross app anymore)
- you can still go back at any time and re-pair the device with the Meross App ;)

**Comment by krahabb** [comment]
Hey @almico, I'll close this down: there's an excellent guide [here](https://github.com/krahabb/meross_lan/discussions/63) and looks like the last HA mosquitto addon is working good now
