### ISSUE TITLE
Finding other MAC address

### ISSUE THREAD

**Issue by kanda-robotics** [krahabb/meross_lan#60]
I have some Meross devices which has different MAC address.
The MAC address is "34:29:8f:xx:xx:xx".

So I modified "merossclient/const.py".
`#MANUFACTURER = "Meross"`
`MANUFACTURER = "Sandemarine"`
`#MEROSS_MACADDRESS = '48:e1:e9:xx:xx:xx'`
`MEROSS_MACADDRESS = '34:29:8f:xx:xx:xx'`

And also "manifest.json"
`  "dhcp": [{"hostname": "*", "macaddress": "48E1E9*"},{"hostname": "*", "macaddress": "34298F*"}],`

I have successfully added a device and device works properly.

I would like to find multiple MAC addresses at same time.

**Comment by krahabb** [comment]
Well!
Thank you @kanda-robotics,
the consts are just used as placeholders so they don't really have any code impact (except as labels reported to UI here and there)

I'll add the MAC mask to the 'official' manifest.json in the upcoming release. Do you have any more insights about the device/manufacturer? is it a kind of clone ?
I've googled a bit and seen Sandemarine being a supplier of 'marine stuff' do they actually sell rebranded meross devices ?
I've seen this OUI assignments browsing around:
34298F1 -> Chengdu Meross Technology....
34298F8 -> Nanjing Sandemarine....
detailed link here : https://www.adminsub.net/mac-address-finder/34298f
By the look of it we should add a better filtering MAC mask to the manifest since 34298F* comprises other manufacturers as well.
What's your idea?

**Comment by kanda-robotics** [comment]
I double checked my devices.
My devices are "34298F1". Which means it is not Sandemarine. 

I'm sorry for that.
Also I was relieved that it wasn't clone.

**Comment by krahabb** [comment]
:)
I'll update the manifest with this last then!
