### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by drako86** [krahabb/meross_lan#64]
I have this error in log 

MerossDevice(2010231560181590832548e1e938aa98) has incorrect timestamp

Solution ???

**Comment by krahabb** [comment]
Hello @drako86 ,
that's a warning, something to be aware, not really an error. It means your devices have no option to correctly set their timestamp and that could possibly cause issues (mss310 energy metering for instance). Some other devices might work correctly but still, this is a warning something could be broken.
The log itself should repeat every 24 hours and I see this could be annoying.
Meross devices usually contact an NTP service at boot (and maybe later on too) in order to get correct timestamps. If they're insulated/firewalled you could consider allowing NTP traffic from them to the outside world, else, don't bother the warning.
I don't really know which servers they use (a quick google could give a response tho); in my own LAN I've just opened outbound UDP dest port 123 and they correctly sync their time. Beware: HA too need to be time synced else the check would fail because of HA and not the Meross ;)

**Comment by drako86** [comment]
Thank you so much, I will check ^^
