### ISSUE TITLE
Accidentally clicked "Ignore"

### ISSUE THREAD

**Issue by CTJohnK** [krahabb/meross_lan#70]
Latest version. I accidentally Ignored the new Meross device and now I cannot add it.

What do I need to do to get the device loaded?

**Comment by krahabb** [comment]
Hello @CTJohnK ,
If it's only 'ignored' you can just enter the Integrations page and, in the top right corner click on the 'filtering menu' (kind of triangle-burger). Here you can show the ignored and disable dintegrations.

Hint (when started using HA this bugged me a lot!): 
HA pages for Integrations, Device, Entities, by default will show you a subset of all of the items (for example disabled ones are never showed by default). If you can't find an item it is probably just filtered out by the view

**Comment by CTJohnK** [comment]
Unfortunately, it is not there and I've disconnected the plug for over an hour and even forced a different IP for it, but it has not been rediscovered.

**Comment by krahabb** [comment]
If you know the IP you can manually add the device by adding the meross_lan integration the usual way from the HA Integrations UI.

I need a bit of context to try figure out what is going on:
- Is the device still paired to official Meross cloud or did you re-pair it to your private MQTT broker?
- Which HA installation is ? HASSIO (or any other dockerized setup) or core on python/venv?. This could be important to understand why (DHCP) discovery is not working (even tho it worked before so it just adds up to mistery)

Also, the definitive help might come from enabling debug logging in HA for meross_lan. 
In configuration.yaml add this and restart:
```
logger:
  default: info
  logs:
    custom_components.meross_lan: debug
```
After restarting HA try unplug/replug the device and wait like 2 minutes then check if any relevant message shows up in the HA log. Remember to disable logging after testing since it could be very verbose depending on how many meross_lan devices you have. This test should be done before manually adding the device in 'Integrations' else the discovery process would behave a bit differently.

Thank you

**Comment by CTJohnK** [comment]
Sorry, im a little confused.
I don't see a way to manually add the plug via the HA UI. I presume you mean via your Integration UI, but I don't see a way to do this.

Also, the tracing seems to be by device and without seeing the device I cannot turn tracing on for it.

Lastly, I thought I had mentioned, but I didn't, I'm using http, not mqtt.

**Comment by CTJohnK** [comment]
I did a little poking around with Agent Ransack within the 'config' directory and I did find an entry for the plug in "core.device_registry" and "core.entity_registry", but not in "core.config_entries", by searching for the MAC address.  All three have entries for the other plugs.

**Comment by CTJohnK** [comment]
I removed the entry from "core.device_registry" (probably not the best idea, but I did make a backup first), unplugged the plug, rebooted HA, made sure the device no longer showed on my network, then plugged it back in.  I went into HA Integration and the device appeared and was waiting to be configured.

**Comment by krahabb** [comment]
The entry in device_registry could be due to other integrations discoverying and configuring the device: for example some 'router' integration could do this (I have fritzbox integration and the device gets 'tracked' from that). In HA a single device could be bound to different integrations if they register it by the same unique_id (which could be the case since meross_lan identifies devices by MAC and so do other integrations).
This shouldnt be an issue unless some 'logic' (could be a bug or could be intended I don't know) prevents other integrations to correctly setup the device. You can check this by inspecting your 'Devices' tab in HA Configuration taking care of showing also the 'disabled' ones. If it appears that the very same device/ip is disabled try to enable it. My FritzLan integration by default configures all of the LAN devices/ips as disabled until you explicitly enable one.

I think the DHCP builtin discovery could automatically discard devices (by MAC) which are already configured in HA but this is only a guess. This way, explicitly enabling the device, shouldnt change anything.

Beside that you can manually configure meross_lan this way:
- go to HA 'Configuration' -> 'Integrations'
- click on 'ADD INTEGRATION' from the bottom right
- type or search 'meross_lan' and select it from the list of available integrations
- now it could happen you're given the 'Meross LAN MQTT Hub' config entry. This is the first entry you manually configure if you have also MQTT integration in your HA. This is an 'helper' config which is able to discover devices over MQTT. In case just hit submit and let it go. If you don't have any MQTT integration you shouldnt be asked for this one.
- If you had to setup the 'Meross LAN MQTT Hub' repeat adding 'meross_lan' integration in the 'Integrations' page.
- Now, when the config entry panel shows up, you are asked for device address/ip and device key. Fill in the address and let the 'key' field empty and see if it correctly detects/configure your device.
- If not will follow up ;)

**Comment by CTJohnK** [comment]
Ah!  I didn't think to 're-add' the integration, I'll keep that in mind for the future.

As it stands, removing that entry, rebooting and plugging the plug back in did the trick, I now have it configured and added to Lovelace.

Thank you for the information and thank you for the Integration.  I got into trouble recently with the other Meross integration tool when my son was trying to get the Meross bulb colors setup for the coming holidays.  He made way too many requests trying to get the color he was looking for and that triggered Meross to shut down that integration.

Any new Meross products we purchase are HomeKit compatible and we're using the HomeKit controller integration with HA.

Again, thank you.
