### ISSUE TITLE
Cannot add device manually

### ISSUE THREAD

**Issue by dsimoes** [krahabb/meross_lan#76]
## Version of the custom_component
2.2.1

## Configuration

```yaml

Default

```

## Describe the bug
I did a fresh install using HACS of the latest 2.2.1.
Once restarted, 2 of my devices appeared to configure and work great.
But I have additional devices on another network using a VPN tunnel that I would like to connect providing the IP Address.
Documentation says: 'You can also manually add your device by adding a new integration entry and providing the host address.'
But where can I do this? When i try to add the integration manually It won't show up.
Did I miss something?

## Debug log

```text

None

```

**Comment by krahabb** [comment]
Hello @dsimoes ,
If you tried to add 'meross_lan:' to your configuration.yaml that doesn't work since setup is done only through the UI.
From the 'Configuration'->'Integrations' page in HA click 'add-integration' and search for meross_lan.
Then you'll either proposed an 'MQTT Hub' entry (if your HA has mqtt configured) or a 'manual ip' entry.
If you get the former just add it (it is used to configure the general mqtt pub/sub interface for meross_lan) and forget it, then add again meross_lan. This time you'll get the manual ip entry configuration UI.
Repeat for every device

**Comment by dsimoes** [comment]
Hello @krahabb,

Apologies! I swear last night I was checking the add integration and the meross_lan wasn't there. Even after multiple restarts of HA. I was assuming it was by design auto discover and that's it.
But this morning it appeared. So now I can add it manually. 

If you don't mind me asking, how does meross_lan can auto detect (discover) the devices without the cloud access? My devices are even on a separate VLAN than the one HA resides. I'm quite curious on which protocol allowed this discovery.

Thanks again!

**Comment by krahabb** [comment]
>Apologies! I swear last night I was checking the add integration and the meross_lan wasn't there. Even after multiple restarts of >HA. I was assuming it was by design auto discover and that's it.
>But this morning it appeared. So now I can add it manually.

Ohh maybe it is because the frontend caches a lot of things so you sometimes have to refresh the browser to make things update
It happens to me too: sometimes strings or stuff is not updating until I manually refresh the browser window

meross_lan uses the HA own dhcp integration to discover Meross devices. So, if your HA istance is receiving DHCP traffic (which is usually broadcasted over the local LAN) it can discover devices by either mac address (every manufacturer has its 'own' well known address range) or by network name. meross_lan then uses a mac address 'mask' to detect if a device appearing on your LAN is a Meross device or not and then act accordingly (this is done by dhcp integration anyway which then 'forwards' the 'possibly interesting device' to meross_lan)

This is the standard behaviour. As per why devices from a separate VLAN were detected that is likely due to your router 'advertising' on the LAN new dhcp leases coming from the VLAN but this is a guess I'm not too much into 
 this implementations/features

**Comment by dsimoes** [comment]
Thanks for the explanation. Yes, indeed the DHCP Server is also configured for each vlan but clearly it's passing information between them. I will investigate that ;)

Closing this issue. It's working perfectly so far.

**Comment by marcovtwout** [comment]
@krahabb 
> (..) If you get the former just add it (it is used to configure the general mqtt pub/sub interface for meross_lan) and forget it, then add again meross_lan. This time you'll get the manual ip entry configuration UI.

I got stuck here until I found this explanation by accident while searching the issue tracker. Could this be described more clearly in the documentation or made more intuitive somehow?

**Comment by krahabb** [comment]
Hello @marcovtwout ,
I've just added a note to review the docs for this and other issues. Thank you for signaling this should/could be clarified
