### ISSUE TITLE
MSS510x 3.2.2 Firmware appears to have broken Meross_LAN

### ISSUE THREAD

**Issue by CTJohnK** [krahabb/meross_lan#83]
## Version of the custom_component
--> v2.2.1

## Configuration
Nothing specific to Meross_LAN is configured here.

## Describe the bug
A family member with the Meross app on their phone thought they would be nice and updated the three MSS510x switches for me yesterday.  The three switches no longer respond to the Meross_LAN integration, but they do respond to the app as well as the other Meross HA cloud based integration.

The devices do appear on the network (their IP addresses are fixed) and are now at Firmware version 3.2.2 with Hardware version 3.0.0.  I attempted to change the "version" tag in core.config_entries from 3.1.5 to 3.2.2, but after a HA reboot, the issue persisted.  I then removed one of the switches from the integration and tried to manually add it back, however the response in the UI is "Unable to connect".

I am not using MQTT.

## Debug log
The trace below is from one of the remaining MSS510x switches.
[mss510x-1632057737.csv](https://github.com/krahabb/meross_lan/files/7192147/mss510x-1632057737.csv)
`

**Comment by krahabb** [comment]
Hello @CTJohnK ,
From this and other reports so far I guess the issue lies in the key-hack implemented in my code (I'm just speculating...and hoping)
Newer firmwares are likely closing on this so you just have to reconfigure meross_lan to use the proper key.
The new release 2.3.1 addresses this 'emergent' behaviour by streamlining the configuration phase with better error handling and giving you the option to 'fetch' the device key automatically by querying your meross accont cloud configuration.
If not, try it and please report here so we'll have a maybe better picture

**Comment by CTJohnK** [comment]
Ah, I thought the new release was specific for MQTT.  Will give it a try and report back.

**Comment by CTJohnK** [comment]
Interesting.  I didn't update to 2.3.1 yet, but when I logged back into HA, there was a message about a new device found at it is the one I had removed.

**Comment by CTJohnK** [comment]
Upgraded to 2.3.1, restarted HA, tried to manually add the switch, but no luck.  I presume if the integration is going to hit the cloud account, it needs credentials, etc but I don't see anything in the documentation for it.  It could also be Sunday and I'm "weekend blind".

**Comment by krahabb** [comment]
yes,
when you setup address and key, the integration tries to identify the device and ensure everything is ok.
At this stage, if the key is wrong it will show you the error in the HA form. The warning message also 'hints' you to submit again without touching the configuration in order to enter the key retrieval form. If you edit any it will retry the identification and so you will likely 'stall' on the error unless you type in the exact key.
If the setup form doesn't tell you it's an invalid key then we might be f...d ;)

**Comment by krahabb** [comment]
> yes,

I meant: yes you have to provide credentials ::::))))

**Comment by CTJohnK** [comment]
Sorry for what I'm sure is a foolish question, but where do I put those credentials?

**Comment by krahabb** [comment]
Haha..it's not a foolish question! it just tells me my UI is not self explanatory enough!
Don't worry..here's the flow to get to the credentials form:
When you enter address and key and try SUBMIT you likely get an error (a red text in the upper part of the form stating the reason)
if the error says 'invalid key' just hit SUBMIT again (the text should also hint you to proceed again) without touching the address or key.
At this point you'll be prompted with login/password for meross cloud account.

**Comment by CTJohnK** [comment]
Well the problem is I only get the "Unable to connect" error.

**Comment by analogmonster** [comment]
I would just like to agree with @CTJohnK that I don't seem to get the expected behaviour.  I have an entry for Meross LAN MQTT hub.  I click configure, I get a message asking for hardware key which I leave blank and click submit - option successfully saved.  I go to add a new Meross LAN integration and it asks for device host address and device key.  I provide a host address but no key - submit, unable to connect message, submit again, same message.  No cloud login prompt

**Comment by krahabb** [comment]
> Well the problem is I only get the "Unable to connect" error.

That explains a lot and scares a bit
I'd need need some detailed logs to understand what is happening behind the scenes.
To start with, a simple warning should anyway being logged in HA stating the reason behind the 'unable to connect'.
Also, you (both) could try providing a random key and see if the flow follows to the correct key retrieval form.
Putting a 'blank' key in configuration will enable a key hack algorithm wich maybe is 'falling apart'.
If you instead set an explicit key I hope the device will kindly report the protocol key error so my code is able to follow up

**Comment by CTJohnK** [comment]
So, I put a short code in and submitted twice, the second time I was promoted to enter my credentials.So, have the switch I deleted added back now.Thanks for your help!

**Comment by krahabb** [comment]
So did it work with the key retrieved from the cloud?
That would be awesome and confirm newer Meross firmwares are just closing in on the key hack and not anything else

**Comment by CTJohnK** [comment]
Yes, after I put in a short string and clicked Submit a couple of times, I was promoted for user/password and then the entity created with what I presume is the Meross id.

**Comment by CTJohnK** [comment]
I've updated the other two switches and everything is working again.

**Comment by analogmonster** [comment]
Same here thanks
