### ISSUE TITLE
Device Already configured

### ISSUE THREAD

**Issue by matfil92** [krahabb/meross_lan#88]
Hi,
I've successfully installed Meross LAN component with various devices.
All works correctly but yesterday I've tried to remove one entities of smart plug and now, also if I've reset it, if I try to setup it again I correctly see in Meross APP but in home assistant they will find it correctly but if I try to add it I've an error that said "Device Already configure"

How can I solve it? 

![image](https://user-images.githubusercontent.com/63936349/134337001-c8db563c-d18b-4f2a-9a8d-6edff6ffdcdf.png)

**Comment by krahabb** [comment]
Hello @matfil92,
Maybe there's an 'ignored' version of the config entry hidden behind or in a 'disabled' state.
You can check from the top right corner of the Integrations page if it's hidden (by default) by HA and regain acces to it.
If you're absolutely sure there are no other hidden configured devices/entries and still it shows you this error you might try restart HA: usually this is a consequence of an 'inconsistent' state which gets resolved only by rebooting HA. It might happen some 'disable' or 'remove' operations are not carried out cleanly maybe for transient errors or for permanent bugs (hard to identify because they really depends on a lot of factors). Rebooting is the easiest fix.
Just be sure the entry is not still there disabled or ignored

**Comment by krahabb** [comment]
I assume this issue is not actual anymore ;)

**Comment by davisgoodman** [comment]
@krahabb I'm seeing this issue still with one of my Smart_Plugs. I've looked through all the disabled/hidden entities/configs and can't find the ip reporting to be already configured. Is there a file where the devices are listed I could look through?

That is the last of my smart plug that needs to be added. All the others went really well.
![image](https://user-images.githubusercontent.com/37666918/173191092-3f0a4a8b-0daf-4201-be60-953fcd04c190.png)

**Comment by krahabb** [comment]
The 'Device is already configured' error comes from another 'config_entry' (integration configuration entry) having the same 'unique_id' as the one you're adding. These 'config_entries' are stored in plain json format under .homeassistant/.storage/core.config_entries. (This file contains all of your integrations configurations: beware when manually editing it)
meross_lan initially uses the MAC address as unique_id when devices are discovered by DHCP but, when the configuration is being finalized and you have set the correct key (thus allowing a complete identification of the device) this unique_id is set according to the 'meross device UUID' which should be unique too (like the MAC).
Still can't get where this mess comes from and I'm sorry for that but you can try manually inspecting that 'core.config_entries' file looking for all the 'meross_lan' entries and isolate the offending one (i.e. the one you're sure is not related to any of your working devices).
Editing the file as I said might be dangerous if you break the json layout. As usual a good backup copy might be handy. Also, I guess it would be safer to stop HA before editing the file so it could then restart on a clean configuration.

I guess it would be nice to have the device UUID of this newly added conflicting device so you could look straight for that value in the config file but, as of now, there's no easy way to expose that. I'm looking forward to show this field information on the configuration form for the next release so it could help digging into the issue.
