### ISSUE TITLE
Both my Wifi Plugs are no longer seen in HA but work in Meross App

### ISSUE THREAD

**Issue by thorrrr** [krahabb/meross_lan#92]
HI Guys
Both my Wifi Plugs are no longer seen in HA but work well from the app???
In my logs i see 2021-09-28 11:32:23 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration meross_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

I have tried to reinstall but same issue both plugs are getting 1 entity disabled see error [here](https://1drv.ms/u/s!Ao6WCX2miTCJjLE-6vnqSttwZLF_PA?e=iQ6hcg)
I have enabled logs as mentioned 
-->

## Configuration

```yaml
[mss210-1632826578.csv](https://github.com/krahabb/meross_lan/files/7243590/mss210-1632826578.csv)
[mss210-1632826552.csv](https://github.com/krahabb/meross_lan/files/7243592/mss210-1632826552.csv)

Add your logs here.

```

## Debug log

I have added the logger but see nothing in logs ???

Add your logs here.

```See [here ](https://1drv.ms/u/s!Ao6WCX2miTCJjLE_31lGYfUbzRi_hA?e=IOXksS)for log config

**Comment by CTJohnK** [comment]
Any chance you recently updated the firmware on the plugs?  If so, take a look at issue #83 and #89.

**Comment by thorrrr** [comment]
HI i never touched them unless the upgrade themselves mine are Model MSS210 Firmware 6.1.12 Hardware 6.0.0

**Comment by krahabb** [comment]
Hello @thorrrr ,
I can't get your logs (maybe I'm blind with github or you didn't uploaded them) so I can's say anything except like @CTJohnK  stated:
It is likely a problem with the device key. I've added the option to retrieve it from Meross cloud while configuring the devices so you'd have to delete the config entries and re-add to HA. When asked for the device key put in a random string (meross_lan is a bit buggy atm in recognizing key issues when leaving the field blank). Everything should be in issues #83 #89 anyway

**Comment by CTJohnK** [comment]
It looks like the MSS210 units are Apple HomeKit compatible.  I don’t know if you’re using them with HomeKit, but the units I have which are HomeKit compatible, I use the HA HomeKit Controller integration.  Just thought I’d throw that out there as an option.

If you want to stay with Meross LAN, I’d make sure the unit is removed from HA, then Add “Meross LAN” as an integration.  Make sure you set the plug to a static IP address, enter the device’s IP address and throw some random value in the “Device Key” field.  You might have to do this twice and then you should be prompted for your Meross User ID and Password.

At least that is how it worked for me, but that was after I upgraded two of the plugs to the latest firmware (issue #83).

**Comment by thorrrr** [comment]
HI 
Mine have static ips when i first added them i was using them with Meross LAN that is what they have stopped working on

**Comment by thorrrr** [comment]
How do i remove them from HA i have to Meross folders in Custome Folder LAN & Cloud but when i say uninstall in HACS it says remove config ?
I don’t have any config in my yaml for Meross!!!

**Comment by krahabb** [comment]
Hello @thorrrr ,
the disabled entity is just a switch to enable/disable 'Do Not Disturb' mode. It is disabled by default since it is seldom used so I prefered to let it disabled but you can just enable it and use to control the 'presence light' available on the plugs.
Since it is 'do not disturb' it works like this:
- ON -> put device in do not disturb mode i.e. turn off the 'presence' light
- OFF -> disable do not disturb so the plug can 'lights up' showing it's presence and state

The 'incorrect timestamp' is just a warning i.e. something to be aware of (maybe) but usually not hurting. It depends on the fact that the (UTC) time on HA is different (more than 5 seconds) from the one on the plugs so either is wrong.

Both the HA machine and the plug usually get the time from NTP servers over the internet but that really depends on how they're configured and the availability of these 'public' NTP servers.
As I said it shouldn't really hurt (just a warning). On your side you can just check your HA time is correct (this could really matter for every other function in HA).
For the plugs there is nothing you can do: if they're able to connect to the internet they should update their time by themselves. If not: no solution

As a last note: meross_lan is able to detect and sometimes fix incorrect time on some kind of devices (mss310 for example) but this is really dependant on firmware/model so it is not really something I can assure is working. Also, this 'time fixing' feature works only when the device is connected to your own local mqtt broker and not paired to the official meross app (since when paired to meross cloud it should get the time by itself)
