### ISSUE TITLE
3 strings missing in translations/{lang}.json

### ISSUE THREAD

**Issue by ertechdesign** [krahabb/meross_lan#97]
**Is your feature request related to a problem? Please describe.**
While testing my Czech translation I noticed a few missing strings.

**Describe the solution you'd like**
Could the following strings be added to the translation JSONs and wired to the flow in order to get the integration translated?
"required": "Required",
"success": "Success!",
"devicesFound": "We found the following devices:"

**Additional context**
This will provide better UX to non-English speakers.

**Comment by krahabb** [comment]
Hello @ertechdesign ,
I can't figure out where these strings should be placed since, by the look of it they are 'native' string keys used by HA frontend and should be already localized.
I'm not totally aware of how these string translations mixups between the custom code provided and the internal ones used by the frontend (or core) itself.
If I get it right anyway these strings are:
- "required" shown by HA config flow for a field which needs to be filled in UI
- "success" the final message form showing you a completed config flow
- "devicesFound" I'm guessing this is used when discovery shows you new devices to configure
If you can confirm this is where they're shown/used I'll maybe try to better understand how and where HA gets those translated but, at the moment, I'm guessing these should be part of the HA core/frontend pack of translations (and maybe the CZ translation is missing or incomplete for these - reference [here](https://developers.home-assistant.io/docs/translations) )

**Comment by ertechdesign** [comment]
Hello @krahabb ,

You might be right here. I never used the Czech version of Home Assistant and only seen it first time when I smoke tested my commit so I'm not aware of any untranslated strings in the main framework. I'd like to give a Raspberry with Home Assistant to my parents who are Czechs and don't speak any English so I'm excited to make a little contribution here. 😄 

Thank you very much for checking this.
