### ISSUE TITLE
hi, i have one mss310r that work perfectly,  bat my 4 x mss310 work only fewer minutes and than become offline

### ISSUE THREAD

**Issue by No-Smart** [krahabb/meross_lan#99]
## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by No-Smart** [comment]
hi, i have one mss310r that work perfectly, bat my 4 x mss310 work only fewer minutes and than become offline

**Comment by No-Smart** [comment]
Now all device work.

**Comment by No-Smart** [comment]
the problem persists

**Comment by krahabb** [comment]
Hello @No-Smart,
It usually happens with my devices too that sometimes they just fail a connection attempt and then on the next inquiry come online again (so you usually see they'r egoing offline and then coming back usually in 30 seconds on the next connection attempt) and I've never found how to solve this.

If it's a 'persistent' malfunction you can try enabling the tracing feature (which just runs 10 minutes so it might not intercept the error: keep trying until you can catch a trace with an error inside)
You can enable tracing with https://github.com/krahabb/meross_lan#troubleshooting or maybe better, enable debug logging directly in HA so that the logs never stop (until you change the HA configuration.yaml).
For the latter (HA debug log) insert this snippet in your configuration.yaml and restart:
```yaml
logger:
  default: info
  logs:
    custom_components.meross_lan: debug

```

**Comment by krahabb** [comment]
Beside the usual network connection problems, the unavailability of the device after few minutes could be due to an incorrect/absent device key in configuration.
The devices need a proper key to correctly communicate. If the key is left empty there's a form of hack trying to overcome the protocol security features but, being a 'trick' is not at all reliable and so (and it seems latest firmwares are really making it hard to be able to hack) meross_lan could loose the ability to communicate.

You can try follow this [post](https://github.com/krahabb/meross_lan/issues/92#issuecomment-929545495) and the [underlying issue](#83)
